### ISSUE TITLE
持っているものを指定された位置に戻すプログラム

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2014-semi#10]

**Comment by wkentaro** [comment]
This is old. I close.

**Comment by YuOhara** [comment]
I think https://github.com/start-jsk/2014-semi/pull/76 is the code @jiangjun0105 made for this.

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/76
is a program to get item from shelf.

And no one is assigned for this issue.
