### ISSUE TITLE
棚内のアイテムをランダムにつかむプログラム

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#101]

**Comment by wkentaro** [comment]
target binの枠の前に手があるとして、そこからservice callなどでアイテムをつかんで枠の前に戻るというものにしてください。
https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/object-picking-action-server-class.l

**Comment by wkentaro** [comment]
![113c310c-bd45-11e4-908a-c732d2d8391c](https://cloud.githubusercontent.com/assets/4310419/6407639/abc8dde0-be87-11e4-818b-b01985bb5e7d.png)

**Comment by k-okada** [comment]
最終的にはactionlibがいいですね．

**Comment by wkentaro** [comment]
そうすると、target binの前まで行くというところ33-48行目を消す感じで大丈夫ですね。
あと、このプログラムは"Object Verification"のあとにハズレだったら戻すということも行う必要があるので、最初にbin内でstop-graspをが必要だと思います。

**Comment by wkentaro** [comment]
プログラムを作成したら、scripts/master.pyに呼び出しのメソッドを追加して下さい。 #126
