### ISSUE TITLE
次回 2015/02/23(月) 13:00- までにやること

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#102]
* @wkentaro : https://github.com/start-jsk/2014-semi/issues/100
* @iory : https://github.com/start-jsk/2014-semi/issues/101
* @Tnoriaki , @umoji  : 環境設定
* 全員 : Gripperのための素材集め。

**Comment by jiangjun0105** [comment]
環境設定とは具体的になんの意味？
わからないから、聞きたいんです。

**Comment by wkentaro** [comment]
indigoでのcatkin workspaceです。
main.lが実行できるようにして下さい。

2015年2月19日木曜日、Jiang Jun<notifications@github.com>さんは書きました:

> 環境設定とは具体的になんの意味？
> わからないから、聞きたいんです。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/102#issuecomment-75018401>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
@jiangjun0105 さんは環境設定は問題無いですか？

**Comment by jiangjun0105** [comment]
Sorry, but I didn't bring my lab computer back to dormitory, so I haven't try it yet.
For I still have two exams on next Friday, these several days I have to prepare for the exams,
And maybe tomorrow I can't go to school.
I will see you at the meeting after next Friday.

**Comment by wkentaro** [comment]
I see. 加油！
