### ISSUE TITLE
アイテムをorder binに置くプログラム

### ISSUE THREAD

**Issue by Tnoriaki** [start-jsk/2014-semi#104]

**Comment by wkentaro** [comment]
order binの場所はどこでもいいみたいですね。
baxterとpod-lowresの間に置くのがいいと思ったんだけど、どうかな。

2015年2月19日木曜日、Takasugi Noriaki<notifications@github.com>さんは書きました:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/104>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
----------転送メッセージ----------
From: *Romano, Joseph* <romanoj@kivasystems.com>
日付: 2015年2月7日土曜日
件名: [amazonpickingchallenge] Order bin
To: "amazonpickingchallenge@freelists.org" <
amazonpickingchallenge@freelists.org>


Hi Sven,

Some answers inline below:



1) What are the dimensions?
    It is not completely decided yet, but we are considering using this
tote:
http://www.uline.com/Product/Detail/S-19473R/Totes-Plastic-Storage-Boxes/Heavy-Duty-Stack-and-Nest-Containers-Red-24-x-15-x-8?model=S-19473R&RootChecked=yes
2) Is it available for purchase?
    See above. At Amazon we use different totes, but for the sake of the
challenge we'd like to use one that is commonly available (if teams really
feel they need it). Unfortunately U-Line doesn't ship directly
internationally (but you can have them deliver to UPS, who will ship
internationally).
3) Does it have to be placed on a support (e.g. a table) or is the floor OK?
     You can place it anywhere you like, so yes, the floor is OK. You can
also bring or create any table surface you like. We will try to have some
on-hand at the contest for you to use.
4) Must the bin be stationary throughout the trial? Is the robot allowed to
move it on purpose or by accident?
     This is an interesting question we haven't considered. We'll need some
more time to think it over. In principal I am OK with it, but my initial
concern is there might be some form of cheating you could come up with that
we haven't yet considered.
5) Are two bins allowed?
     No, there will only be a single bin.

-Joe
________________________________________
From: amazonpickingchallenge-bounce@freelists.org [
amazonpickingchallenge-bounce@freelists.org] on behalf of Cremer, Sven [
sven.cremer@mavs.uta.edu]
Sent: Friday, February 06, 2015 8:59 AM
To: amazonpickingchallenge@freelists.org
Subject: [amazonpickingchallenge] Order bin

Hi Joe,

I’ve a few questions about the order bin:

1) What are the dimensions?
2) Is it available for purchase?
3) Does it have to be placed on a support (e.g. a table) or is the floor OK?
4) Must the bin be stationary throughout the trial? Is the robot allowed to
move it on purpose or by accident?
5) Are two bins allowed?

Thanks,
Sven

2015年2月19日木曜日、和田 健太郎 / Kentaro Wada<www.kentaro.wada@gmail.com>さんは書きました:

> order binの場所はどこでもいいみたいですね。
> baxterとpod-lowresの間に置くのがいいと思ったんだけど、どうかな。
>
> 2015年2月19日木曜日、Takasugi Noriaki<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/start-jsk/2014-semi/issues/104>.
>>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com <http://www.wkentaro.com>
>
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
@Tnoriaki

order binはこれを本番でも使うみたいなので、だいたい寸法合わせてモデル作ってみてください。(商品の3Dモデルデータとかないですよね..?)
http://m.uline.com/mt/www.uline.com/Product/Detail/S-19473R/Totes-Plastic-Storage-Boxes/Heavy-Duty-Stack-and-Nest-Containers-Red-24-x-15-x-8?model=S-19473R&RootChecked=yes

2015年2月19日木曜日、和田 健太郎 / Kentaro Wada<www.kentaro.wada@gmail.com>さんは書きました:

>
>
> ----------転送メッセージ----------
> From: *Romano, Joseph* <romanoj@kivasystems.com>
> 日付: 2015年2月7日土曜日
> 件名: [amazonpickingchallenge] Order bin
> To: "amazonpickingchallenge@freelists.org" <
> amazonpickingchallenge@freelists.org>
>
>
> Hi Sven,
>
> Some answers inline below:
>
>
>
> 1) What are the dimensions?
>     It is not completely decided yet, but we are considering using this
> tote:
> http://www.uline.com/Product/Detail/S-19473R/Totes-Plastic-Storage-Boxes/Heavy-Duty-Stack-and-Nest-Containers-Red-24-x-15-x-8?model=S-19473R&RootChecked=yes
> 2) Is it available for purchase?
>     See above. At Amazon we use different totes, but for the sake of the
> challenge we'd like to use one that is commonly available (if teams really
> feel they need it). Unfortunately U-Line doesn't ship directly
> internationally (but you can have them deliver to UPS, who will ship
> internationally).
> 3) Does it have to be placed on a support (e.g. a table) or is the floor
> OK?
>      You can place it anywhere you like, so yes, the floor is OK. You can
> also bring or create any table surface you like. We will try to have some
> on-hand at the contest for you to use.
> 4) Must the bin be stationary throughout the trial? Is the robot allowed
> to move it on purpose or by accident?
>      This is an interesting question we haven't considered. We'll need
> some more time to think it over. In principal I am OK with it, but my
> initial concern is there might be some form of cheating you could come up
> with that we haven't yet considered.
> 5) Are two bins allowed?
>      No, there will only be a single bin.
>
> -Joe
> ________________________________________
> From: amazonpickingchallenge-bounce@freelists.org [
> amazonpickingchallenge-bounce@freelists.org] on behalf of Cremer, Sven [
> sven.cremer@mavs.uta.edu]
> Sent: Friday, February 06, 2015 8:59 AM
> To: amazonpickingchallenge@freelists.org
> Subject: [amazonpickingchallenge] Order bin
>
> Hi Joe,
>
> I’ve a few questions about the order bin:
>
> 1) What are the dimensions?
> 2) Is it available for purchase?
> 3) Does it have to be placed on a support (e.g. a table) or is the floor
> OK?
> 4) Must the bin be stationary throughout the trial? Is the robot allowed
> to move it on purpose or by accident?
> 5) Are two bins allowed?
>
> Thanks,
> Sven
>
> 2015年2月19日木曜日、和田 健太郎 / Kentaro Wada<www.kentaro.wada@gmail.com
> <javascript:_e(%7B%7D,'cvml','www.kentaro.wada@gmail.com');>>さんは書きました:
>
>> order binの場所はどこでもいいみたいですね。
>> baxterとpod-lowresの間に置くのがいいと思ったんだけど、どうかな。
>>
>> 2015年2月19日木曜日、Takasugi Noriaki<notifications@github.com>さんは書きました:
>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/start-jsk/2014-semi/issues/104>.
>>>
>>
>>
>> --
>> 和田 健太郎 / Kentaro Wada
>> http://wkentaro.com <http://www.wkentaro.com>
>>
>>
>>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com <http://www.wkentaro.com>
>
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by Tnoriaki** [comment]
了解です！

**Comment by wkentaro** [comment]
closeしてもいいですか？
