### ISSUE TITLE
掃除機のOnOff server をつくる

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#111]
掃除機のOnOff用のシステムをつくる.

rasberry pi？
サーボでボタンを押す？
リレーで電源Onして、On信号を送る？

**Comment by k-okada** [comment]
ARduino でいい気がします．開けてみないとわからないけど，最近の掃除機は電子機器になっているから，取っ手の操作ユーザーインターフェースの部分を分解すると基盤が出てきて，そこのどこかがスイッチになっているので，それをArduinoにつなげて5V/0Vを切り替えれば動くのでは？ダメだったらリレーをつけるひつようがありますね．

ということで，まずは掃除機をゲットしないといけないです．どこかに落ちているといいんだけど，卒業するから入りません，という人がいないかな．もしいなかったら，予算１万円ぐらいで買ってみてください．

**Comment by wkentaro** [comment]
この赤い掃除機はあまり改造などはしてはいけないということでしょうか。
![2015-02-24 13 54 01](https://cloud.githubusercontent.com/assets/4310419/6343505/f1228ae2-bc2c-11e4-86e7-396b45eb881f.jpg)

**Comment by iory** [comment]
予算一万ということですが、買う場合はどこで（例えばamazon）買ってもいいのでしょうか？

**Comment by wkentaro** [comment]
これは結構いい掃除機みたいなのでだめですね。。

**Comment by k-okada** [comment]
いいけど生協とかオリンピックとか赤札堂に行ったら２０００円ぐらいでないかなぁ．買うときは領収書をとっておいてください．

--
◉ Kei Okada

**Comment by iory** [comment]
なるほど。
領収書とっておきます。

**Comment by iory** [comment]
最初はarduinoでやるのでrosserialをインストールしておいてください.
Arduinoのシリアル通信をros化するpackageです.
http://wiki.ros.org/rosserial

**Comment by wkentaro** [comment]
オリンピックで6500円くらいのものを買いました。
吸い込み仕事量は180Wです。
![2015-02-24 18 21 38](https://cloud.githubusercontent.com/assets/4310419/6346330/6b76a6b4-bc52-11e4-9126-1ed27f8cc9da.jpg)
![2015-02-24 18 21 51](https://cloud.githubusercontent.com/assets/4310419/6346331/6b7e0f30-bc52-11e4-8aca-41721d8c5e4a.jpg)

**Comment by wkentaro** [comment]
rosserialのインストールできました。

**Comment by iory** [comment]
掃除機の電源をオンするとそこに直接100V流れる方式になっているので、リレーでon-offすることになりそうです.

**Comment by iory** [comment]
リレーを使うならばソリッドステートリレーを使うと良さそうなのですが, どうでしょうか？
http://akizukidenshi.com/catalog/g/gK-02436/

**Comment by k-okada** [comment]
研究室にないかB1とか８階とか探してみてください．

--
◉ Kei Okada


2015-02-25 14:44 GMT+09:00 ioryz <notifications@github.com>:

**Comment by wkentaro** [comment]
見つからなかったので、買ってきます。

**Comment by Tnoriaki** [comment]
500$B1_$GGc$C$F$-$^$7$?(B


2015/02/25 15:31$B!"(BKentaro Wada <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by Tnoriaki** [comment]
500円で買ってきました
![image1](https://cloud.githubusercontent.com/assets/9031753/6366551/9e3a06aa-bd0a-11e4-87a8-a0f43735f04b.jpeg)

**Comment by wkentaro** [comment]
テスト


2015年2月25日水曜日、Takasugi Noriaki<notifications@github.com>さんは書きました:

> 500円で買ってきました
> [image: image1]
> <https://cloud.githubusercontent.com/assets/9031753/6366551/9e3a06aa-bd0a-11e4-87a8-a0f43735f04b.jpeg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/111#issuecomment-75916867>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by iory** [comment]
arduinoとSSR(リレー)をつないでrosで通信して掃除機のon-offをするようにしました.
https://github.com/iory/2014-semi/blob/on-off-server-111/jsk_2014_picking_challenge/src/switching_gripper.cpp

rosserialを使います. arduinoに書き込んであるので, 使い方としては, 
rosrun rosserial_python serial_node.py _port:=/dev/ttyUSB0
rostopic pub /on_off_gripper std_msgs::Empty 
でスイッチングできます.

**Comment by iory** [comment]
actionlib化しておきます.

**Comment by iory** [comment]
actionlib化しようと思いましたが, rosserialでのactionlibの使用方法がよく分からないので, とりあえずは/on_off_gripper/stateでスイッチのon/offをpublishし, /on_off_gripperにstd_msgs/Emptyでスイッチングするようにしました.
またarduinoのコードはfirmwareというディレクリを作ってそこに入れるようにします.
https://github.com/iory/2014-semi/tree/on-off-server-111/jsk_2014_picking_challenge

terminalからarduinoへ書き込む方法は以下です.
'''
catkin_make jsk_2014_picking_challenge_firmware_switching_gripper-upload
'''

**Comment by wkentaro** [comment]
actionファイルを
https://github.com/wkentaro/2014-semi/blob/iory-on-off-server-111/jsk_2014_picking_challenge/action/VacuumCleanerSwitch.action
のように追加して、
```
#include <jsk_2014_picking_challenge/VacuumCleanerSwitchAction.h>
#include <actionlib/server/simple_action_server.h>


void messageCb(const jsk_2014_picking_challenge::VacuumCleanerSwitchGoalConstPtr& goal, Server* as)
{
    if (goal->switch == "ON") {...} else {...}
    as->setSucceeded();
}

void setup()
{
   ros::init("on_off_server");
   ros::NodeHandle n;
   Server server (n, "on_off_gripper", boost::bind(&execute, _1, &server), false);
   server.start(); 
}

void loop()
{
   nh.spinOnce();
   delay(1);
}
```

という感じだと思ったのですが、どこで失敗しますか。

**Comment by iory** [comment]
```
[100%] Built target rosserial_arduino_generate_messages
[100%] Built target rosserial_msgs_generate_messages
Built target baxter_maintenance_msgs_generate_messages
Built target baxter_core_msgs_generate_messages
Built target rqt_yn_btn_generate_messages
[100%] [100%] Built target jsk_2014_picking_challenge_generate_messages
Built target jsk_2014_picking_challenge_ros_lib
[100%] [100%] Built target rosserial_server_socket_node
Built target rosserial_server_serial_node
-- Generating switching_gripper
-- Configuring done
-- Generating done
-- Build files have been written to: /home/iori/catkin_ws/semi/build/2014-semi/jsk_2014_picking_challenge/firmware
[100%] Built target jsk_2014_picking_challenge_firmware
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[ 90%] Built target atmega328_CORE
[ 95%] Building CXX object CMakeFiles/switching_gripper.dir/switching_gripper.cpp.obj
In file included from /home/iori/catkin_ws/semi/src/2014-semi/jsk_2014_picking_challenge/firmware/switching_gripper.cpp:1:0:
/home/iori/catkin_ws/semi/devel/include/jsk_2014_picking_challenge/VacuumCleanerSwitchAction.h:9:18: fatal error: string: No such file or directory
 #include <string>
                  ^
compilation terminated.
make[6]: *** [CMakeFiles/switching_gripper.dir/switching_gripper.cpp.obj] Error 1
make[5]: *** [CMakeFiles/switching_gripper.dir/all] Error 2
make[4]: *** [CMakeFiles/switching_gripper.dir/rule] Error 2
make[3]: *** [switching_gripper] Error 2
make[2]: *** [2014-semi/jsk_2014_picking_challenge/CMakeFiles/jsk_2014_picking_challenge_firmware_switching_gripper] Error 2
make[1]: *** [2014-semi/jsk_2014_picking_challenge/CMakeFiles/jsk_2014_picking_challenge_firmware_switching_gripper.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
```

これでうまくいかなくなりますね.

**Comment by wkentaro** [comment]
```
$ catkin_make jsk_2014_picking_challenge_firmware_switching_gripper-upload
```
をした時？

**Comment by iory** [comment]
arduinoに書き込む前だから,(ほぼ一緒だけど)
```
$ catkin_make jsk_2014_picking_challenge_firmware_switching_gripper
```
だね.

**Comment by wkentaro** [comment]
こっちの環境ではうまくいくな。。
```
$ catkin_make jsk_2014_picking_challenge_firmware_switching_gripper
[100%] Built target rosserial_msgs_generate_messages_py
[100%] Built target rosserial_msgs_genpy
[100%] Built target jsk_2014_picking_challenge_ros_lib
-- Generating switching_gripper
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wkentaro/semi/build/2014-semi/jsk_2014_picking_challenge/firmware
[100%] Built target jsk_2014_picking_challenge_firmware
make[4]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[ 90%] Built target atmega328_CORE
Scanning dependencies of target switching_gripper
[ 95%] Building CXX object CMakeFiles/switching_gripper.dir/switching_gripper.cpp.obj
Linking CXX executable /home/wkentaro/semi/devel/share/jsk_2014_picking_challenge/switching_gripper.elf
Generating EEP image
Generating HEX image
Calculating image size
Firmware Size:  [Program: 9074 bytes (27.7%)]  [Data: 1466 bytes (71.6%)] on atmega328p
EEPROM   Size:  [Program: 0 bytes (0.0%)]  [Data: 0 bytes (0.0%)] on atmega328p

[100%] Built target switching_gripper
[100%] Built target jsk_2014_picking_challenge_firmware_switching_gripper
```

**Comment by wkentaro** [comment]
includeにいれると、こっちでも失敗しました。

2015年3月2日月曜日、ioryz<notifications@github.com>さんは書きました:

> arduinoに書き込む前だから,(ほぼ一緒だけど)
>
> $ catkin_make jsk_2014_picking_challenge_firmware_switching_gripper
>
> だね.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/111#issuecomment-76706785>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
@iory と話して
rosserialがactionlibに対応していない可能性があるので、serverとpublisherで対応することになりました。

2015年3月2日月曜日、和田 健太郎 / Kentaro Wada<www.kentaro.wada@gmail.com>さんは書きました:

> includeにいれると、こっちでも失敗しました。
>
> 2015年3月2日月曜日、ioryz<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> arduinoに書き込む前だから,(ほぼ一緒だけど)
>>
>> $ catkin_make jsk_2014_picking_challenge_firmware_switching_gripper
>>
>> だね.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/start-jsk/2014-semi/issues/111#issuecomment-76706785>
>> .
>>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com <http://www.wkentaro.com>
>
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
