### ISSUE TITLE
baxterの腕がぶれる件について

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#115]
baxterの腕を動かしている時にブレが大きく、
壁に衝突する場合があるのですが対策はあるでしょうか？

**Comment by k-okada** [comment]
どういう姿勢列を送るとぶれて，どういう姿勢列をいれるとブレないかしらべてみましょう．
例えばブレる姿勢列にたいして，時間を大きくしていって動作をゆっくりしていくと，ぶれなくなるのか，
などが興味が有ります．
次に，途中の速度の与え方，加速度の与え方，最後にはBaxter側の逆動力学的なパラメータがどうか，
というところまで掘れると思います．

--
◉ Kei Okada


2015-02-23 20:23 GMT+09:00 ioryz <notifications@github.com>:

**Comment by iory** [comment]
なるほど、調べてみます。

**Comment by wkentaro** [comment]
おそらくaction serverの問題で、現状angle-vectorだとブレるが、angle-vector-sequenceで3つ以上のavsを送ればほぼブレないようです。
最終審査ビデオ用にangle-vector-sequenceで動作させるようにプログラム直しておきます。

**Comment by k-okada** [comment]
一番早い方法でいいですが，
１） Action Serverを直す
２） roseusの:anlge-vectorで対応する
３） プログラムを直す

があります．２）は稲垣くんがいれば簡単に出来ると思います．


--
◉ Kei Okada


2015-03-11 19:19 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by aginika** [comment]
1)をやっておきますと今日相談しましたが、
とりあえず
jsk-ros-pkg/jsk_robot#279で2)を行うようなものを書きました。（初期姿勢と中間点を追加するのみ）
が、ぶれまくりな気がしています。
@wkentaro angle-vector-sequenceで渡した関節角は初期姿勢と中間点とゴールでしょうか？

**Comment by wkentaro** [comment]
初期姿勢からゴールまでの軌道を小分けしてIKを解き、
`(send *baxter* :angle-vector-sequence (list av初期, av中間点1av, av中間点2, avゴール) (list 10000 10000 10000 10000)))`
という感じで送りました。

**Comment by aginika** [comment]
細かく分けるとうまくいくと聞いて、１０分割ほどするようにしたら、
実際にぶれが少なくなったと思います。

**Comment by aginika** [comment]
baxter_interfaceだけ、srcに用意して、ver1.0.0で運用しています。
問題があったら報告してください。
一切ぶれません。

**Comment by wkentaro** [comment]
@iory closeお願いします。
