### ISSUE TITLE
インタラクティブにtarget binへの移動ができるようにする

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#116]
main.lを改良する方針で、いまは`(test-ik-target)`しかないものを例えば`(move2target :larm 'a)`としてbin_Aに移動させるという風にすると便利かと思います。

**Comment by wkentaro** [comment]
実機を動かしているときに効率の良いように関数などを作ります.

**Comment by wkentaro** [comment]
@umoji これやりますか？

**Comment by umoji** [comment]
了解です。

**Comment by wkentaro** [comment]
途中まで作りました。
https://github.com/wkentaro/2014-semi/tree/improve-main-116

**Comment by umoji** [comment]
これ以上に作らなきゃいけないものってありますか？

**Comment by wkentaro** [comment]
大体これでいいかなという感じですが、気になるところがあれば変えてください。
なければそのままPR送ってください。

**Comment by wkentaro** [comment]
すこし直すところがあったので、もし変えるところがなければ、僕がPR送って起きます。

**Comment by umoji** [comment]
一応PR送ってみたのですが、直して送っていただけると幸いです。

**Comment by wkentaro** [comment]
送りました。
https://github.com/start-jsk/2014-semi/pull/120
