### ISSUE TITLE
kinect2を動かす

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#118]
baxterにkinect2がついたので, kinect2を動かしてみましょう.
https://github.com/code-iai/iai_kinect2

**Comment by iory** [comment]
baxterからの画像
![kinect2onbaxter](https://cloud.githubusercontent.com/assets/4690682/6344421/a4de56ac-bc3b-11e4-8036-c530a9a5d465.png)

**Comment by iory** [comment]
udev ruleを設定するのを忘れるとno kinect2 device foundとか出てくるので気をつけてください.

**Comment by iory** [comment]
rosrun image_view image_view image:=/kinect2/rgb/image
rosrun image_view image_view image:=/kinect2/mono/image
とかで試してみてください.

**Comment by wkentaro** [comment]
できました。

**Comment by iory** [comment]
とりあえず接続は確認できたのでcloseします.

**Comment by wkentaro** [comment]
pointcloudが取りたい場合
`roslaunch kinect2_bridge kinect2_bridge.launch`

**Comment by iory** [comment]
```
rosrun image_view image_view image:=/kinect2/depth/image
```
だとdepthは表示できないので, rvizで表示してください.
![depth_map](https://cloud.githubusercontent.com/assets/4690682/6502048/07255e18-c363-11e4-8dba-67280305c22d.png)
