### ISSUE TITLE
travisのテストが通らない

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#123]
travisのテストが通らず、以下のように失敗しているのですが、原因がわかりません。何が問題でしょうか？

```
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis/11799/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis/11799/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis/11799/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis/11799/ building.. False result... FAILURE
+++exit 1
++++'[' 3 = 1 ']'
```

**Comment by wkentaro** [comment]
直りました。moveit_resourcesがbuild_dependに必要みたいです。
https://github.com/start-jsk/2014-semi/pull/128https://github.com/start-jsk/2014-semi/pull/128

**Comment by jiangjun0105** [comment]
Sorry, I konw it's really a little annoying, but I want to ask you some questions once again.
I search "travis" by google, and find some basic introduction of it：

Travis CI automatically detects when a commit has been made and pushed to a GitHub repository that is using Travis CI, and each time this happens, it will try to build the project and run tests.
(quote from wikipedia)

Dose it mean that after you make a commit, you will receive a notify telling you the test result from Travis?
What's the content of the test? Travis will compile the code and run it just like what programmers do?
Finally, if I want to use Travis, what do I need to do? install it? or just check a confirmation box in GitHub?

I am not anxious to know it, so please answer it when you are free.

**Comment by wkentaro** [comment]
Here is tutorial for travis. http://docs.travis-ci.com/user/getting-started/

Simply put,  you should do following to start travis::
* prepare .travis.yml and comit it to github repo
* sign in travis and register the github repo
the process of testing (ex. installing ROS or catkin_make building) is written in the yaml file. Every times you send PR to the repo, travis automatically has done the test and we can find if it's safe to merge the PR or not.
