### ISSUE TITLE
Object Verificationのための姿勢になるプログラム

### ISSUE THREAD

**Issue by Tnoriaki** [start-jsk/2014-semi#127]
アイテムを持っている腕を頭のうえにあるカメラに見える様に移動させて
rqt_yn_btnにサービスコールしrqt_yn_btnの判断を返すプログラム

**Comment by wkentaro** [comment]
プログラムを作成したら、scripts/master.pyに呼び出しのメソッドを追加して下さい。 #126

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/147
Merged so I close this.
