### ISSUE TITLE
publisherのqueue_sizeを指定しないことによるwarning

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#129]
rospy.Publisherの引数にqueue_sizeを指定しないとwarningが出ます。
indigoで、publisherのqueue数を指定できるようになったことによるようです。
http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers#queue_size:_publish.28.29_behavior_and_queuing

**Comment by wkentaro** [comment]
ネットワークの接続が悪くなければ、1/2/3程度で良いそうなので、1にしておきました。

**Comment by garaemon** [comment]
基本的には何も考えずに1がオススメです

2015年2月27日金曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Closed #129 <https://github.com/start-jsk/2014-semi/issues/129>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/129#event-243237432>.
>


-- 
from iPhone

**Comment by wkentaro** [comment]
なるほど、ありがとうございます。
