### ISSUE TITLE
次回の集合日 (2015-03-02)

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#133]
次回の集合日を決めましょう。
各人のタスクを終わらせて集まるという感じがいいかと思いますが、
今持っているタスクいつ頃できそうですか？
あとそのときまでに、何個か似た商品を買ってくるようにしたいですね。

**Comment by wkentaro** [comment]
私は3日集合であれば、 #132 を終わらせられそうです。

**Comment by iory** [comment]
3日集合で大丈夫です.
一応今日も研究室行ってみます.

**Comment by wkentaro** [comment]
今日も13時からで大丈夫ですか。


2015年3月2日月曜日、ioryz<notifications@github.com>さんは書きました:

> 3日集合で大丈夫です.
> 一応今日も研究室行ってみます.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/133#issuecomment-76654836>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
