### ISSUE TITLE
color_histogram_matcherを用いた物体判別

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#135]
https://github.com/start-jsk/2014-semi/issues/91

**Comment by wkentaro** [comment]
[build error]Converting pcl::PCLPointCloud2 to sensor_msg::PointCloud2
http://answers.ros.org/question/204244/build-errorconverting-pclpclpointcloud2-to-sensor_msgpointcloud2/

**Comment by garaemon** [comment]
You don't link correct libraries. It looks cmake is wrong

**Comment by wkentaro** [comment]
ありがとうございます。変換できました。
```
link_directories(${pcl_ros_LIBRARIES})
target_link_libraries (pcd_read
  ${pcl_ros_LIBRARIES})
```

**Comment by wkentaro** [comment]
認識の仕方ですが、以下でやろうと思います。
* カメラ画像からヒストグラムを計算(color_histogram_matcherのinput_reference_cloud, output_reference).
* ヒストグラムのマッチング(自分で)

color_histogram_matcherは、姿勢を判断するものでそこにあるものを判別するものではないという認識であっているでしょうか。

**Comment by k-okada** [comment]
いや，どちらかというと，
color histgram matcherはヒストグラムが同じかどうかみるので，姿勢は判断せずに，
入力のpointcloudがrefernceと同じ色味をもっているかを判別しているんだとおもいます．

**Comment by iory** [comment]
color_histogram_matcherなのですが, RGBのヒストグラムのcoefficientの合計が大きい物ほどそれである確率が高いとしているのですが, 確率を求めるのにもっと良い方法はあるでしょうか？

**Comment by YuOhara** [comment]
OpenCVにcvCompareListって関数があって、それで4つくらいの方法が試せるみたいです。
http://docs.opencv.org/modules/imgproc/doc/histograms.html#comparehist

https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/src/color_histogram.cpp
はそのうちのインターセクションを自分で実装して使ってます

**Comment by YuOhara** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/src/color_histogram_sliding_matcher.cpp
インターセクションはこっちでした

**Comment by iory** [comment]
ありがとうございます.

**Comment by wkentaro** [comment]
closeお願いします。
ただテストが必要かもしれませんね。
