### ISSUE TITLE
.gitignoreを追加したい

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#136]
.gitignoreをレポジトリのルートに追加したいのですが、
(pycファイルなどを無視するため)

Ros用のものを追加する形でいいでしょうか。
https://github.com/github/gitignore/blob/master/ROS.gitignore

**Comment by k-okada** [comment]
はい、どうぞ

2015年3月3日火曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> .gitignoreをレポジトリのルートに追加したいのですが、
> (pycファイルなどを無視するため)
>
> Ros用のものを追加する形でいいでしょうか。
> https://github.com/github/gitignore/blob/master/ROS.gitignore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/136>.
>


-- 
--
◉ Kei Okada
