### ISSUE TITLE
virtual force publisherの使い方

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#143]
@k-okada 
以前 #91 でvirtual_force_publisherが挙げられていましたが, 
使い方など参考にするものはあるでしょうか？

**Comment by k-okada** [comment]
1) ノードをたちあげる
2) wrench をrvizで表示する
3) eusへはsend *ri* :state :force-vector に自動ではいったか

というような手順かな。わからなければ呼び出して下さい

2015年3月3日火曜日、ioryz<notifications@github.com>さんは書きました:

> @k-okada <https://github.com/k-okada>
> 以前 #91 <https://github.com/start-jsk/2014-semi/issues/91>
> でvirtual_force_publisherが挙げられていましたが,
> 使い方など参考にするものはあるでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/143>.
>


-- 
--
◉ Kei Okada

**Comment by aginika** [comment]
どういう目的か分かっていませんが、
baxterが/robot/limb/left/endpoint_stateでbaxter_core_msgs::EndpointStateをpublishしていて、

```
Header header
geometry_msgs/Pose   pose
geometry_msgs/Twist  twist
geometry_msgs/Wrench wrench
```
を出してます。

したのは、wrenchだけを抜き出してpublishしているコードです。
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_lifelog/estimated_endeffector.l

**Comment by k-okada** [comment]
なるほど。virtual...はいらないですね

以下をまずは表示してどういう感じになるか？見てみましょう

2015年3月4日水曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> どういう目的か分かっていませんが、
>
> baxterが/robot/limb/left/endpoint_stateでbaxter_core_msgs::EndpointStateをpublishしていて、
>
> Header header
> geometry_msgs/Pose   pose
> geometry_msgs/Twist  twist
> geometry_msgs/Wrench wrench
>
> を出してます。
>
> したのは、wrenchだけを抜き出してpublishしているコードです。
>
> https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_lifelog/estimated_endeffector.l
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/143#issuecomment-76971875>.
>


-- 
--
◉ Kei Okada

**Comment by iory** [comment]
ありがとうございます
やってみます

**Comment by iory** [comment]
wrenchを読みだして表示してみました.
![wernch](https://cloud.githubusercontent.com/assets/4690682/6500249/4ce63790-c34c-11e4-8237-6c647adc7a09.png)

これから, 物を持った時の重さを求めるには, どういった方法があるでしょうか？

**Comment by k-okada** [comment]
wrenchのforceのnormを見たらいいともいます．

--
◉ Kei Okada

**Comment by iory** [comment]
とりあえず, normを見てみました.
https://github.com/iory/2014-semi/blob/weight-publisher-143/jsk_2014_picking_challenge/euslisp/wrench-force-norm.l
![end_effector_norm](https://cloud.githubusercontent.com/assets/4690682/6501712/2682b660-c35f-11e4-9839-856f39a02dac.png)

トルクによる商品推定の戦略としては,
画像を撮るときの姿勢が一定なので, その時の重さをあらかじめ測っておいて(オフセットをとる), 各商品を持った時の重さを測っておき, 最終的に確率を返すという方針で行こうと思うのですがどうでしょうか？

**Comment by Michi-Tsubaki** [comment]
> eusへはsend ri :state :force-vector に自動ではいったか

入ってませんでした！
