### ISSUE TITLE
issue, milestone管理に関して

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#144]
いまは、大事なissue全てに「最終ビデオ審査」のmilestoneを割り振っていますが、
全体の集合日をmilestoneで指定して、taskにmilestoneを割り振る感じにしましょうか。 @iory

**Comment by iory** [comment]
なるほど。
そのほうが小分けにして作業の進捗がわかるので賛成です。

**Comment by wkentaro** [comment]
とりあえず、明日の分を作成しました。https://github.com/start-jsk/2014-semi/milestones
