### ISSUE TITLE
次回の集合日 (2015-03-04投稿)

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#146]
3月5日の13時からでいいでしょうか。
それまでにMilestoneのものを完成させるのが目標です。
タスクリスト: https://github.com/start-jsk/2014-semi/milestones/2015-03-05

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/milestones/2015-03-05

**Comment by wkentaro** [comment]
#135 ですが、kinectがないと試せない（とわかった）ので、明日研究室で開発します。そのため、明日までというのは難しいです。

**Comment by iory** [comment]
13時からで大丈夫です。
