### ISSUE TITLE
Kudu(Ubuntuパソコン)をセットアップする

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#148]
Ubuntuパソコンを学習データなどを保存して使いたいと思います。

やること

* object dataのダウンロード
* sift特徴量の抽出

**Comment by k-okada** [comment]
kinectをつなげているデスクトップを使うのがいいともいます．そのPCさえあれば，必要なlaunchも上がって，デターも蓄積されている，という具合に．

--
◉ Kei Okada


2015-03-05 13:37 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
了解です。そちらでやってみます。
