### ISSUE TITLE
トルクによる商品の推定

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#150]
トルクを測って商品を持った時に,
確率的に商品を推定する.

**Comment by iory** [comment]
重さを推定する用に, actionlibで商品の重さを調べるようにしました.
https://github.com/iory/2014-semi/blob/weight-publisher-143/jsk_2014_picking_challenge/src/learning_weight.cpp

```
$ roslaunch jsk_2014_picking_challenge learning_weigh.launch
$ rosrun jsk_2014_picking_challenge learning_weight_client.py -f FILE_NAME
```

**Comment by wkentaro** [comment]
このプログラムは、各姿勢でのForce値を覚えておいて、リクエストに対してそのときとの差を計算して返すというものですか？

**Comment by wkentaro** [comment]
learning_weight.cppで重さをデータに保存したらダメなのでしょうか。

**Comment by iory** [comment]
これはクライアントからリクエストした時に重さをサンプル数を100とかとってその平均と標準偏差を測って、データとしてとったほうが便利そうかと思ったので、learning_weight.cppはactionlibのサーバーにしてます。

データをとったあとに推定する段階でもlearning_weight.cppが使いまわせると思ったのでこのままがよいかと。

**Comment by iory** [comment]
@k-okada 
baxterのアームを同じ位置にしたときに, wrenchのnormをサンプル数100でとった場合の値をとると, 値が同じような値にならずに変わってしまうのですが, これは読む値が間違っているのでしょうか？
https://github.com/iory/2014-semi/blob/weight-publisher-143/jsk_2014_picking_challenge/euslisp/wrench-force-norm.l
  https://github.com/iory/2014-semi/blob/estimation-by-weight-150/jsk_2014_picking_challenge/src/calc_weight_mean.cpp

**Comment by k-okada** [comment]
どれぐらいかわるでしょうか？グラフが表示できるかな？
ヒント：rqt_graph

--
◉ Kei Okada

**Comment by aginika** [comment]
この作戦は没になったのでしょうか？

**Comment by iory** [comment]
@aginika いまのところ没になっています

**Comment by k-okada** [comment]
できれば復活したいところです．werenchの値と，各関節のeffortの値を，ものを持っている時，持っていない時，で調べたいところです．

--
◉ Kei Okada

**Comment by aginika** [comment]
最悪、はかれないのであれば、
ROSでtopicの出せる高精度電子はかりをbaxterの横にでも置くと
識別指標になるのかもしれません。

**Comment by wkentaro** [comment]
もともと2-300グラムの誤差があるというのと、掃除機の蛇腹のしなり具合によって値が変わるので難しそうです。
