### ISSUE TITLE
Kinectのセンサ情報から物体を認識する際のマスク画像を作成したい

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#151]
kinectから取れるPointCloudを使って、手に持っている物体だけ残すようにマスク画像を作成したいと考えていますが、PointCloudから計算できるPointIndicesを使うことでできるでしょうか。

https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/mask_image_to_point_indices_nodelet.cpp
の逆の操作になると思います。

**Comment by k-okada** [comment]
self filterです @aginika が対応してくれるはず．

**Comment by wkentaro** [comment]
なるほど、了解です。

**Comment by garaemon** [comment]
これでは?

https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/point_indices_to_mask_image_nodelet.cpp

**Comment by wkentaro** [comment]
見落としていました。ありがとうございます。

**Comment by wkentaro** [comment]
@aginika さんが時間があればやってくださるとのことです。
@Tnoriaki @iory

**Comment by aginika** [comment]
jsk-ros-pkg/jsk_recognition#765
で距離で除外した画像を作るlaunchを加えました。参考になると幸いです。

なんでか、self filterがちゃんと聞いてないので、それは今後解決します。

**Comment by wkentaro** [comment]
ありがとうございます。
