### ISSUE TITLE
siftでの認識精度のテスト

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#155]
今回のChallengeでは、物体認識で位置情報が重要でないのでPointCloudでなく画像メインで行う予定です。

方針
1. PointCloudから物体の位置を把握し、その部分のカメラ画像を切り取る。
2. 切り取ったカメラ画像をもとに判別(sift, color, etc.)

とりあえず、siftのプログラムでの認識精度をテストすることにします。

**Comment by wkentaro** [comment]
物体の認識を何度か試しましたが、sift単体での判別だと、組み合わせによっては難しいと思います。どのような場合に難しいかはもう少しデータを集めると数字で報告できそうですが、形が曖昧（変化できる）ものだと誤認識しやすいという印象で、色情報を使わないと人形などは判別が難しそうです。

**Comment by garaemon** [comment]
点群が綺麗にsegmentationできていれば、色ヒストグラムでかなり良い精度がいけると思います


SIFTでやる場合は、BoFのような全てのSIFT特徴ベクトルを足すといったものが有効であると考えられますね。

**Comment by wkentaro** [comment]
なるほど。 SIFTに関しては、
今は特徴量（全てを使って）の距離マッチングでのマッチング数で判別を行っていますが、BoFへ改良したいと思います。
判別にSVMがよく使われるようですが、berkeleyの提供している学習データはかなり豊富でNNの方がいいかもしれないので、どちらも試そうと考えています。

color_histogramに関しては @iory にお願いしています。

**Comment by k-okada** [comment]
そうですね．まだまだ先の話でいいですが，それができたら
コンテキスト，状況，などなどに基づいて認識していくのがよいです．
コンピュータビジョンとロボットビジョンの違いはこの分野で，いまは
ロボットが出回っていないからコンピュータビジョンアプローチが優勢ですが
そのうちロボットビジョンアプローチになっていくと思います．
特に今回のような例は有効に思います．
顕著性 ロボット 認識 とかで検索すると色々論文が出てくると思います．

--
◉ Kei Okada


2015-03-11 3:28 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by garaemon** [comment]
色はかなり強力な特徴で、BoFでも最近のDNNでもちょっと試すくらいだと精度変わらない気がしますね。

見分けられないケースがあれば、以下のようなことを考えてみると良いかも
1. 大きさが異なるか？なら点群の大きさというような特徴を使う
2. 重さが異なるか？なら重さの特徴を使う
3. 形が大きく違うか？なら法線の特徴を使う

2015年3月15日日曜日、Kei Okada<notifications@github.com>さんは書きました:

> そうですね．まだまだ先の話でいいですが，それができたら
> コンテキスト，状況，などなどに基づいて認識していくのがよいです．
> コンピュータビジョンとロボットビジョンの違いはこの分野で，いまは
> ロボットが出回っていないからコンピュータビジョンアプローチが優勢ですが
> そのうちロボットビジョンアプローチになっていくと思います．
> 特に今回のような例は有効に思います．
> 顕著性 ロボット 認識 とかで検索すると色々論文が出てくると思います．
>
> --
> ◉ Kei Okada
>
>
> 2015-03-11 3:28 GMT+09:00 Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
>
> > なるほど。 SIFTに関しては、
> > 今は特徴量（全てを使って）の距離マッチングでのマッチング数で判別を行っていますが、BoFへ改良したいと思います。
> >
> >
> 判別にSVMがよく使われるようですが、berkeleyの提供している学習データはかなり豊富でNNの方がいいかもしれないので、どちらも試そうと考えています。
> >
> > color_histogramに関しては @iory <https://github.com/iory> にお願いしています。
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/start-jsk/2014-semi/issues/155#issuecomment-78116791
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/155#issuecomment-80744445>.
>


-- 
✉︎ from iPhone

**Comment by wkentaro** [comment]
テスト結果:
https://github.com/wkentaro/2014-semi/blob/test-sift-matching-155/jsk_2014_picking_challenge/data/test_sift_matching_result.csv

今回テストに使った画像は正面からのみなので、正解になりやすいとは思いますが、
それでも以下のような物体で判別を誤っています。

   - クレヨン
   - ぬいぐるみ
   - コンセント保護プラグ
   - アヒルのおもちゃ
   - 本

​

2015-03-15 11:11 GMT+09:00 Ryohei Ueda <notifications@github.com>:

> 色はかなり強力な特徴で、BoFでも最近のDNNでもちょっと試すくらいだと精度変わらない気がしますね。
>
> 見分けられないケースがあれば、以下のようなことを考えてみると良いかも
> 1. 大きさが異なるか？なら点群の大きさというような特徴を使う
> 2. 重さが異なるか？なら重さの特徴を使う
> 3. 形が大きく違うか？なら法線の特徴を使う
>
> 2015年3月15日日曜日、Kei Okada<notifications@github.com>さんは書きました:
>
> > そうですね．まだまだ先の話でいいですが，それができたら
> > コンテキスト，状況，などなどに基づいて認識していくのがよいです．
> > コンピュータビジョンとロボットビジョンの違いはこの分野で，いまは
> > ロボットが出回っていないからコンピュータビジョンアプローチが優勢ですが
> > そのうちロボットビジョンアプローチになっていくと思います．
> > 特に今回のような例は有効に思います．
> > 顕著性 ロボット 認識 とかで検索すると色々論文が出てくると思います．
> >
> > --
> > ◉ Kei Okada
> >
> >
> > 2015-03-11 3:28 GMT+09:00 Kentaro Wada <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> >
> > > なるほど。 SIFTに関しては、
> > > 今は特徴量（全てを使って）の距離マッチングでのマッチング数で判別を行っていますが、BoFへ改良したいと思います。
> > >
> > >
> >
> 判別にSVMがよく使われるようですが、berkeleyの提供している学習データはかなり豊富でNNの方がいいかもしれないので、どちらも試そうと考えています。
>
> > >
> > > color_histogramに関しては @iory <https://github.com/iory> にお願いしています。
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/start-jsk/2014-semi/issues/155#issuecomment-78116791
> > >.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/start-jsk/2014-semi/issues/155#issuecomment-80744445>.
>
> >
>
>
> --
> ✉︎ from iPhone
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/155#issuecomment-80798188>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by YuOhara** [comment]
5/17は結構ミスってますね・・・
もしかしたら，しきい値とか で，結果が変わったりするでしょうか？
ここのプログラムでは，
```
 good_matches = [m for m, n in matches if m.distance < 0.75*n.distance]
```
で0.75となってるところです．
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/src/point_pose_extractor.cpp
ではそのパラメータをdynamic_reconfigureで変えられるようになってます．

**Comment by wkentaro** [comment]
しきい値を
* 0.6
* 0.75
* 0.9

の3つにしてやってみました。
0.9だと結果はほとんどFalseになりましたが、他はそれぞれ正解になるものが異なっているので、注目する商品によってしきい値をうまく変えれば正解率は上がりそうです。
https://github.com/wkentaro/2014-semi/tree/test-sift-matching-155/jsk_2014_picking_challenge/data/test_result

**Comment by wkentaro** [comment]
color histogramでのテストも行いましたが、
今回使った画像は
https://github.com/wkentaro/2014-semi/tree/test-sift-matching-155/jsk_2014_picking_challenge/data/raw_img
で、商品の部分だけセグメントされているわけでないためか、結果は全てFalseでした。
https://github.com/wkentaro/2014-semi/blob/test-sift-matching-155/jsk_2014_picking_challenge/data/test_result/test_color_histogram_matching_result.csv

**Comment by k-okada** [comment]
白色がヒストグラムにはいっているかな？入っていないかな？入れないようにしないとかなり引っ張られると思います．
この画像だったら，まずはhsvでsが小さいもの（白黒）の部分はぬいて，http://en.wikipedia.org/wiki/HSL_and_HSV
でいうと外側の部分のドーナッツ部分で比較する必要が有ります．

ということで，
１）適当な画像を作る．国旗などで白黒がないもの．http://ja.wikipedia.org/wiki/%E5%9B%BD%E6%97%97%E3%81%AE%E4%B8%80%E8%A6%A7
アゼルバイジャン，アルメニア，アルバニア，ウクライナ，エクアドル，カメルーン，ガーナ
あたりで認識できるか確認

２）　白黒を（自動で）抜いて認識できるか．つまり新は除外してドーナッツ部分だけでヒストグラムをつくっているか確認．ドイツと南オセチアの類似度が高く出ればOKか．

かな．







--
◉ Kei Okada

**Comment by wkentaro** [comment]
>
色はかなり強力な特徴で、BoFでも最近のDNNでもちょっと試すくらいだと精度変わらない気がしますね。

まず色判別の精度をあげようと思います。 #184
