### ISSUE TITLE
グリッパーで物を掴めたかの判定

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#156]
掃除機でうまくつかめた時に、高い掃除機だったら吸い込んだかの吸い込んでいないかがセンサーで分かるようになっているのですが、今の安い掃除機だと単純なon/offの制御だけなので判定ができません。

案：
物を掴んだ時の重さで判定
センサーをとりつけて判定 -> どんなセンサーをつかうのか(圧力計...etc)

**Comment by aginika** [comment]
>>物を掴んだ時の重さで判定
昨日一緒に作業してEnd effectorのチカラの値を見ましたが、
あまり持っているときと持っていないときの差がはっきりとしなかったと思います。

どうするか決まりましたか？

**Comment by iory** [comment]
いえまだ決まっていません。
何か良い方法ありますでしょうか？

**Comment by iory** [comment]
3月16日以降の話ですが、
吸い込んでいる時には消費電力が変わると思うのでその消費電力から判断するとか、
物体が吸い付いた時には音が変わるのでその音から判断するなどを考えています。

**Comment by iory** [comment]
今更気づいたのですが、吸込み時に赤色のLEDが点灯するのでこれで判断できるかもしれません。

**Comment by iory** [comment]
![off](https://cloud.githubusercontent.com/assets/4690682/6613331/47e452ae-c8ce-11e4-8ccd-467a0dd65616.jpeg)
![on](https://cloud.githubusercontent.com/assets/4690682/6613332/4b390710-c8ce-11e4-8bf4-a0f5e75a6bc9.jpeg)

**Comment by wkentaro** [comment]
吸い込み時に回路に付いているLEDに3Vの交流電圧がかかり、点灯するようです。
Arduinoのアナログ入力で計測する形で問題ないでしょうか。

**Comment by iory** [comment]
問題ない気がします.
ただ交流電圧なのでarduinoで負電圧の入力ができないような気がするので, 
そこらへんも試してみます.

**Comment by wkentaro** [comment]
それについては調べた時、負電圧は出来ないから、簡単な回路を作ればいいと書いてありました。(3Vを中心にすると)

2015年3月27日金曜日、ioryz<notifications@github.com>さんは書きました:

> 問題ない気がします.
> ただ交流電圧なのでarduinoで負電圧の入力ができないような気がするので,
> そこらへんも試してみます.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/156#issuecomment-86889444>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by iory** [comment]
掃除機についていた圧力センサが機械式のようで、それで対応しました。

**Comment by iory** [comment]
rostopic echo /gripper_grabbed/state で掴んでいるかいないかがわかります.
https://github.com/iory/2014-semi/blob/is-gripper-grabbed-156/jsk_2014_picking_challenge/firmware/switching_gripper.cpp

**Comment by iory** [comment]
あとは実際に動かしてみて判定できそうか試してみます

**Comment by iory** [comment]
吸い込んでいるときはしっかりTRUEが帰ってきているので大丈夫そうです。
![screenshot from 2015-04-08 16 05 47](https://cloud.githubusercontent.com/assets/4690682/7040473/b8e94878-de0a-11e4-832e-55aa1b75e5ac.png)

**Comment by wkentaro** [comment]
finished so i  close this.
