### ISSUE TITLE
最終審査ビデオ用のmasterプログラム作成

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#158]
1.  個々の動作を動くようにする(問題のある部分は作成者に報告)
1.  連続して動作できるようにする(途中で止まってもある程度自動復旧できるように)
1.  作成・実行しながら、うまくつかめないものや判別できないものをメモ
1.  (3.より順序の計画アルゴリズム)

**Comment by wkentaro** [comment]
https://github.com/jsk-ros-pkg/jsk_roseus/issues/260

**Comment by iory** [comment]
@k-okada  
PRのマージお願いします.
https://github.com/start-jsk/2014-semi/pull/159
https://github.com/start-jsk/2014-semi/pull/149
