### ISSUE TITLE
baxter headのangle-vector

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#165]
```
(send *baxter* :head :angle-vector #f(80))
(send *ri* :angle-vector (send *baxter* :angle-vector))
```

としても、headが動きません。
何か立ち上げるノードなどありますか？

**Comment by wkentaro** [comment]
head_action_server.pyを手元のPCで立ち上げても動かないです。

**Comment by aginika** [comment]
すいません。
head動かすのは、僕がやらないとできないと思います。
４時過ぎについたら対応します。

**Comment by iory** [comment]
@aginika  今日ではなくても大丈夫です。

**Comment by wkentaro** [comment]
baxter sdkのバージョンv1.1.0にeusも対応したことで、現在動いています。
