### ISSUE TITLE
arduinoの配線を綺麗にする

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#170]
線がぬけやすかったり、トライアックがショートしたりして
良く掃除機が沈黙するので新たに綺麗に作り直しましょう。

**Comment by k-okada** [comment]
アンプ側はhttp://magicaso1.web.fc2.com/helmet/20090730-07.jpg
みたいな感じで熱収縮チューブで覆うといいと思います。

**Comment by k-okada** [comment]
あとarduinoいまは大きいけどいいやつがあると
http://oriental-robotics.jimdo.com/?mobile=1#PhotoSwipe1426523565349
みたいにかっこよく治るかもしれないです
研究室内とか8Fのバクイ君や笹渕君に聞いてみてください
K-okadaよくわからないコトにこだわっているので、
よいえば探してくれると思います

**Comment by iory** [comment]
なるほど、分かりました。
研究室の方に聞いてみていろいろ参考にしようと思います。

**Comment by aginika** [comment]
arduinoぶらさがっている状態なので、掃除機から離れないようにアタッチメントあると幸いです。

**Comment by k-okada** [comment]
３Dプリンタで作りましょう．ぼくでもCADは３時間ぐらいでわかるようになりました．

--
◉ Kei Okada


2015-03-18 21:11 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by iory** [comment]
@aginika 了解です
@k-okada CADのソフトとかはありますでしょうか？

**Comment by k-okada** [comment]
@m1a1k0o さんかそに隣に座っている浅野くんに聞いてみてください

**Comment by iory** [comment]
いろいろ聞いてみた結果, 
アンプの側はヒートシンクとかをしっかり固定したほうが良いということでユニバーサル基板に移植します.
arduino nanoも借りてみたのでコンパクトにできるかやった後に,
CADでケースを作ってみます.

**Comment by iory** [comment]
リレー側の回路をユニバーサル基板に移植しました。
![2015-04-06 17 34 47](https://cloud.githubusercontent.com/assets/4690682/7002407/0b13e004-dc85-11e4-9a59-0d695c83d11b.jpg)

これにarduino nanoを載せたいのですが、いわいしさんの机にあるようなarduinoのコネクタピンはどこにあるでしょうか？
![2015-04-06 17 32 45](https://cloud.githubusercontent.com/assets/4690682/7002408/0cf33f46-dc85-11e4-92a7-a6b8b4c694da.jpg)

**Comment by iory** [comment]
掃除機の基盤の移植が終わりました．
今度はつかんだ判定もできるようになりました．

あとケースをＣＡＤで作って地下の装置で設定してきたので，
@m1a1k0oさんあとでよろしくお願いします．
![image](https://cloud.githubusercontent.com/assets/4690682/7022064/d42a0292-dd62-11e4-90ae-6b0621741701.png)

**Comment by m1a1k0o** [comment]
いま3Dプリンターで作成中です。
明日あたりには完成だと思います

**Comment by iory** [comment]
ありがとうございます。

**Comment by aginika** [comment]
@m1a1k0o ケースは完成したのでしょうか？

**Comment by m1a1k0o** [comment]
造形はできていると思われます．
ただ、サポート材を溶かす必要があるのでかまに入れないといけない思いますので明日にはできると思います．
早急に必要ならばかまに入れる操作をしていただけると素早くできるかもしれません．

そうでなければ自分が明日やります．

**Comment by wkentaro** [comment]
finished. so i close this.
