### ISSUE TITLE
angele-vector-sequence (... ) :fast を試す

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2014-semi#177]
`send *ri* :angle-vector-sequence (list av0 av1 av2) :fast`
とすると最速で動くはずです．あまり早すぎると脱臼したみたいになるのでいい感じにしなければいけないですが，これで動かして，まずは動作自体を最速で動くようにしましょう

もし脱臼するなら
`send *ri* :angle-vector-sequnce ... :fast (*ri* . controller-type) 0.1 :scale 5`
とかしてみましょう．

**Comment by wkentaro** [comment]
we use this in #209
