### ISSUE TITLE
baxter moveitをeusから動けるようにする

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#178]

**Comment by aginika** [comment]
します。

**Comment by k-okada** [comment]
https://github.com/start-jsk/2014-semi/issues/91#issuecomment-77506080
のあたりの色認識を先にやるのがいい気がします．
まずはスピードを上げていくところが重要で，どこまでできるか見極めて，
で，それができたら，動作や，認識の精度をあげていくというのがいいともいます．
motionplanningの人は軌道ができたら，OKで時間の部分は余り考えていないので，
eusから動いた後に，スピードを早くしようとすると，こんどはmoveit開発になっていく
とおもいます．なので，出来る事を先にやって，おわったら，これをやるのが良さそうです．

**Comment by aginika** [comment]
了解です。
そうします。

**Comment by k-okada** [comment]
closeはしなくていいです

**Comment by aginika** [comment]
IK fastを使うために必要になるかもしれないです・・・

**Comment by wkentaro** [comment]
一旦closeでいいでしょうか。

**Comment by aginika** [comment]
いまのところ必要なさそうです。
