### ISSUE TITLE
color_histogram_matcherで彩度の低い位置の色情報を除外して判別

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#184]
>
白色がヒストグラムにはいっているかな？入っていないかな？入れないようにしないとかなり引っ張られると思います．
この画像だったら，まずはhsvでsが小さいもの（白黒）の部分はぬいて，http://en.wikipedia.org/wiki/HSL_and_HSV
でいうと外側の部分のドーナッツ部分で比較する必要が有ります．
>
ということで，
１）適当な画像を作る．国旗などで白黒がないもの．http://ja.wikipedia.org/wiki/%E5%9B%BD%E6%97%97%E3%81%AE%E4%B8%80%E8%A6%A7
アゼルバイジャン，アルメニア，アルバニア，ウクライナ，エクアドル，カメルーン，ガーナ
あたりで認識できるか確認
>
２）　白黒を（自動で）抜いて認識できるか．つまり新は除外してドーナッツ部分だけでヒストグラムをつくっているか確認．ドイツと南オセチアの類似度が高く出ればOKか．
>
かな．

**Comment by wkentaro** [comment]
#155

**Comment by wkentaro** [comment]
>
１）適当な画像を作る．国旗などで白黒がないもの．http://ja.wikipedia.org/wiki/%E5%9B%BD%E6%97%97%E3%81%AE%E4%B8%80%E8%A6%A7
アゼルバイジャン，アルメニア，アルバニア，ウクライナ，エクアドル，カメルーン，ガーナ
あたりで認識できるか確認

次にテストができるようにしたいと思います。

**Comment by wkentaro** [comment]
国旗でcolor_histogram_matcherのテストをしてみましたが、あまりに精度が低いので、何かおかしいかもしれません。

気になる点
* 255だとヒストグラムに反映されない

**Comment by wkentaro** [comment]
直りました。
color_histogram_matcher.pyがリクエストの物体配列と異なる順番で確率を返していたのが問題でした。
https://github.com/start-jsk/2014-semi/commit/b3da22fc0969aecb73bee25b816301b8a66a2785

**Comment by wkentaro** [comment]
Pythonの辞書型は順序を保持しない(キーのアルファベット順になる)ので気をつけてください。 @iory 
ちなみに順序を保持したい場合はcollections.OrderedDictがあります。

**Comment by garaemon** [comment]
参考までに、jsk_perception/ColorHistogramLabelMatchを使うとこんな感じになります

![screenshot from 2015-03-29 18 27 15](https://cloud.githubusercontent.com/assets/40454/6884894/731511fe-d641-11e4-95da-08707e99cb00.png)

**Comment by wkentaro** [comment]
棚の物体を手のカメラで取りに行くときなどの位置推定にかなり有効そうですね。

jsk_perception/ColorHistogramLabelMatchは色(red/green/blue)のどれかで使うという使い方ですか？
たとえば赤だけの画像とヒストグラムで
/input:=/rgb_decomposer/output/red
/input/reference:=/single_channel_histogram_red/output

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/807

サンプルではhueを使っていますが、基本的には1チャンネルの画像のみを使う用に書いていますね。

また、同じ画像無いの一部の領域をリファレンスに、それに似たところを探す、と言うのをモチベーションにしているので分類となると少し違ってきますね。

**Comment by wkentaro** [comment]
了解です。ありがとうございます。


2015-03-30 1:40 GMT+09:00 Ryohei Ueda <notifications@github.com>:

> jsk-ros-pkg/jsk_recognition#807
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/807>
>
> サンプルではhueを使っていますが、基本的には1チャンネルの画像のみを使う用に書いていますね。
>
> また、同じ画像無いの一部の領域をリファレンスに、それに似たところを探す、と言うのをモチベーションにしているので分類となると少し違ってきますね。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/184#issuecomment-87438817>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
何がおかしいのかわかっていませんが、ColorHistogramMatcherの精度は今2/16でランダムと同じような精度です。
https://github.com/wkentaro/2014-semi/blob/test-color-histogram/jsk_2014_picking_challenge/data/test_result/test_lab_color_histogram_matching_result.csv

**Comment by iory** [comment]
![dendro](https://cloud.githubusercontent.com/assets/4690682/7178819/bb49ea88-e46c-11e4-93bb-cbf895b7b70c.png)

ちょっと見づらいですが、クラスタリングしてみた結果まあまあ分類できているかと思うので、
これで精度測ってみます。

**Comment by iory** [comment]
テストデータからカラーヒストグラムで正しく分類できるかを
https://github.com/iory/2014-semi/blob/test-color-histogram/jsk_2014_picking_challenge/test/color_classification.py
で調べた結果、32.8%の精度でした。
間違えている結果もjoke本（赤い）のをindex_cards(赤い）と間違えたなど、似ているものなので、組み合わせによっては信頼度が高そうです。

**Comment by k-okada** [comment]
ランダムに3個選んで、識別すると認識率はどれぐらいかな？

--
◉ Kei Okada

2015/04/30 19:51、ioryz <notifications@github.com> のメッセージ:

**Comment by iory** [comment]
物体に対してとった画像数が均一でないですが、
３個を選んで色だけでどの物体か判定した時に50％以上で判断できた場合の割合を全パターンで試した結果90％でした。
https://github.com/iory/2014-semi/blob/test-color-histogram/jsk_2014_picking_challenge/test/color_classification.py

**Comment by iory** [comment]
ちなみにテスト画像は以下を使っています。
https://github.com/start-jsk/2014-semi/issues/279

3種の組み合わせで100％あったという数を数えたら24.2%でした。
組み合わせによっては色情報だけでも簡単に判断できそうです。

**Comment by wkentaro** [comment]
bof_object_matcherと同じ感じでnodeとlaunch作ってもらえますか？
@iory

2015年5月2日土曜日、ioryz<notifications@github.com>さんは書きました:

> ちなみにテスト画像は以下を使っています。
> #279 <https://github.com/start-jsk/2014-semi/issues/279>
>
> 3種の組み合わせで100％あったという数を数えたら24.2%でした。
> 組み合わせによっては色情報だけでも簡単に判断できそうです。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/184#issuecomment-98271920>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by iory** [comment]
了解です

**Comment by iory** [comment]
PR送りました。
 https://github.com/start-jsk/2014-semi/pull/417

**Comment by wkentaro** [comment]
昨日か一昨日に集めた画像群みたいなのありますか？
