### ISSUE TITLE
Useful setup of your shell using jsk_tools (for baxter user)

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#191]
### source jsk_tools shell settings when source /opr/ros/indigo/setup.XXX
Use latest jsk_tools, which is included in jsk_common:
```sh
cd ~/catkin_ws/semi/src
wstool set jsk_common https://github.com/jsk-ros-pkg/jsk_common.git --git
wstool update jsk_common
cd ..
rosdep install -y -r --from-paths .
catkin build jsk_tools  # or catkin_make --only-pkg-with-deps jsk_tools
```
Restart shell by `exec bash` or `exec zsh`.
Now you can use `rossetip`, `rossetlocal` and `rossetmaster` by `source /opt/ros/indigo/setup.XXX`.
See https://github.com/jsk-ros-pkg/jsk_common/pull/845 for more information.

### Set baxter as default rosmaster
Add below to your `.bashrc` or `.zshrc`:
```sh
function my_rossetmaster() {
  local hostname=${1-"baxter.jsk.imi.i.u-tokyo.ac.jp"}
  local ros_port=${2-"11311"}
  rossetmaster $hostname $ros_port
}
alias rossetmaster='my_rossetmaster'
```
Restart shell by `exec bash` or `exec zsh`.
Now you can use `rossetmaster` to set ROS_MASTER_URI for baxter and `rosetmaster pr1040` for pr2.

**Comment by k-okada** [comment]
ok, I have release new versoin of jsk_tools, 1.0.66 and once that is
released (at least  tomorrow) , you do not have to use source
repository.

once this https://github.com/ros/rosdistro/pull/7760  is merged, then
ros build firm runs to generate deb file at
http://jenkins.ros.org/view/Hsrc/job/ros-indigo-jsk-tools_sourcedeb/
--
◉ Kei Okada
