### ISSUE TITLE
掃除機のon/offを手元で

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#199]
baxterの掃除機のつかめるかつかめないかのテストをするときに、
一人でも手元でスイッチをon/offできるように携帯やarduinoのbluetoothでスイッチングができたら良いのですが、そういったものはあるでしょうか？

**Comment by iory** [comment]
浅野さんからxbeeを借りれたので作ってみます

**Comment by wkentaro** [comment]
ターミナルでrostopic pubするのでは手間がかかるという事でしょうか？

2015年4月8日水曜日、ioryz<notifications@github.com>さんは書きました:

> 浅野さんからxbeeを借りれたので作ってみます
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/199#issuecomment-90911932>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by iory** [comment]
そうです
リモコン的なものがあるといろいろ便利だと思います。
どっちにしろ時間がかからないと思うので、さっと試してみます。

**Comment by wkentaro** [comment]
なるほど。了解です。

2015年4月8日水曜日、ioryz<notifications@github.com>さんは書きました:

> そうです
> リモコン的なものがあるといろいろ便利だと思います。
> どっちにしろ時間がかからないと思うので、さっと試してみます。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/199#issuecomment-90914620>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
これは一旦closeでいい？

**Comment by iory** [comment]
closeで
