### ISSUE TITLE
最速で何分かかるかのテストを行う

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#209]

**Comment by iory** [comment]
作りかけです。
https://github.com/iory/2014-semi/blob/move-to-bin-motion/jsk_2014_picking_challenge/test/measure-fastest-time.l

**Comment by wkentaro** [comment]
* move to target bin
* pick object
* put order bin
で4:30でした。

**Comment by k-okada** [comment]
https://twitter.com/baxter_jsk
```
(ros::roseus "tweet_example")
(ros::advertise "tweet" std_msgs::string 1)
(setq start-time (ros::time-now))
(unix:sleep 3)
(setq finish-time (ros::time-now))
(setq elapsed-time (ros::time- finish-time start-time))
(setq elapsed-msg (instance std_msgs::string :init))
(send elapsed-msg :data (format nil "It takes ~d min ~d sec" (/ (send elapsed-time :sec) 60) (mod (send elapsed-time :sec) 60)))
(ros::ros-info (send elapsed-msg :data))
(ros::publish "tweet" elapsed-msg)
(ros::spin-once)
(ros::exit 1)
```

こんなかんじでしょうか．

**Comment by k-okada** [comment]
１）　IKを解くだけ
２）　吸引してみる（適当に手の位置をきめる）で何％でつかめるか
３）　手探りだけで吸引してみる（つかめていなかったら，手先の位置を替える）で何％つかめるか
４）　大体の物体の位置を知った上で吸引してみると何％つかめるか
５）　認識いれると何分余計にかかるか，成功率は何％上がるか．この時は思った思ったものがつかめなかったら地面に落とす
６）　認識入れて思ったものがつかめなかったら棚に戻すと何％つかめるか
７）　ちゃんとかごに入れるところまでやる


ルールで確認しておきたいこと
- 一回掴んだものは同じbinに戻さないといけないか？戻さなくていいと，結構うれしい
- MAXで何点になるのか．

**Comment by iory** [comment]
pick-objectの5パターンを試して、Eの棚の計測をしてみたら1分4秒かかりました。
これだと全部の棚をすると12分かかるので、もうちょっと早くできるところを改善していく必要がありそうです。
今はpick-objectでつかめるまで元の位置（棚の前）まで戻っているのでまずはそこをなくしていこうかと思います。

**Comment by aginika** [comment]
明日12物品ノーチエックで時間計測します。

**Comment by wkentaro** [comment]
Alright. I will do it tomorrow.

**Comment by wkentaro** [comment]
左手しか今は使えませんが、明日はこれ
```lisp
(test :use-arm (list :larm) :bins (list :a :b :d :e :g :h :j :k))
```
で計測できると思います。
https://github.com/start-jsk/2014-semi/pull/273

**Comment by aginika** [comment]
@iory くんのおかげで、２つの掃除機を取り合えず動かせるようになりました。
明日こそ物品１２個の通しと動作の無駄を省くのもやってしまえたら嬉しいです。

**Comment by wkentaro** [comment]
画像での認識なしで掴んで order bin に入れるというのをやったところ6:30くらいでした。

**Comment by aginika** [comment]
> ５）　認識いれると何分余計にかかるか，成功率は何％上がるか．この時は思った思ったものがつかめなかたら地面に落とす
> ６）　認識入れて思ったものがつかめなかったら棚に戻すと何％つかめるか
> ７）　ちゃんとかごに入れるところまでやる

これをまだやってませんが、どうしましょうか？

**Comment by wkentaro** [comment]
イシュー分けました: https://github.com/start-jsk/2014-semi/issues/313
* pick→verifyを行う際の成功率(x / 12)とスコアと時間
* pick→verify→returnを行う際の成功率とスコアと時間
* pick→verify→return/place→pick→verify→placeを行う際の成功率とスコアと時間
5-7はということであっていますか。

**Comment by wkentaro** [comment]
今日やったpick→placeは全部single-binでしたが、
* 成功率: 6/12
* スコア: 60点
* 時間: 6:30

**Comment by k-okada** [comment]
MAXの時間は何分だっけ？

2015年5月1日金曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> 今日やったpick→placeは全部single-binでしたが、
>
>    - 成功率: 6/12
>    - スコア: 60点
>    - 時間: 6:30
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/209#issuecomment-97870207>.
>


-- 
--
◉ Kei Okada

**Comment by aginika** [comment]
20分間の試合だったと思います。

**Comment by wkentaro** [comment]
20分ですね。
