### ISSUE TITLE
左手の吸引ハンド, 予備の作成

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#215]

**Comment by aginika** [comment]
左手のハンドはつきました。

**Comment by wkentaro** [comment]
左手の掃除機と予備の掃除機を買ってきました。
（合計で今は3個有ります）

**Comment by aginika** [comment]
close可能でしょうか？

**Comment by wkentaro** [comment]
closeします。
基板については -> https://github.com/start-jsk/2014-semi/issues/236
