### ISSUE TITLE
ルール確認

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#216]
from http://amazonpickingchallenge.org/details.shtml

1. 制限時間は20分
1. 途中でやめてもいい。（人が宣言できる）他は全て自動化する必要がある。
1. 本番の1時間前からセットアップ。10分前から棚の中が見られる。2分前にjsonが渡される。
1. 商品の種類は25種類
1. shelfの棚の数は12(A-L)
1. 同じ商品が複数入っていることもある
1. 商品の姿勢はランダム（本もランダムに変わった模様）
1. 一つの棚から取ってくる商品はひとつだけ（つまり全部とるとしても棚の数が最大なので12個）
1. 間違った商品をとっても棚に戻せばいい。（同じ棚かは不明でメーリスで確認中 [here](http://www.freelists.org/post/amazonpickingchallenge/Rule-about-placing-back-the-wrong-item-on-the-shelf)）
1. 棚の中に入っている商品数で点数は異なる(1個: +10, 2個: +15, 3個以上: +20)
1. single-item bin, double-item bin, multi-item bin それぞれ最低2個はある。
1. 商品によってもボーナス点数がある。 see [here](http://amazonpickingchallenge.org/meta_items.jpg)

**Comment by wkentaro** [comment]
9.について返信が有りました。同じ棚に戻す必要があるそうです。
http://www.freelists.org/post/amazonpickingchallenge/Rule-about-placing-back-the-wrong-item-on-the-shelf,1

**Comment by aginika** [comment]
準備時間は４時間２０分ではないのでしょうか？
```
Each team will have 4 hours and 20 minutes to set up their system at
the testing workspace, 20 minutes to perform their scored trial, and
20 minutes to clear out of their testing workspace ( a total of 5
hours). You will have a shelf in your workspace the entire time, which
you can use for testing and calibration. Based on the challenge
schedule you may have time to set up earlier in your workspace, or
unpack your system in another location.
```

**Comment by wkentaro** [comment]
HPには以下のように書いてあったので1時間だと思ったのですが、4時間20分というのはメールに書いてありましたか？

>
**One hour prior to the start of an attempt the team will be given access to setup their system at the contest shelf**. Ten minutes prior to the start of the attempt the organizers will obscure the contestants' view of the shelf and randomize the items on the shelf. Then, (2 minutes prior to the start of the attempt) the organizers will give the team a JSON file containing the shelf layout and work order as described in the Interface. The team will then be allowed to upload the data to their system, after which the shelf will be unveiled and the attempt started. Items that appear in the work order can be picked in any order.

**Comment by aginika** [comment]
上にあったものはメールの内容です。

**Comment by aginika** [comment]
全く複雑ではないので、器にする必要はなさそうですが、
本番のネットワーク環境ってどこかに記されていましたでしょうか？

**Comment by garaemon** [comment]
いざという時のためにハブはもちろんだけど、NATできるwifiを持っていくと良いと思います。
多めに買ったものがあるはずです

2015年4月29日水曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 全く複雑ではないので、器にする必要はなさそうですが、
> 本番のネットワーク環境ってどこかに記されていましたでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/216#issuecomment-97428850>.
>


-- 
✉︎ from iPhone

**Comment by aginika** [comment]
@garaemon 
ありがとうございます。明日あたりに確保できる分を確認して、確保しておきます。

**Comment by aginika** [comment]
Orderbinはいかなるところにおいてもいいみたいです。

http://www.freelists.org/post/amazonpickingchallenge/Order-bin,1

**Comment by aginika** [comment]
いまさらですが、25 x 53 x 35 のorderbinのようです。
