### ISSUE TITLE
exceed threshold error when send :angle-vector-sequence

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#217]
How can I avoid this error?

Should I calculate the speed by my own?

**Comment by k-okada** [comment]
Need to find nice scale parameters?
@aginika

**Comment by aginika** [comment]
@wkentaro When you send the same trajectory more slowly, does the error disappear?
If so, one solution is to change the scale paramter. Here , https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-interface.l#L233 .

This paremeter will affect to this time calculating function https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L231

**Comment by wkentaro** [comment]
yeah, by changing the scale the error disappears.
I mean I'd like to set the scale automatically.
Is that difficult?

More specifically, Baxter sets fold pose before move arm to target bin.
When moving to fold-pose.the start angle vector is different in different
situations.

2015年4月21日火曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> @wkentaro <https://github.com/wkentaro> When you send the same trajectory
> more slowly, does the error disappear?
> If so, one solution is to change the scale paramter. Here ,
> https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-interface.l#L233
> .
>
> This paremeter will affect to this time calculating function
> https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L231
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/217#issuecomment-94791825>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
we need to find better scaling parameter, change them automatically may
difficult.
or find parameter that works for 90% and create detector to fail the motion
and resend the angle-vector with slower parameter.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Okay, I will set the param after the tests.
