### ISSUE TITLE
棚にある物体をランダムにつかめるまで掴もうとする

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#219]
@iory 
obejct-picking-server.l
をつかめるまでつかむプログラムにしてください。

arm-motion.lで、掴みに行くプログラムと、fold-poseになるプログラムは分けたほうがいいと思います。（参考https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/arm-motion.l#L93)

**Comment by aginika** [comment]
arm-motion.l は下の画像で言うどの部分なのでしょうか？

![picking challenge](https://cloud.githubusercontent.com/assets/4310419/6282442/703d4a5a-b918-11e4-9a5f-cca8813132f2.png)

**Comment by iory** [comment]
arm-motion.lは基本的にbaxterを動かす動作を関数化したものです。

**Comment by iory** [comment]
@k-okada euslispのrandomへシードを与えるにはどうすればいいでしょうか？

**Comment by wkentaro** [comment]
これが割と時間かかる場合には、手のカメラで物体の位置のあたりをつける必要がでてくると思います。

手のカメラはいま吸引ハンドがかぶっていますが、連結している先の方のパーツを90度回転させてつけるようにすればかぶらないようになると思うので（かぶっていてもよく見えるので）使えそうですね。

**Comment by aginika** [comment]
@iory  *random-state* に適当な値をsetqすると違う値がとれます。
```
$ *random-state*
#i(123456 789012)
```
時間でもとって入れればいいと思います。ただ２つのあたいをとるベクトルなので注意してください。

**Comment by iory** [comment]
ありがとうございます。
2015/04/23 22:02 "Yuto Inagaki" <notifications@github.com>:

**Comment by k-okada** [comment]
でおくれました．eusのランダムは以下になります．
http://euslisp.github.io/jskeus/jmanual-node185.html


--
◉ Kei Okada

**Comment by iory** [comment]
gaussian-randomとかもあるんですね。
ありがとうございます。

2015-04-27 14:03 GMT+09:00 Kei Okada <notifications@github.com>:
