### ISSUE TITLE
final_video.launchを実行するとエラーがでる。

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#222]

**Comment by aginika** [comment]
color_histogram_matcher.launchがないようですが、最新では何を使うとよいでしょうか？
```
$ roslaunch jsk_2014_picking_challenge final_video.launch 
... logging to /home/baxter/.ros/log/5fe53f4a-e8ee-11e4-ae64-b8ca3ab5d80e/roslaunch-mouro-8852.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

while processing /home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/launch/color_histogram_matcher.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/launch/color_histogram_matcher.launch'
```

**Comment by wkentaro** [comment]
更新できておらず申し訳ないです。
color_histogram_matcher.launchをbof_object_matcher.launchにすれば動くはずです。
sift_matcher.launchも必要ないです。

色はいままだ @iory にテストしてもらっていて、
lab_color_histogram_matcher.lanch と
rgb_color_histogram_matcher.launch
に分かれています。

2015年4月22日水曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> color_histogram_matcher.launchがないようですが、最新では何を使うとよいでしょうか？
>
> $ roslaunch jsk_2014_picking_challenge final_video.launch
> ... logging to /home/baxter/.ros/log/5fe53f4a-e8ee-11e4-ae64-b8ca3ab5d80e/roslaunch-mouro-8852.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
>
> while processing /home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/launch/color_histogram_matcher.launch:
> Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/baxter/semi/src/2014-semi/jsk_2014_picking_challenge/launch/color_histogram_matcher.launch'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/222#issuecomment-95208743>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
PR送りました。
challenge.launch
という名前に変えました。
https://github.com/start-jsk/2014-semi/pull/223

**Comment by aginika** [comment]
@wkentaro ありがとうございます。
