### ISSUE TITLE
掃除機基板の複製

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#236]
予備をつくらないと行けないと思うのですが、
今は手作業でハンダ付けしているのですが、回路図を作って
どこかに発注できるでしょうか？

**Comment by k-okada** [comment]
p版に発注できます．しましょう．

--
◉ Kei Okada


2015-04-23 21:29 GMT+09:00 ioryz <notifications@github.com>:

**Comment by iory** [comment]
なるほど、発注の予備は何個くらい頼めばいいでしょうか？

**Comment by aginika** [comment]
決まりましたでしょうか？
決まってなかったら適当ですが、４つぐらいでいいのでしょうか？ @k-okada

**Comment by k-okada** [comment]
そうですね．いい感じに無理しない範囲で小さい感じにしましょう．

--
◉ Kei Okada


2015-04-24 16:34 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by iory** [comment]
了解です。

**Comment by aginika** [comment]
手先ゴムも複数準備できました。基盤ができれば両手で吸い込みができるようになります。

**Comment by aginika** [comment]
tmpな回路を作ってもらいました。
発注の方も進めていただけると幸いです。

**Comment by wkentaro** [comment]
最終的には自作するのではなく、発注するという方針でいきます。
回路図などは @iory お願いします。

**Comment by aginika** [comment]
P版に発注できましたか？

**Comment by wkentaro** [comment]
発注には時間がかかると思うので、早めにお願いします。

**Comment by iory** [comment]
手作りですることになりました
