### ISSUE TITLE
ノード構成

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#237]
https://github.com/start-jsk/2014-semi/pull/233

ノードの構成ですが、以下のようで大丈夫でしょうか。 @k-okada 

グローバルパラメータ
------------------------------
* /target
    * target binの名前
    * a, b, c, .., l
* /left\_limb/state, /righ\_limb/state:
    * アームごとの状態
    * move\_to\_target\_bin
    * pick\_object
    * return\_object
    * move\_for\_verification
    * place\_object
    * verify\_object

ノード構成
---------------
* **bin_contents** (publisher)
    * jsonを読んで、棚に入っている商品についてpublishする (~output)
* **work_order** (publisher)
    * jsonを読んで、取る順番にソートしてpublishする (~output)
* **master** (client)
    * /stateによって/targetに対して動作を行う
* **move_to_target_bin** (actionlib server)
    * target binの前に腕を移動させる
* **pick_object** (actionlib server)
    * target binの前にいることを前提にしてものを取りに行く
* **return_object** (actionlib server)
    * target binの前にいることを前提にしてものを戻しに行く
* **move_for_verification** (actionlib server)
    * 物体の判別に適した姿勢を取る
* **verify_object** (actionlib server)
    * 物体が正しいかを判別する
* **place_object** (actionlib server)
    * Place object on order bin

**Comment by wkentaro** [comment]
上のは無しの方向で。
* 動作は全て一つのノードが行うことにして、stateはparameter_serverが管理することにします。(main.lの中でmove_to_target_bin, move_for_verificationなどを呼ぶ)
* main.lはstateを見て動作を行うのみ。

**Comment by wkentaro** [comment]
robotのモーションをいちいちactionlibにするのは手間がかかるので、robot-main.lという一つのプログラムから呼ぶという仕様にしましょう。
もしeusのノードが死んだ時のために、パラメータサーバが記憶の部分を受け持って、respawnで生き返った時にまた前のステートからやり直すようにしようと思います。

https://github.com/start-jsk/2014-semi/pull/238
PRを送りました。

今までのmain.lはrobot-test.lになりました。
master.pyと同じ機能はrobot-main.lとパラメータサーバで行うことにします。

**Comment by wkentaro** [comment]
システム図を作ったら載せます。

**Comment by aginika** [comment]
了解です。
今日中に動かせるようになって、今週中に動作の高速まで行えたらうれしいです。

robot-main.lが完成したら、僕は両腕で動かせるように変えたいと思います。
まだ決めていないですが、smachの形にするかもしれません。

**Comment by wkentaro** [comment]
![img_3705](https://cloud.githubusercontent.com/assets/4310419/7314836/4521e1c0-eaa3-11e4-9466-57785d62b153.JPG)

**Comment by wkentaro** [comment]
- [ ] robot-main.l @wkentaro
  - [x] move-to-target-bin (function) @wkentaro
  - [x] move-for-verification (function) @wkentaro
  - [ ] pick-object (function) @iory
  - [ ] return-object (function) @iory
  - [x] place-object (function) @wkentaro
  - [ ] verify-object (function) @wkentaro
- [ ] work_order.py @wkentaro 
- [ ] bin_contens.py @wkentaro
- [ ] bof_object_matcher.py @wkentaro
- [ ] color_histogram_matcher.py @iory

@iory work_order.pyとbin_contents.pyはrobot-main.lと同じ人がやったほうがいい気がするから俺がやるわ。
pick-objectとreturn-objectを早急にお願いします。

**Comment by aginika** [comment]
#243 によって上のcheckboxはどう更新されますか？

**Comment by wkentaro** [comment]
I updated. 
`robot-main.l` is almost done. I need to create `verify-object` function.

**Comment by aginika** [comment]
了解です。ありがとうございます。

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/253
https://github.com/start-jsk/2014-semi/pull/252
https://github.com/start-jsk/2014-semi/pull/260

bin_contents.py, work_order.py, robot-main内のget-work-orderを作りました。

**Comment by aginika** [comment]
上記のチェックリストは変更されますでしょうか？
```
bof_object_matcher.py
 color_histogram_matcher.py
 verify-object
```

**Comment by aginika** [comment]
@wkentaro ping

**Comment by wkentaro** [comment]
更新しました。
* color_histogram_matcher.py
が残っていると思います。

**Comment by wkentaro** [comment]
更新しました。

* color_histogram_matcher.py

が追加されました。

**Comment by wkentaro** [comment]
![2015-05-07 14 07 54](https://cloud.githubusercontent.com/assets/4310419/7508887/985c81ea-f4c3-11e4-913e-abf1caded439.jpg)

**Comment by wkentaro** [comment]
ノード構成は確定したと思うので、closeします。
