### ISSUE TITLE
本番に持っていくもの

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#239]
- [x] 掃除機 * 3
- [x] 吸引ハンド * 3
- [x] 吸引ハンド先ゴム * 3
- [ ] コンバータ * 3
- [x] 掃除機基盤 * 4
- [x] Kinect2 * 2
- [x] Kinect2アタッチメント * 2
- [x] baxterサポートPC(要相談)
- [x] PCモニター
- [x] 掃除機格納BOX * 2
- [x] テープ(吸引ハンド固定のため)
- [x] soundプレーヤー
- [ ] ~~掃除機を載せる台~~
- [x] wifi with nat
- [x] ハブ
- [x] 養生テープ
- [x] ThinkPad Keyboard
- [ ] ノートPC
- [x]  バッファロ WZR-1750DHP2/N
- [x] 物品
- [x] くくりつける紐/ダイニーマ
- [x] マイナスドライバー/工具類
- [ ] 密閉テープ
- [ ] ねじりっこ
- [ ] トルクスレンチ
- [ ] 結束タイ
- [x] 高さ調整のためのダンボール/テーブルのようなもの
- [x] メジャー
- [x] 掃除機の箱
- [ ] 掃除機の箱の中の梱包材
- [x] 黒い箱
- [x] ダイニーマ
- [ ] 掃除機を持っていくための袋
- [x] 吸盤を傷めないための箱 (baxter tool_box)
- [x] baxter tool_box
- [x] ハサミ
- [x] マジックテープ
- [x] LANケーブル
- [x] カッター
- [ ] 電源タップ
- [x] カメラ（念のため?）
- [ ] 半田ごて/ 半田

**Comment by aginika** [comment]
音をならしていいかは聞いてみます。

**Comment by wkentaro** [comment]
mouroはusbが一度抜けると再起動する必要があるので、できれば別のPC(5月頭にB4に届く奴など)を使いたいですね。

**Comment by aginika** [comment]
そうですね。故障したら怖いので予備あると嬉しいですが、その余裕は無さそうですね。

ハブとwifiを追加しました

**Comment by aginika** [comment]
PC用のモニターは現地で借りれましたっけ？

**Comment by k-okada** [comment]
それ考えるとノートが安心かな

--
◉ Kei Okada

2015/04/30 0:37、Yuto Inagaki <notifications@github.com> のメッセージ:

**Comment by aginika** [comment]
現状PCとして以下のUSBポートが必要です。
- Kinect2
- 掃除機コントローラ右手
- 掃除機コントローラ左手

PCの場合
- キーボード

予備
- スピーカー

**Comment by aginika** [comment]
ノートPCもあまりがないか探して見ます。
ただ、点群処理やmoveitも動かすかもしれないので、
そこそこハイスペックが必要かと思われます。

**Comment by garaemon** [comment]
kinect2やばいですね

動作確認必須です

◉  ryohei

2015-04-30 1:30 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by aginika** [comment]
ノートPCについてですが、@furushchev にmsiのハイスペックなPCを一台貸してもらいました。
14.04しか動かないみたいなので、ちょうどよさそうですが、キーボードはUSBで刺したほうがいいかもしれません。
一応このPCはとっておきます。

**Comment by iory** [comment]
@garaemon さんからいただいたバッファロの無線ルータの設定しました。

**Comment by wkentaro** [comment]
無線の中継機として使う方法の手順を書いておいてもらえますか？

**Comment by aginika** [comment]
ノートPCでkinect2の点群が読めることを確認しました。OpenCLの導入もできたため3.8hzほどです。

**Comment by aginika** [comment]
セットアップ時間に物品を持っていけば置いて練習することが出来るみたいです

**Comment by wkentaro** [comment]
先に手のカメラで棚の中の写真を撮っておけば、棚の背景差分か色特徴も使えそうですね。

**Comment by aginika** [comment]
グリッパを外すためのマイナスドライバーを追加しました。

**Comment by aginika** [comment]
ヘッドのネジ、Kinectのねじのためのトルクスレンチを追加しました。

**Comment by wkentaro** [comment]
名前忘れましたが、吸盤をノズルに付ける時に締めて固定するやつも必要ですね。
名前分かりますか？

2015年5月14日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> ヘッドのネジ、Kinectのねじのためのトルクスレンチを追加しました。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/239#issuecomment-101705281>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
結束タイ？

**Comment by wkentaro** [comment]
それです。

2015年5月14日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 結束タイ？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/239#issuecomment-101721000>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
加えました。
@iory くんと @m1a1k0o もできるだけ指摘してくれると嬉しいです。

**Comment by wkentaro** [comment]
ありがとうございます。

2015年5月14日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 加えました。
> @iory <https://github.com/iory> くんと @m1a1k0o <https://github.com/m1a1k0o>
> もできるだけ指摘してくれると嬉しいです。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/239#issuecomment-101721874>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
* 掃除機の箱
* 掃除機の箱の中の梱包材
* 黒い箱
* ダイニーマ
* 掃除機を持っていくための袋

![2015-05-18 21 11 05](https://cloud.githubusercontent.com/assets/4310419/7680565/c9919d58-fda2-11e4-8dc0-3fd4c9acd46f.jpg)

**Comment by aginika** [comment]
@m1a1k0o 後で他に必要なものがあったら加えておいてください。
明日、買い物とある程度の資材集めを行いたいと思います。

**Comment by wkentaro** [comment]
昼ごろからいくつもりしておけばいいでしょうか。
16:50-18:30は授業があります。

**Comment by aginika** [comment]
買い物についてでしょうか？

**Comment by m1a1k0o** [comment]
・幅が厚めの結束帯(靴下型の吸盤でよければ必要ないかもしれませんが)
・ビニルテープ(吸盤の固定や掃除機との固定に必要)(固定の際にぐるぐる巻きにすると思うので多めにあった方がよさそう)

**Comment by aginika** [comment]
一応以下のものを買おうと思います。

- 密閉テープ
- ねじりっこ
- トルクスレンチ
- 結束タイ

他に必要なものはあったりしますか？@iory くん

**Comment by aginika** [comment]
買って来ました。
- カルビな

も買いました

**Comment by wkentaro** [comment]
渋谷寄るので、変圧器探してきていいでしょうか？ @aginika

2015年5月21日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 買って来ました。
>
>    - カルビな
>
> も買いました
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/239#issuecomment-104189203>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
いいですけど、
この前買って研究室にあるかもしれないと@k-okada先生が言ってました。見つけられませんでしたが。

**Comment by wkentaro** [comment]
了解です。
今日探して無かったら買います。

@k-okada どの辺りを探せばいいでしょうか。


2015年5月23日土曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> いいですけど、
> この前買って研究室にあるかもしれないと@k-okada <https://github.com/k-okada>
> 先生が言ってました。見つけられませんでしたが。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/239#issuecomment-104822431>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
変圧器を覗いて問題なさそうなので、closeします。
