### ISSUE TITLE
吸引ハンド手先が棚の縁にひっかかる

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#245]
- 手を引くときに低すぎて引っかかってます。
- その縁で手先のゴム部分がとれてしまいます。

**Comment by wkentaro** [comment]
@iory target-pick-regionの位置調整をお願いします。

https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/motion/move-to-target-bin.l#L7
で始めるときの準備の段階でそれぞれの棚の天井からの距離を合わせるようにしたいですが、できればカメラで自動で調整できるようにもしたいですね。

**Comment by iory** [comment]
調整しました。
多分棚の位置によってあたる範囲が変わってくるのでpick-regionは今後も調整が必要になると思います。
https://github.com/start-jsk/2014-semi/pull/262

前にpoint cloudから棚の位置をとってそれとeusのモデルを合わせることができると聞いたのですが、
どうやってやればいいでしょうか？

**Comment by aginika** [comment]
@iory 了解です。ありがとうございます。

ひとつの方法は、
棚の点群モデルを入力点群にICPでフィットさせて位置調整をして
その結果をeusに反映させるとかでしょうか？

**Comment by k-okada** [comment]
2015-04-27 1:03 GMT+09:00 Yuto Inagaki <notifications@github.com>:

> 棚の点群モデルを入力点群にICPでフィットさせて位置調整をして
> その結果をeusに反映させるとかでしょうか？
>

これは稲垣くんの宿題だった気がしますね．植田くんによるとエッジの比較で出来るという話でした．やってみましょう．

--
◉ Kei Okada

**Comment by wkentaro** [comment]
その場合は、kinectの向きは今のままでも大丈夫なのでしょうか。（やってみないとわからないかもしれませんが。）

2015-04-27 12:25 GMT+09:00 Kei Okada <notifications@github.com>:

> 2015-04-27 1:03 GMT+09:00 Yuto Inagaki <notifications@github.com>:
>
> > 棚の点群モデルを入力点群にICPでフィットさせて位置調整をして
> > その結果をeusに反映させるとかでしょうか？
> >
>
> これは稲垣くんの宿題だった気がしますね．植田くんによるとエッジの比較で出来るという話でした．やってみましょう．
>
> --
> ◉ Kei Okada
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/245#issuecomment-96487057>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
@wkentaro どのような点を気にされているのでしょうか？

**Comment by wkentaro** [comment]
位置調節は棚が全部見えていなくても大丈夫ですか？

2015年4月28日火曜日、Yuto Inagaki<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

> @wkentaro <https://github.com/wkentaro> どのような点を気にされているのでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/245#issuecomment-96694166>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
なるほど、そう意味ですか。
確かにやってみるのが早いですが、輪講の時に準備した時にはそこそこいい結果だったと思います。

eus棚モデルの位置合わせは明日やりますが、
今全体のプログラムで棚の位置を使ってIKを解いてるところはあるのでしょうか？
各binにジョイントのようなものは定義されている感じでしょうか？

**Comment by wkentaro** [comment]
Here is the implementation of target region of "move_to_target_bin".
https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/motion/move-to-target-bin.l#L7

And [here](https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/motion/move-to-target-bin.l#L37)
It solves IK for the region.

**Comment by wkentaro** [comment]
これは完了でいいですか？　@aginika

**Comment by aginika** [comment]
一旦完了にします。
位置合わせはrvizのpodを見ながらロボットを動かして合わせることで済みそうです。
