### ISSUE TITLE
eusモデルに吸引はんどがないです。

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#247]
end effectorの先は、吸引ハンドの先にした方がよいでしょうか？
でもIK解けにくくなったりというのはあったりするのでしょうか？

**Comment by k-okada** [comment]
end-coordsは吸引ハンドのさきにしたほうがいいですね．
プログラムはだいぶ変わるかもしれないけど．そうすればハンドの形状向きをかえても
同じプログラムで使えるので．
もしそれでIKが解けなくなるなら，そもそもハンドの形状向きを見直しになります．

--
◉ Kei Okada


2015-04-25 21:38 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by aginika** [comment]
頑張ってやってみます。

**Comment by aginika** [comment]
end-coordsだけを変更するにはどうすればよろしいでしょうか？

**Comment by k-okada** [comment]
本当はbaxter.lを作る時のyamlを変えますが
今回はhttps://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/robot-init.l
で無理やり帰るのが正解だと思っています

--
◉ Kei Okada

2015/04/29 22:47、Yuto Inagaki <notifications@github.com> のメッセージ:

**Comment by aginika** [comment]
I will close this once, cause #308 will be merged.
