### ISSUE TITLE
Segmentation Fault when converting baxter_white_hand.urdf to baxter_white_hand.dae

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#257]
I am a newbie around model, so I am reading https://code.google.com/p/rtm-ros-robotics/wiki/model_conversion?ts=1374263141&updated=model_conversion#Collada_model_(.dae)_->_Euslisp_(.l)
to learn how to convert urdf to euslisp.l.

Below command failed. 
```
$ rosrun collada_urdf urdf_to_collada baxter_white_hand.urdf baxter_white_hand.dae
Segmentation fault (core dumped)
```

How can I convert?

**Comment by k-okada** [comment]
try using 12.04

--
◉ Kei Okada

**Comment by aginika** [comment]
I'm using

**Comment by k-okada** [comment]
so, the hand model is create in CAD software and that can export dae or
stl, look inside urdf file, may be they uses stl/dae for mesh model and use
assimp to convert them
or use gdb to debug urdf_to_collada, which I just teach software 2 lecture,
last week.

--
◉ Kei Okada

**Comment by k-okada** [comment]
@m1a1k0o , can you create dae file less thant 1M ?

**Comment by m1a1k0o** [comment]
I will try tomorrow.

**Comment by aginika** [comment]
I got file from @m1a1k0o and send PR with #294

**Comment by aginika** [comment]
@k-okada Could you tell me how can I generate baxter.l?
Is the below thing will be OK?
```
rosrun collada_urdf urdf_to_collada `rospack find baxter`/baxter.urdf baxter.dae 
rosrun euscollada collada2eus baxter.dae baxter.yaml baxter.l.$$.tmp; mv baxter.l.$$.tmp baxter.l
```

I just need to fix urdf_collada?

**Comment by k-okada** [comment]
need to use simplified mesh
https://github.com/RethinkRobotics/baxter_common/pull/48 or
https://github.com/rethink-rlinsalata/baxter_common/compare/RethinkRobotics:development...k_rob-simple_meshes

--
◉ Kei Okada

**Comment by k-okada** [comment]
I'll take care of this since this is not important nor urgent

**Comment by k-okada** [comment]
this is due to size of of cylinder model, fixed in hrere
https://github.com/k-okada/2014-semi/commit/a04f408790c51786c55380df9456eeda81dff7fe

**Comment by aginika** [comment]
Thanks a lot
