### ISSUE TITLE
２双掃除機のそれぞれにgripperのON/OFFを作成する

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#263]
掃除機を片方ずつ制御できるように、
arduinoとbaxter-interfaceのoverrideを作成する必要があります。

**Comment by iory** [comment]
https://github.com/iory/2014-semi/commit/d684cac1a17ee410866ce6409f03771becfa417d
https://github.com/iory/2014-semi/commit/413a59ee787644f258efcfd1c54072b5d26ec265
グリッパーの両手の掃除機を片方ずつ操作できるようにbaxter-interfaceを変更しました。
(load "package://jsk_2014_picking_challenge/euslisp/motion/control-vacuum-gripper.l")
してください。

今までは、
```
/on_off_gripper
```
にpublishしていましたが、今度からは
```
/on_off_gripper/limb/left
/on_off_gripper/limb/right
```
にpublishするようになりました。

**Comment by iory** [comment]
arduinoのudevの設定をはるようにinstall.shをbin以下に追加しました
https://github.com/iory/2014-semi/tree/double-on-off-gripper-263/jsk_2014_picking_challenge/bin

**Comment by aginika** [comment]
新しい方のケースのを方の作成をおねがいします。

**Comment by aginika** [comment]
また、以前熱くなって掃除機がだめになり冷やさないと動かないとの話をしてましたが、
- 今確実に数時間連続駆動が可能でしょうか？
- よくなった場合は何に気をつけるべきなのでしょうか？回路の置き方でしょうか？
- 保険になにかできることはありますでしょうか？扇風機は念のために必要でしょうか？

**Comment by iory** [comment]
人がいない夜中にでも駆動時間を測ってみようと思います。

**Comment by aginika** [comment]
@iory 了解です。ありがとうございます。

**Comment by wkentaro** [comment]
回路はtmpですが、つきました。

**Comment by aginika** [comment]
１時間ほどずっと吸って切ってを繰り返していますが、作動しています。

**Comment by iory** [comment]
一時間つけっぱなしにしましたが止まらずに動きました。
大丈夫そうですね。
