### ISSUE TITLE
twitter はじめました

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2014-semi#27]
baxterのtwitterをはじめました．

https://twitter.com/baxter_jsk

です．％　PR2のものは(https://twitter.com/pr2jsk にあります）
```
rostopic pub -1 /tweet std_msgs/String "Hello World"
```
で話します．

画像をポストするには，
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_pr2_startup/jsk_pr2_lifelog/tweet_client.l
みたいに画像へのファイルパスをメッセージに含めればよいです．

ぜひ，遊んでください．

@aginika baxterのlaunchにrostwitterを含めてください．

**Comment by k-okada** [comment]
robot-communication.lにtweet-with-iamgeをついかしたので，commit おねがいします > @wkentaro 
これはjsk_2014_picking_challenge/lanch/image_saver.launchが必要です

タスクの中でものを掴んで，binにいれる直前のところで
(tweet-with-image "I got oreo" "larm")
とか読んでくれると嬉しいです．

**Comment by wkentaro** [comment]
I think tweet-with-image takes some time maybe..
We may need to improve the speed or remove the tweeting in the challenge.

**Comment by aginika** [comment]
昨日の23:00テストラン5:20秒ごろがわかりやすいかと思いますが、確かに５秒ほど停止してしまいます。

またなぜか画像が変わりません。
https://twitter.com/baxter_jsk

**Comment by wkentaro** [comment]
今日のテストランではツイートしていなかったです。

**Comment by aginika** [comment]
Is this fixed?

**Comment by wkentaro** [comment]
今日のテストランではツイートできていたようです。
https://twitter.com/baxter_jsk
