### ISSUE TITLE
Self filterで腕がうまく消えない。

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#272]
かなら前から分かっていたことですが、忘れてました。
daeのmeshでやるという方法がいいかもとのアドバイスでしたので、
やってみます。

**Comment by aginika** [comment]
また、新しく左手についたハンドのモデルの更新もやります。

**Comment by garaemon** [comment]
daeではなく、stlのmeshがオススメです。
daeではpr2_navigation_self_filterは動かない、moveitなら動くけど重い、という状況ですね


2015年4月28日火曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> かなら前から分かっていたことですが、忘れてました。
> daeのmeshでやるという方法がいいかもとのアドバイスでしたので、
> やってみます。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/272>.
>


-- 
✉︎ from iPhone

**Comment by aginika** [comment]
了解です。ありがとうございます。

**Comment by aginika** [comment]
とりあえずcylinderでやってましたが、現状は問題なくなっています。
urdf内での書き方がよくなかったのかもしれません。

**Comment by aginika** [comment]
今日、再発しています。
@garaemon さんのおしゃっていた、stlバージョンでもやってみましたが、
綺麗に消えません・・・
![baxter_self_filter](https://cloud.githubusercontent.com/assets/3803922/7444692/5f53737c-f1cb-11e4-826d-911f44f2df54.png)

**Comment by aginika** [comment]
２つのnodeがこれに対してpublishしていました。
ひとつを殺したら治りました。
