### ISSUE TITLE
pick-objectが上から始めても段々下にいく

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#278]
複数回実行すると下に下がっていくようで、そのせいで物体がつかめないことがあります。

**Comment by k-okada** [comment]
目標値はどうやって決めている？コードのどの部分だろう？

--
◉ Kei Okada


2015-04-28 19:46 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by iory** [comment]
修正しました
angle-vector-sequenceを送った後に, *baxter* を初期位置で更新して対処しました
https://github.com/wkentaro/2014-semi/pull/3

**Comment by wkentaro** [comment]
thanks.

**Comment by wkentaro** [comment]
実機で試しましたが、問題なくつかめるようになりました。

**Comment by aginika** [comment]
今回の主な問題は、頻繁に*baxter*の:angle-vectorを実機と動機させていたことだったのだと思います。
potentio-vectorを参照せずにするように一緒に変更しました。

**Comment by iory** [comment]
@aginika ありがとうございました
