### ISSUE TITLE
収集した画像

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#279]
例えば
```bash
roscd jsk_data

USER=wada make large KEYWORD=jsk_2014_picking_challenge/20150428_collected_images.tgz
(cd large; tar zxvf *.tgz)
```
でデータを持ってくることができます。

**Comment by aginika** [comment]
great

**Comment by wkentaro** [comment]
サンプル

![side20018](https://cloud.githubusercontent.com/assets/4310419/7373657/c7f4634e-ee08-11e4-91b9-e39afa48d3a6.jpg)
![front0023](https://cloud.githubusercontent.com/assets/4310419/7373644/b90d663c-ee08-11e4-9fa9-a0f389b99e86.jpg)
![back0013](https://cloud.githubusercontent.com/assets/4310419/7373660/cd693d72-ee08-11e4-944d-7ff47afd6697.jpg)
![front0016](https://cloud.githubusercontent.com/assets/4310419/7373664/d2a6d65a-ee08-11e4-8128-b73d6b01e91b.jpg)
