### ISSUE TITLE
動作から余分な部分を省く

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#280]
* fold-poseを少なくする。

**Comment by iory** [comment]
pick-object の戻る動作もなくなるといいと思います

**Comment by wkentaro** [comment]
直しました。
![animation](https://cloud.githubusercontent.com/assets/4310419/7400266/9d2e16de-eef6-11e4-9440-156bdb23b605.gif)

**Comment by aginika** [comment]
大分いい感じですね。
今日実機で全部取ってしまいましょう！

**Comment by wkentaro** [comment]
NEXT
=====
MoveToTargetBin からfold-poseを除く

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/346
で可能な限り省いたつもりです。
