### ISSUE TITLE
掃除機の設置方法

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#281]
- 掃除機が高い位置にないと蛇腹が伸びきって危ないときがあります。高めの台が必要です。
- かごに入れたら改善されると思いますが、掃除機の車輪ですべります。

**Comment by aginika** [comment]
掃除機の車輪をガムテープでとりあえず固定したら大分後者はましになりました

**Comment by aginika** [comment]
掃除機を現在はbaxterの後ろに2台ともおいています。伸びきる心配はなくなりました。
本番では2mの範囲を超えない程度に現在の高さを再現する必要があります。

**Comment by wkentaro** [comment]
![](http://i.imgur.com/PWAzAcD.jpg)

**Comment by aginika** [comment]
これをくくりつける予定の紐なんていう呼称でしたっけ？

**Comment by wkentaro** [comment]
ダイリーマですか？

**Comment by aginika** [comment]
それです。ありがとうございます。

**Comment by aginika** [comment]
設置方法は、とりあえずこれで決着がつきそうなのでcloseします。

**Comment by k-okada** [comment]
ダイニーマですね @yuki-asano

--
◉ Kei Okada

**Comment by yuki-asano** [comment]
ダイニーマはb1にあるので、使って構いませんよ

**Comment by wkentaro** [comment]
ダイニーマでしたか。
ずっと聞き間違えていました。

ありがとうございます。
使わせて頂きます。

**Comment by wkentaro** [comment]
掃除機は箱のできるだけ外側から蛇腹を出さないと、baxterが手を伸ばした時に掃除機を引きずり出してしまうことがありました。 2015-05-17 10:00-
箱の中に取り付けるときに、出口ギリギリに置かないとダメそうです。

**Comment by wkentaro** [comment]
@k-okada 
箱への入れ方はどうしましょうか。
できるだけ箱の外側に付けたいので、
ケンシロウ班の人たちに手伝ってもらってフレームを組もうかと考えています。

**Comment by wkentaro** [comment]
今日行った設置方法で今のところ問題無いと思います。
蛇腹の長さが足りないということがあればOpenします。

**Comment by k-okada** [comment]
キャリーケースには白い型抜きした物が必要ですか？それともなんかの梱包材でいいですか？

--
◉ Kei Okada

2015/05/20 0:16、Kentaro Wada <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
掃除機はケースの中で吊るす形にしてあります。そのため、型抜きしたものは必要無く、梱包材を隙間に入れて固定するようにするのでいいと思います。

2015年5月20日水曜日、Kei Okada<notifications@github.com>さんは書きました:

> キャリーケースには白い型抜きした物が必要ですか？それともなんかの梱包材でいいですか？
>
> --
> ◉ Kei Okada
>
> 2015/05/20 0:16、Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> のメッセージ:
>
> > Closed #281.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/281#issuecomment-103551214>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
了解です．

--
◉ Kei Okada


2015-05-20 0:32 GMT+09:00 Kentaro Wada <notifications@github.com>:
