### ISSUE TITLE
Return objectの動作が失敗する

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#286]
stop-graspしてスリープが入っていないなど未完成の部分があるので、直す必要が有ります。

**Comment by aginika** [comment]
Fix with #290 ?

**Comment by wkentaro** [comment]
実機でやった時まだあったように思います。
今日試します。

2015年4月30日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> Fix with #290 <https://github.com/start-jsk/2014-semi/pull/290> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/286#issuecomment-97656475>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by iory** [comment]
Fix with https://github.com/start-jsk/2014-semi/pull/300

**Comment by wkentaro** [comment]
直りました。
