### ISSUE TITLE
本番のセットアップ手順及びそのために必要なもの

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#293]
本番直前にもう一度行うこと
- [ ] Baxterのreboot

ハードウェアセットアップ
- [ ] ハンドを組み立て終わり密閉テープでぐるぐる巻にしてからbaxterに装着する
- [ ] Kinectヘッドの交換
- [ ] ハンドの取り換え
- [ ] kinectの設置
- [ ] Baxter Displayの変更
- [ ] 左手掃除機の向きをちゃんと前に向けることをわすれない
- [ ] 蛇腹の掃除機との結合部分はガムテープで固定する

ソフトウェア動作確認
- [ ] Kinect2の動作確認
- [ ] Kinect2のstatic_tf_publisherの値の確認
- [ ] 棚の位置の確認
- [ ] 掃除機の動作確認
- [ ] じゃばら、および吸い込みハンドの確認
- [ ] baxter.launchの確認
- [ ] ネットワークの確認
- [ ] 全binへのリーチ確認
- [ ] 腕のキャリブレーション（ってしてもよいのでしょうか？）
- [ ] 切り出し画像の確認
- [ ] ディスプレイがつかないときは、sheetaを再起動する

**Comment by aginika** [comment]
プログラム周りはすべて各々動作確認用のlaunchがあったほうがいいと思います。
自動でできる部分はできるだけ増やしたいです。
他にもあったらおねがいします。

**Comment by k-okada** [comment]
ヘッドの取り替えて手順の確認と道具と予備部品がひつようですね
一体型の帽子のしたいところ

2015年4月30日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> プログラム周りはすべて各々動作確認用のlaunchがあったほうがいいと思います。
> 自動でできる部分はできるだけ増やしたいです。
> 他にもあったらおねがいします。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/293#issuecomment-97649305>.
>


-- 
--
◉ Kei Okada

**Comment by aginika** [comment]
直前に一からとりかえる練習をします。

> 道具と予備部品

を#239に加えました。

**Comment by aginika** [comment]
File Descriptor周りの問題と思われるものを回避するために本番前に一度rebootします。

**Comment by aginika** [comment]
直前の手順についても考えなくてはならない時期だと思います。

- 直前では、デスクトップPC及びバクスターの再起動
- roscoreの確認をするためにcheck_state.py
- baxter.launchの起動
- setup.launchの起動/ rvizも起動されます。
- TODO after_launch.pyの実行
- 最後にmain.launchの実行

**Comment by aginika** [comment]
```
自分たちが想定ている商品単語名と主催者が思っているものの違いを確認する。
```
これも直前には確認した方がいいため、それを@wkentaro くんがunittestとして作ってくれました。

**Comment by aginika** [comment]
最新の僕らの予定では、２分前にjsonが渡されるため、

- 直前では、デスクトップPC及びバクスターの再起動
- check_after_boot.py
- baxter.launchの起動
- check_after_baxter.py
- setup.launchの起動/ rvizも起動されます。
- check_after_setup.py
- jsonのアップロード
- unit testをしてjsonの確認を行い
- 最後にmain.launchの実行(jsonファイル名の要チェック)

**Comment by wkentaro** [comment]
そろそろ、srcにいれてある使用するパッケージのタグを決めたほうがいいでしょうか？

**Comment by wkentaro** [comment]
main.launchのjson引数をapc.jsonにしようと思います。
Aで普通に始めてしまうということがあると困るので。
jsonがないとwork_order.pyらへんがエラーを吐くと思います。

**Comment by aginika** [comment]
#773 にあるように、認識の領域がきっちり取り出せているかを確認する必要があります。

これは、ただsetup.launchまであげればいいはずです。

**Comment by aginika** [comment]
#764 から移動して加えました。

**Comment by aginika** [comment]
Move to #796
