### ISSUE TITLE
Baxterのhead故障

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#295]
Baxterおよびmouroを再起動しましたが、
pan及びnodが反応しなくなりました。

**Comment by aginika** [comment]
![robot_state](https://cloud.githubusercontent.com/assets/3803922/7406419/c5dfb816-ef3d-11e4-8d18-4eb76540d2a9.png)

**Comment by k-okada** [comment]
池田さん連絡しよう

2015年4月30日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> [image: robot_state]
> <https://cloud.githubusercontent.com/assets/3803922/7406419/c5dfb816-ef3d-11e4-8d18-4eb76540d2a9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/295#issuecomment-97660223>.
>


-- 
--
◉ Kei Okada

**Comment by aginika** [comment]
相談の結果、
とりあえず保留にします。

この問題は、腕とヘッドのコリジョンによるものな気がするので
本番のロボットは壊さないようにしたいです。
