### ISSUE TITLE
一体型の帽子のしたいところ

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#296]
Kinectのヘッドのアタッチメントをかっこ良くして
一体型にしてほしい @m1a1k0o

**Comment by m1a1k0o** [comment]
・一体化する
・向きがぶれないように固定できるようにする
・Kinectを固定できるようにする
これ以外に何かあれば教えてください．

**Comment by aginika** [comment]
それで大丈夫です。
なるはやだとさいわいです。

**Comment by m1a1k0o** [comment]
寸法は適当で仮で作ってみたのですが，こういうイメージでしょうか？
上の箱の部分にKinectをすっぽりはめられるようにする．
下の棒の部分でBaxterと固定して向きを固定できるようにする．
![baxter_head_kari](https://cloud.githubusercontent.com/assets/11226577/7441796/a1cc4812-f132-11e4-9946-5098cd0e8b2b.png)
疑問なのですが一体化するとはネジなどを用いずにこれを一体化成型するということなのでしょうか？
そうする場合，一体化させるメリットは何なのでしょうか？
パーツわけして組み立てるではだめなのでしょうか？
大きくなるので持ち運びすると無駄にスペースを取ってしまうような気がしますし，あまりメリットがない気がしているのですが．

**Comment by k-okada** [comment]
上の箱はなくていい気がします．今の黄色いのは，そのままKinectがつくようにあっていますが，そのアタッチメント部分だけKinect2につくようにかえればいいのではないでしょうか？どうでしょうか．

--
◉ Kei Okada


2015-05-03 1:35 GMT+09:00 Makoto Sugiura <notifications@github.com>:

**Comment by aginika** [comment]
kinect2は可動部のせいで何故かふわふわとしてしまっています。
それには上から押さえつけなくては固定できない気がしたため、今回この形で依頼しました。

**Comment by aginika** [comment]
センサー位置がずれやすくなる部位が減ることが目的ですが、
もし一体にせずにしても微動だにしないのであれば、僕は問題ありません。

**Comment by aginika** [comment]
@m1a1k0o kinect2の後ろのコードはどこに入る感じでしょうか？

**Comment by aginika** [comment]
一体型でなくてもおｋです。

**Comment by m1a1k0o** [comment]
3パーツに分けて作成します．
kinectの部分，帽子の部分，支えるための部分
３Dプリンターの関係で大きさを多少変えるかもしれません．

![baxter_head_kai](https://cloud.githubusercontent.com/assets/11226577/7467804/1100ed50-f33b-11e4-9508-09a73a8495bb.png)

**Comment by k-okada** [comment]
せっかく３Dプリンタで作るんだからもう少し工夫しよう．
例えば，キネクトと帽子の間のスペースはなぜ必要？
キネクトを止める四角の一番下の部分の四角はなぜ必要？


--
◉ Kei Okada


2015-05-05 15:28 GMT+09:00 Makoto Sugiura <notifications@github.com>:

**Comment by aginika** [comment]
> キネクトと帽子の間のスペースはなぜ必要？

低くつけすぎると自分のヘッドでKinectの入力の半分が消えてしまうため
高くしてもらっています。

**Comment by k-okada** [comment]
なるほど，でも，もう少し，工夫した形にしよう．これだったら角材で作っておいて，と言われそう．

--
◉ Kei Okada


2015-05-05 15:44 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by m1a1k0o** [comment]
工夫というのは見た目ということでしょうか？
kinectがガタガタしてしまうということを聞いたので，なるべく安定性を求めるため，帽子の横部分に支えをつけるなどしたり，kinectがピッタリはまるように凹凸を工夫したりはしています．
それに伴って発生した四角部分は肉抜きするなどして材料を使いすぎないようにしているつもりです．

**Comment by k-okada** [comment]
元の帽子のものは，サイトがあリマスが，今回のものはこうやってサイトを作って自分の論文や修論にこういうものをこうやって作りました，こういう効果が有りました，と自信をもって書けるでクオリティになっていますでしょうか？
http://www.generationrobots.com/blog/en/2015/01/generation-robots-help-baxter-robot-detects-users-thanks-to-motorised-kinect-head-mount/



--
◉ Kei Okada


2015-05-05 16:00 GMT+09:00 Makoto Sugiura <notifications@github.com>:

**Comment by aginika** [comment]
ねじ待ちです。
簡単に載せて見ませたが、僕は大満足です。
向きの固定もかなりよさげでした。

**Comment by aginika** [comment]
仮止めですが、z軸周りの固定がうまくいっていて、かぶせるだけで、その周りの固定は完璧に思えます。
特に今のところねじが届いてないいがいは問題ないので、一旦closeします。

![img_4500](https://cloud.githubusercontent.com/assets/3803922/7613534/3af142f8-f9cc-11e4-860b-6fc8e4943b8b.JPG)
