### ISSUE TITLE
グリッパーのつかみがあまい時に掴んでいないと誤認識する

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#303]

**Comment by wkentaro** [comment]
### 解決案
* 手の測距センサーを使う
* ハンドカメラで差分をとる

**Comment by aginika** [comment]
2人には話しましたが、
現状の吸った判定は内部の構造的に２値のようですが、
掃除機の吸った判定をアナログ的な値にすることはやはり難しいのでしょうか？

**Comment by aginika** [comment]
画像処理をまずやることにするようです。

**Comment by wkentaro** [comment]
https://github.com/wkentaro/tmp/tree/master/apc-check-if-grabbed
でやってみました。

**Comment by aginika** [comment]
結構ぽくなってますね。

**Comment by wkentaro** [comment]
つかんでいないと思っているときは、腕を突っ込んだ位置に必ずもどるので、その位置で背景差分しようと思います。

**Comment by wkentaro** [comment]
kong_tennis_ballも空気が抜けすぎて（布製なので）掴んでいても掴んでいないと認識してしまいます。
![screenshot from 2015-05-03 17 23 06](https://cloud.githubusercontent.com/assets/4310419/7444346/311dc780-f1b9-11e4-8998-84d2dcecac9c.png)

**Comment by wkentaro** [comment]
See #436
