### ISSUE TITLE
掃除機の蛇腹を取り外しする際に壊れないようなグリッパー

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#310]
* 積層を厚くしたものは強く引いて外しても壊れなかった
* 積層を厚くするか、構造を変える

**Comment by m1a1k0o** [comment]
先ほど言いましたが壊れにくくするための吸盤作成しました．
机に置いておくので明日以降に使ってみてください．
![kyuban_kai2](https://cloud.githubusercontent.com/assets/11226577/7431055/95866ea8-f055-11e4-9153-813f0236b467.jpg)

**Comment by k-okada** [comment]
指きったみたいだけど大丈夫？
落ち着いて無理しないように。

--
◉ Kei Okada

2015/05/01 22:58、Makoto Sugiura <notifications@github.com> のメッセージ:

**Comment by m1a1k0o** [comment]
APCとは関係ないことで実験を行っていた際に怪我をしてしまいました．
ご心配をかけてしまい申し訳ございません．

**Comment by wkentaro** [comment]
改良版の吸盤受け取りました。
ありがとうございます。
今日試そうと思います。

**Comment by aginika** [comment]
@m1a1k0o 使ってみました。

@m1a1k0o の指摘していた通り実際に固くなってしまいます。

前回に比べて今のところ抜けにくそうまたちぎれにくそうで、よさげです。
ただ以下が問題点です。
- べたつきが取れません。

- 硬くて今まで撮れていたものが取れにくくなる。

- 取り付けるための穴が小さすぎて、吸盤の先がそこにひっぱられて
    尖ってしまう？花がしぼむような形になってしまう。

![img_4417](https://cloud.githubusercontent.com/assets/3803922/7440775/9aff86be-f102-11e4-94e5-0a1ae5950d20.JPG)
![img_4416](https://cloud.githubusercontent.com/assets/3803922/7440774/9aff487a-f102-11e4-84a8-a2473b8c3c93.JPG)

**Comment by aginika** [comment]
![img_4419](https://cloud.githubusercontent.com/assets/3803922/7440782/5258b29a-f103-11e4-82e3-7be73d8b34c6.JPG)
![img_4418](https://cloud.githubusercontent.com/assets/3803922/7440781/5255a438-f103-11e4-8b4d-c475db881a97.JPG)

**Comment by m1a1k0o** [comment]
＞べたつきが取れません。
これは型から取り出すのが早かったからかもしれません．
適切な時間まで型に入れたままにして造形したものなら大丈夫だと思います．

＞硬くて今まで撮れていたものが取れにくくなる。
これはゴムをシリコンゴムの柔らかいものに変えると少しは良くなるかもしれません．

＞取り付けるための穴が小さすぎて、吸盤の先がそこにひっぱられて尖ってしまう？花がしぼむような形になってしまう。
長くしているので穴の大きさを大きくしてもはずれにくいかもしれませんので作り直せば改善されるかもしれません．
もしくは吸盤部分の半径を大きくする．

今のところ使ってみた感じでは総合的に見て前回のものとどちらが良いと思われますか？

**Comment by aginika** [comment]
今のところ前回の方がまだものを取りやすかったです。
ただ、上に書いたことを試してもらえると嬉しいです。

**Comment by aginika** [comment]
@m1a1k0o 改良版をお願いします。。様々な大きさで色々作ってもらえると嬉しいです

**Comment by aginika** [comment]
途中から話がそれてしまいましたが、

> 掃除機の蛇腹を取り外しする際に壊れないようなグリッパー

の目的は達成できたと思います。
マイナスドライバーで押せば蛇腹もグリッパも破損せずに外せました。（数回）

**Comment by aginika** [comment]
ひびが入ってました・・・
@m1a1k0o 
![img_4514 1](https://cloud.githubusercontent.com/assets/3803922/7666172/70a47f3c-fc15-11e4-8b2b-ba3771339d98.JPG)

**Comment by m1a1k0o** [comment]
ひびが入った原因は何だったのでしょうか？
やはり取り外しが原因でしょうか？

**Comment by aginika** [comment]
ゴムをつけようとしたらひびが入っていることにきづきました
取り外しの瞬間についたような音はしていませんが、
取り外しの瞬間かもしれませんしそうでないかもしれません。
取り外すときに運悪く認知できず、取り外してから気づきました。

**Comment by m1a1k0o** [comment]
新しく造形しなおします。
ひびが入った状態だと吸引力が落ちてしまったり、空気漏れが増えたりすることがあったでしょうか？

**Comment by wkentaro** [comment]
左手でしょうか？
それだと、同じ動作でも物体を落としたりしてたので、少し弱くなってたかもしれないです。
ただ、はっきりとわかるほどではありませんでした。

2015年5月16日土曜日、Makoto Sugiura<notifications@github.com>さんは書きました:

> 新しく造形しなおします。
> ひびが入った状態だと吸引力が落ちてしまったり、空気漏れが増えたりすることがあったでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/310#issuecomment-102634501>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
いえ、漏れの面ではもう問題なくなっていると思います。
ただひびわれから破損すると蛇腹の付け口が外れてしまうのではないだろうかというだけです。

**Comment by aginika** [comment]
右手ですね。

**Comment by wkentaro** [comment]
それだと関係ないですね。。

2015年5月17日日曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 右手ですね。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/310#issuecomment-102635609>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by m1a1k0o** [comment]
わかりました

**Comment by iory** [comment]
右手のグリッパーにひびがはいっていて途中で落ちてしまいます。

**Comment by aginika** [comment]
杉浦に新しいグリッパをもらいました。
あとは、予備を増産してもらうだけだと思っています。
