### ISSUE TITLE
認識を入れた時のPicking Challengeテスト

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#313]
>
５）　認識いれると何分余計にかかるか，成功率は何％上がるか．この時は思ったものがつかめなかたら地面に落とす
６）　認識入れて思ったものがつかめなかったら棚に戻すと何％つかめるか
７）　ちゃんとかごに入れるところまでやる
これをまだやってませんが、どうしましょうか？

**Comment by wkentaro** [comment]
* pick→verifyを行う際の成功率(x / 12)とスコアと時間
* pick→verify→returnを行う際の成功率とスコアと時間
* pick→verify→return/place→pick→verify→placeを行う際の成功率とスコアと時間

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/319
でできるようになったと思います。

**Comment by aginika** [comment]
今日テストして動画をとってみたいですね。

**Comment by aginika** [comment]
mouroでattention_divide.launchを立ち上げた時は、以下のトピックが最終的に得られます。
```
/right_process/apply_mask/output
/left_process/apply_mask/output
```
![rviz_div](https://cloud.githubusercontent.com/assets/3803922/7446865/a604df58-f221-11e4-8b9b-13fa484844e1.png)

**Comment by wkentaro** [comment]
attention_clipperは 
https://github.com/start-jsk/2014-semi/issues/378
ができるとわかってからすることになりました。

まずはpassthrough_filterでrobot-main.lのbugfixと認識の精度確認のためのrosbag取りをしたいと思います。

**Comment by wkentaro** [comment]
認識はpassthroughが上手く行っているときには上手く行っています。（今日は一度も間違えていません）
問題は pick_object が本当に取れるかどうかで、置き方によってかなりとれたり取れなかったり変動します。

**Comment by aginika** [comment]
明日通しを繰り返して、問題の洗い出しができたらお願いします。

**Comment by wkentaro** [comment]
了解です。

**Comment by wkentaro** [comment]
**問題**
* セグメントがうまく行かない時がある
  * 反対側に映り込んでしまう -> filterのパラメータ調整
  * move_for_verificationのパラメータ調整
* 端っこにおいてあるものや少し奥においてあるものがとれない -> pick_objectのパターン調整

**Comment by wkentaro** [comment]
> セグメントがうまく行かない時がある
https://github.com/start-jsk/2014-semi/pull/525

**Comment by aginika** [comment]
今後は、#541で問題の洗い出しとまとめを行います。
