### ISSUE TITLE
[MoveToTargetBin] HへのIKが解けない

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#321]
新しいendeffectorのせいか、解けません。

**Comment by k-okada** [comment]
end-coords変えていないんだよね？
だとすると何が変わったのかな？

2015年5月1日金曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> 新しいendeffectorのせいか、解けません。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/321>.
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
end-coordsはvacuum gripperの先に変えました。

**Comment by k-okada** [comment]
まずは変更したendcoordsが実機とあっているかを確認しましょう @aginika


それが確認できたらなんとかします。

2015年5月2日土曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> end-coordsはvacuum gripperの先に変えました。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/321#issuecomment-98153881>.
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/325/filesで、MoveToTargetBinでIKを解いている位置を同じだけずらしました。
そのため、同じangle-vectorになるはずだと思ったのですが、解きにくくなったのでしょうか？

**Comment by aginika** [comment]
@wkentaro 少し位置を調整しました。大きくは変更していません。

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/335
でfoldポーズを変更したので、解けるようになりました。
