### ISSUE TITLE
cheezitが持てない

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#322]
重心当たりを吸わないと、持てないです。

**Comment by aginika** [comment]
見れてなくて申し訳ないのですが、どう持てないのでしょうか？
ぐりっぱ付ですか？

**Comment by wkentaro** [comment]
滑り止めはつけていました。（動画は撮れていません）
cheezitを棚に横向きにおいた場合には、今のpick-objectの場合は重心当たりを吸うことになるので取れますが、
縦向きにおいた場合には、重心よりずれた位置（cheezitの下側）を持つことになるので、cheezitを斜めに持ち上げようとするけど重くて剥がれてしまうという感じです。

**Comment by wkentaro** [comment]
パラメータを調整して持てるようになりました。
動画の最初のほうで掴んでいます。
https://drive.google.com/drive/u/1/folders/0BwemEk8QQ5j3R2RxX2ltZVZMTm8/0B9P1L--7Wd2vflBMNFk3RkFJQnNiWmxvdm9wR0J0c2lEOGt1S3lYRXBBbGNUUVRqcHJ2REU/0B9P1L--7Wd2vfk5Xakk3dHRoNXc3NnZVX2VPMXhmU3RfWUJsOG9tWWdkQXFPSEhpRHVpUVE/0B9P1L--7Wd2vfmNxWDRPWnYzUEVXYmdQbGVzM0twR3Z3dXJBNVExR1liRVFLQmoxbUNxUkU
