### ISSUE TITLE
mouroでbaxter_commonだけ別repositoryを見てます。

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#332]
以下にしています。(simple_urdfのため)
https://github.com/k-okada/baxter_common/tree/fix_simple_urdf

**Comment by aginika** [comment]
(Announce)

**Comment by k-okada** [comment]
これ，古いbranchに変更したソースだから，今の最新のものとちがっちゃっているので，最新のupdateしようと思いますが，今まで使っていたbaxter_commonのrevision?,
branch? tag? はなんでしょうか？

--
◉ Kei Okada

**Comment by aginika** [comment]
@k-okada tagで1.1.0でした。

**Comment by k-okada** [comment]
https://github.com/k-okada/baxter_common/commits/fix_simple_urdf_v_1_1_0

に，v.1.1.0にsimple urdfを追加したものを作りました．これを使っていきましょう．

--
◉ Kei Okada

**Comment by aginika** [comment]
@k-okada 了解です。置き換えます。

**Comment by aginika** [comment]
置き換えました。
