### ISSUE TITLE
テニスボールてきな商品は中途半端な接触だと持てない

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#341]
どれについても同じですが、これは吸える場所（球面・平面）とそれ以外という形でまざっていて持ちにくいです。

**Comment by aginika** [comment]
@m1a1k0o 持てないです。

**Comment by wkentaro** [comment]
@m1a1k0o  に改良していただいた、柔らかめの吸盤は変形しやすくさらに持ちやすくなりそうです。
吸盤の取り付け部の口径を少し大きくすれば、さらに先端を柔らかいままに保てそうなので、可能ならばお願いします。 @m1a1k0o

**Comment by aginika** [comment]
だんだん良くなってきている気がします。

![img_4480](https://cloud.githubusercontent.com/assets/3803922/7607464/872dabb4-f99c-11e4-8e58-82d3652d7d6a.JPG)

**Comment by aginika** [comment]
@wkentaro 新しいグリッパは試しましたか？

**Comment by wkentaro** [comment]
白いやつですか？
白いやつだと前の5倍ぐらい取りやすいです。

2015年5月15日金曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> @wkentaro <https://github.com/wkentaro> 新しいグリッパは試しましたか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/341#issuecomment-102071565>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
いえ、白いやつで接着部の半径が大きくなっているやつです。
付けやすくなった分取りやすくなってしまうとかの問題がないか気になってます。

**Comment by wkentaro** [comment]
今ついているやつが最新だと思っていたので、それしか試してないです。

2015年5月15日金曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> いえ、白いやつで接着部の半径が大きくなっているやつです。
> 付けやすくなった分取りやすくなってしまうとかの問題がないか気になってます。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/341#issuecomment-102074539>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
あれ、机にあったのがさらに最新かと思ってました。
@m1a1k0o すいません。どれが最新かわかりますか？

**Comment by wkentaro** [comment]
同様に柔らかいやつと、少し固めのやつがあるという認識でした。。

**Comment by m1a1k0o** [comment]
現在最新バージョンは柔らかいものが2つとそれより少しだけ硬いものが１つあります。
覚えている限りでは右手が柔らかいもの、左手が少しだけ硬いもの、机にあるのが柔らかいものとなっていたかと思いますが、その後付け替えた場合はわかりません。

**Comment by aginika** [comment]
ブラシもこれっぽい感じで取れなかったです。

**Comment by aginika** [comment]
基本的に現状の吸盤とハンドで行きます。
新たな変更は今後なさそうです。
closeします。
