### ISSUE TITLE
ぬいぐるみの手足を吸い込むと、離すことができなくなる

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#342]

**Comment by aginika** [comment]
数本で構成される金網を張るという作戦を話してました。

**Comment by aginika** [comment]
@m1a1k0o 数本の金網を通したいです。なんとかできますか？

**Comment by m1a1k0o** [comment]
空気の通り道の部分に格子を作ってものを必要以上に吸い込んでしまわないようにするということでよいのでしょうか？

**Comment by aginika** [comment]
はい、そうです。数本の格子です。
おそらくlong側に機構があればいいのではないかと思います。

**Comment by aginika** [comment]
@m1a1k0o いいかんじでした。

ぬいぐるみ系、ビニール系、箱系、どれも問題なさそうです。
ちゃんと吸引を切ると自然落下します。

![img_4479 1](https://cloud.githubusercontent.com/assets/3803922/7606507/52c3d9fa-f994-11e4-8e3a-6927e5829034.JPG)

**Comment by aginika** [comment]
まだ、実験が足りないかもしれないので、またお願いするかもしれませんが、
とりあえず、おｋだと思います。
@wkentaro にも試してもらって、問題なさそうと決まったらもう一個作ってください。
