### ISSUE TITLE
binの中の座標を指定して、そこからの相対位置でIKを解く

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#347]
いま、PickObjectは相対的にmove-end-posで動かしていますが、それを変更して、「binの中心から30センチ横に移動する」という形で動かす方が良いということですが、変えるなら早いほうがいいですね。
明日中にできるといいと思います。

**Comment by aginika** [comment]
了解です。よろしくお願いします。

**Comment by wkentaro** [comment]
#348 でできるようにしました。
