### ISSUE TITLE
メンバーのアクセス権

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#349]
@k-okada 

@aginika にもwrite権限を与えてもらってもいいでしょうか。
いろいろと都合がいいと思うので。

**Comment by k-okada** [comment]
みれるようになったかな

--
◉ Kei Okada

2015/05/03 16:00、Kentaro Wada <notifications@github.com> のメッセージ:

**Comment by aginika** [comment]
見えました。ありがとうございます
。
