### ISSUE TITLE
[error] unbound variable sound_play::soundrequestaction

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#353]
In robot-main.l, I had error below::
```
2.irteusgl$ main
[ERROR] [1430642041.454463597]: attempted to getTopic to topic robotsound, which was not previously advertised. call (ros::advertise "robotsound") first.
/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error: unbound variable sound_play::soundrequestaction in (send #:inst23135 :init "/sound_play" sound_play::soundrequestaction :groupname "speak")

```

**Comment by aginika** [comment]
I couldn't replay on mour.

But I think sound_play 's deb which include aciton_msgs  is not released, so you should clone from github.

**Comment by k-okada** [comment]
if our software depends on unreleased version of sound_play, we need to
update https://github.com/start-jsk/2014-semi/blob/master/README.md, or
better to create custom rosinstall file as
https://github.com/jsk-ros-pkg/jsk_robot/blob/84629a3000f087d58cc2300bd686d1a4a5e804c0/jsk_pepper_robot/pepper.rosinstall

--
◉ Kei Okada

**Comment by wkentaro** [comment]
tnx.
