### ISSUE TITLE
回路まわりが焦げ臭くなった

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#365]
箱が溶けているらしいので、放熱周りを切除したい。

**Comment by wkentaro** [comment]
@m1a1k0o 
二個目ができたらお願いできますか？

**Comment by aginika** [comment]
@wkentaro くんが切除してくれました。
プラスチックの裏側も溶けていたので、すこしナットで浮くようにしています。
新しく箱を作るときの参考になると嬉しいです。
