### ISSUE TITLE
roseus subscriberで予期しないros-info

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#370]
https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/motion/verify-object.l#L12
```
roscd jsk_2014_picking_challenge/euslisp
roseus robot-main.l
> verify-object

```
とするとひたすらnil/tが表示されます。
これは`correct?`が表示されているように思いますが、理由が全くわかりません。

**Comment by aginika** [comment]
spin-onceで他のsubscribeをしていることが原因でした。

**Comment by wkentaro** [comment]
こういうのは、自分のトピックだけspin-onceのが普通ですか？

**Comment by aginika** [comment]
問題がない限り、自分はあまり気にしたことありませんね・・・
何度もsubscribeされて困り、要らなくなるタイミングがあるならunsubscribeすればよいのかもしません。

**Comment by wkentaro** [comment]
ありがとうございます。
問題になれば、namespaceを指定するというようなこともしたいと思います。
