### ISSUE TITLE
認識周りがかなり遅い

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#372]
ので遅延の原因を切り分けて早くできるようにします。

**Comment by aginika** [comment]
作戦は,resize_image_transportやorganized_passthroughで処理範囲を小さくします。

**Comment by aginika** [comment]
あと、openCLをmouroに導入します。

**Comment by aginika** [comment]
現状/kinect2/depth_highres/pointsのhzが1.2hzほどで激遅です。

**Comment by wkentaro** [comment]
OpenCLが導入できたということで3hzほどになってかなり改善されたということでしょうか。
mouroでも使えますか？

**Comment by aginika** [comment]
新しいPCでもopen CLが導入できるように今後も少しやってみます。

**Comment by aginika** [comment]
今日は、色々と認識を早くするように試行錯誤しました。
あまりorganized_passthroughははやくなりませんでした。

- kinect_bridge.launchの段階で試したこと
 - worker_threads -> 増やす. 遅くなる. 4が一番はやい.3hz->0.8hzほど
 - max_depth->狭める。pass_throughを使う時より激遅. 3hz->0.4hzほど
 - そのままが一番はやい
- それ以降の部分で早くしたこと
 - attention_clipperで 入力 2.8hz -> 出力 0.2hzになっていて明らかにボトルネック
 - すべてpassthroughで対応 入力 2.8hz->2hzほど
 - managerをすべて共通にすると遅くなる-> 共通, larm , rarmの3つのmanagerにする
 - standaloneをすべてloadに変更
 - organized_passthroughをやって範囲を限定する.ほんの少し早くなる
 - 共通のpassthroughをself filterより前に持ってくる。ほんの少し早くなる

これだけやって最後のapply_maskが1.2hzほどです。

**Comment by aginika** [comment]
結局kinect_bridgeが早くならないと変わらなくなってしまいます。

**Comment by k-okada** [comment]
kinect-bridge.launchのそのスピードは開発者も認識している問題でしょうか？ code-iasに聞いてみたかな？

--
◉ Kei Okada
