### ISSUE TITLE
VerifyObjectのモードの時に判別結果を可視化

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#377]
判別結果をPictogramを使って手の位置に出したいと思います。

**Comment by garaemon** [comment]
@aginika tweetもしたら楽しいですね

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/motion/tweet.l#L4
でいまは文字だけならすぐできます。
余裕があったら画像も出したいです。

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/400

**Comment by wkentaro** [comment]
いま、publish-popup-textを使っていますが、5文字以上くらいで切れてしまいます。(文字を小さくしても変わらない)

最大文字数はどうやって増やせばいいでしょうか。 @aginika

**Comment by wkentaro** [comment]
長い文字だと表示するのが大変そうなので、一旦closeします。
