### ISSUE TITLE
左右の腕同時稼働が本当に可能なのか検証する

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#378]
ぶつかるのを避ける必要があるので、完全に独立に同時稼働が出来るか、調べたいです。
出来なくても、体の前を腕が横切るときは避けて、pickやreturn, verifyだけを同時稼働ならできると思います。

**Comment by aginika** [comment]
これは、今の平行動作ができたあとにやるかどうかを決めます。
真ん中はどちらかの腕に割り当てる方法を先にやって余裕があったら考えます。

**Comment by wkentaro** [comment]
了解です。
