### ISSUE TITLE
Visualize awesome score board

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#385]
From: https://github.com/start-jsk/2014-semi/pull/361
>
nice, もっとかっこよくしよう
http://tennis.jp/wp-content/uploads/2012/10/IMG_2860s.jpg
http://metoo.up.n.seesaa.net/metoo/image/p1000566.jpg?d=a1
>
>
赤白でもいいが，スコアボードにscore boardはいらないかな．
国旗とチーム名が必要か．
残り時間が表示されると良いか．
下に取り除いた物品，とこれから取り除く物品がひょうじされるといいか．

**Comment by aginika** [comment]
#385
