### ISSUE TITLE
*bin-contents* まわりでsegmentation faultする

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#387]
というのはまだ発生しますか？ @wkentaro

**Comment by wkentaro** [comment]
今日実験するときに確認します。

**Comment by aginika** [comment]
@wkentaro これは再発していますか？

**Comment by wkentaro** [comment]
最近は発生していないと思います。
callback関数のエラーを直したときに治ったのかもしれないです。(defparameterを使ったりしているところもあったので）

**Comment by aginika** [comment]
また発見したら開きます。
