### ISSUE TITLE
最新のbaxter-interface.lではIKが解けない

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#409]
move_to_target_binが失敗するようになります。
いまは baxter-interface.lは58eb815 を使っています。

**Comment by k-okada** [comment]
https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/test/test-robot-motion.l
でエラーになる？ならなければ，どうやったらココでエラーになるようにできるかな．

--
◉ Kei Okada

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/411/files
でできます。

**Comment by wkentaro** [comment]
```
(baxter-init :safe nil)
```
だとsuccessです。

**Comment by wkentaro** [comment]
顔のコリジョンが原因のようで、(baxter-init :safe nil)で動かしています。

**Comment by aginika** [comment]
まだ問題になってますでしょうか？

**Comment by wkentaro** [comment]
:safe nil
でぶつからずに動かせているので、closeします。
