### ISSUE TITLE
物体をつかんでいなくてもmove-for-verificationをしてしまう

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#413]

**Comment by iory** [comment]
これはhttps://github.com/start-jsk/2014-semi/issues/303
とは逆で、何か一瞬掴んだ時に
/gripper_grabbed/limb/left/stateがtrueになってそれが残ったのかな？

**Comment by wkentaro** [comment]
いや、ものをつかんでいない時はしないというようなコードが無い。

**Comment by iory** [comment]
そういうことか。
今の段階ではつかめなかった状態では、次の棚に挑戦するというふうにするか、
pick-objectで確実につかめるように改良していくということになるかな

**Comment by wkentaro** [comment]
* robot_mainはそんなに複雑にせず、pick_objectを呼ぶだけにする。
* pick_objectの後つかめているかどうかCheckする。

というのがいいと考えている。
プログラムを複雑にし過ぎないためにも、掴めたかどうかの判定が早めに欲しいな。

2015年5月7日木曜日、ioryz<notifications@github.com>さんは書きました:

> そういうことか。
> 今の段階ではつかめなかった状態では、次の棚に挑戦するというふうにするか、
> pick-objectで確実につかめるように改良していくということになるかな
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/413#issuecomment-99702050>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
要するに、今の段階でも最終段階でも掴んでいたら判別するに掴んでなかったらしない、というようにするつもり。

2015年5月7日木曜日、和田 健太郎 / Kentaro Wada<www.kentaro.wada@gmail.com>さんは書きました:

> * robot_mainはそんなに複雑にせず、pick_objectを呼ぶだけにする。
> * pick_objectの後つかめているかどうかCheckする。
>
> というのがいいと考えている。
> プログラムを複雑にし過ぎないためにも、掴めたかどうかの判定が早めに欲しいな。
>
> 2015年5月7日木曜日、ioryz<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
>> そういうことか。
>> 今の段階ではつかめなかった状態では、次の棚に挑戦するというふうにするか、
>> pick-objectで確実につかめるように改良していくということになるかな
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/start-jsk/2014-semi/issues/413#issuecomment-99702050>
>> .
>>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com <http://www.wkentaro.com>
>
>
>

-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>
