### ISSUE TITLE
pick_objectのパターンを増やす

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#414]
絶対につかむためには、パターンを増やして掴めるまで努力する量を増やすことが必要そうです。

**Comment by wkentaro** [comment]
Bin内を例えば三次元的に27分割して、物体がどこにあるか認識器に言われたらそこにいけるようにしたいです。

**Comment by wkentaro** [comment]
![2015-05-09 23 52 54](https://cloud.githubusercontent.com/assets/4310419/7550705/e6fa9758-f6a6-11e4-94a4-c25e88b4ba05.jpg)

**Comment by aginika** [comment]
@iory ping

**Comment by iory** [comment]
やります

**Comment by aginika** [comment]
現状手前のものしかとれず少しでも奥にあるととれないそうです。

**Comment by iory** [comment]
https://github.com/start-jsk/2014-semi/pull/641
pick-objectのパターンを増やしてみました。
値の調整などいると思いますし、なにか問題あったらおねがいします。

**Comment by k-okada** [comment]
これはテストはしてみたものなのかな．

--
◉ Kei Okada


2015-05-20 4:51 GMT+09:00 ioryz <notifications@github.com>:

**Comment by iory** [comment]
#704 #684  #683
