### ISSUE TITLE
掃除機の基板をかっこよくする

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#418]
前に@k-okada 先生が基板をかっこよくしてくれと言っていたのですが、
もう一回詳しく聞いてもいいでしょうか？

**Comment by iory** [comment]
基板作成しました。
![2015-05-08 02 37 04](https://cloud.githubusercontent.com/assets/4690682/7528649/5a243758-f566-11e4-8ca5-cbc04f670039.jpg)

**Comment by wkentaro** [comment]
確かにかっこいい。。
ありがとうございます。
