### ISSUE TITLE
レインボーのpodを灰色に表示させたい

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#423]
eusで難しければ、poseをpublishして、その姿勢でstlを表示するようにします。

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/euslisp/roseus-utils.l#L287
を一行コメントアウトすると表示されます．
rvizのバグなんだけどなぁ．何故か治らない．

--
◉ Kei Okada

**Comment by wkentaro** [comment]
オープンハウス用なので、コメントアウトで対応します。

2015年5月7日木曜日、Kei Okada<notifications@github.com>さんは書きました:

>
> https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/euslisp/roseus-utils.l#L287
> を一行コメントアウトすると表示されます．
> rvizのバグなんだけどなぁ．何故か治らない．
>
> --
> ◉ Kei Okada
>
>
> On Thu, May 7, 2015 at 7:12 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > eusで難しければ、poseをpublishして、その姿勢でstlを表示するようにします。
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/start-jsk/2014-semi/issues/423>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/423#issuecomment-99808813>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
僕の環境ではコメントアウトでも治らない気がするのですが、
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/euslisp/roseus-utils.l#L287
のコメントアウト以外には何もしなくて大丈夫ですか。

**Comment by k-okada** [comment]
間違いました．colors の方をコメントアウトします．
https://github.com/jsk-ros-pkg/jsk_roseus/blob/master/roseus/euslisp/roseus-utils.l#L288

--
◉ Kei Okada


2015-05-10 3:47 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by aginika** [comment]
これは想定された表示でしょうか？
![black_pod](https://cloud.githubusercontent.com/assets/3803922/7563478/9eb1edb6-f818-11e4-9e8f-3ce38e0e71ba.png)

**Comment by k-okada** [comment]
おお，で，
  (send msg :color  (vector->rgba (float-vector 0 0 0) a)))
を見て，いい感じの色をいれてください，ということでした．


--
◉ Kei Okada

**Comment by aginika** [comment]
![blue_object](https://cloud.githubusercontent.com/assets/3803922/7563870/55fa1860-f81c-11e4-98db-f8c804cfdc96.png)

**Comment by aginika** [comment]
Close with #480
