### ISSUE TITLE
もうひとつデプスセンサをつける

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#426]

**Comment by iory** [comment]
これは電子回路的なことで解決するんですか？
それとも、そういうパーツがあるのでしょうか？

**Comment by wkentaro** [comment]
トルソ辺りにKinectをもう一台つけるということではないでしょうか。

**Comment by aginika** [comment]
はい、トルソにkinect的なものをつけるだけなので、気にしなくて大丈夫です。

**Comment by iory** [comment]
了解です。

**Comment by aginika** [comment]
Asus xtionを腰につけるとこんな感じに見えます。
![asus_openni](https://cloud.githubusercontent.com/assets/3803922/7587596/7a671ca8-f8f2-11e4-98b3-080d8cafe1fd.png)

**Comment by aginika** [comment]
![xtion_image](https://cloud.githubusercontent.com/assets/3803922/7587625/b2af1804-f8f2-11e4-9702-3c4ec5b3c797.png)

**Comment by aginika** [comment]
新しいPCではsoftkinetcが開けなかったです。
もう少しやってみますが、kinect2の2つめを使えるならそれもやってみたいと思います。

**Comment by aginika** [comment]
launch的にできるのですが、libusbのバスエラーが出てしまうため、もう一つPCを追加します。

**Comment by k-okada** [comment]
複数PCが安全ですが，この場合，
lsusb を見て，違う，バス／チップ につながっているのを確認する，というのが常套手段ではあります．

--
◉ Kei Okada

**Comment by aginika** [comment]
念のため全usbの組み合わせで試したのですが、だめでした。

**Comment by m1a1k0o** [comment]
baxterの胴周りにkinectを取り付けたいということだったので取り付け具を作成してみました。
造形はよる0時あたりにできそうです。そこからサポート材を溶かすので明日になるかと思います。
![torso_baxter](https://cloud.githubusercontent.com/assets/11226577/7714346/ce0dd29a-feb8-11e4-8668-eb308c9ebe8c.png)

**Comment by aginika** [comment]
ありがとうございます。いい感じですね。

**Comment by wkentaro** [comment]
kinectがtorsoにつきました。

![Uploading 2015-05-21 11.53.48.jpg…]()
![2015-05-21 11 54 02](https://cloud.githubusercontent.com/assets/4310419/7740706/bd272da2-ffb0-11e4-9b80-21fb11868ebf.jpg)

**Comment by wkentaro** [comment]
ただ、kinectとの結合部がひとつしかないので、15時には元に戻す必要がありそうです。
造形は明日(あっていますか? > @m1a1k0o )できるということです。

**Comment by m1a1k0o** [comment]
kinectとの結合部品は明日になると思います。

2015年5月21日 12:01 Kentaro Wada <notifications@github.com>:

> ただ、kinectとの結合部がひとつしかないので、15時には元に戻す必要がありそうです。
> 造形は明日(あっていますか? > @m1a1k0o <https://github.com/m1a1k0o> )できるということです。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/426#issuecomment-104109533>
> .
>



-- 
-------------------------------------------------------------------------------------
杉浦 誠 (Makoto SUGIURA)
東京大学 情報理工学系研究科 知能機械情報学専攻
稲葉・岡田研究室（情報システム工学研究室）
〒113-8656 東京都文京区本郷7-3-1 工学部2号館73B1
E-mail: sugiura@jsk.imi.i.u-tokyo.ac.jp
Tel: 03-5841-7416 / Fax: 03-5841-6285
-------------------------------------------------------------------------------------

**Comment by aginika** [comment]
完璧についてます。
後は僕が頑張ります。
ありがとうございました。
