### ISSUE TITLE
mouro以外のPCでの動作確認を行う

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#427]

**Comment by aginika** [comment]
デスクトップのセットアップはできたつもりです。今日から新しい方に変わっているので、注意してください。
今後USB周りの問題が起きるか確認できたらと思います。

OpenCLの導入は、デスクトップの方ではできませんでした。

以下のエラーが出てしまうため、depth nodeletが失敗します。
```
cl_get_gt_device(): error, unknown device:
```
https://github.com/code-iai/iai_kinect2/issues/63 にもあるようなエラーなのですが、解決できずでした。
ただ、hz : 3.8hzあります。ノートPCの方はなにかをミスっていたのでしょうか・・・

とりあえずノートも動作の確認をします。

**Comment by wkentaro** [comment]
ありがとうございます。

**Comment by aginika** [comment]
![pazu](https://cloud.githubusercontent.com/assets/3803922/7550739/5abf45ca-f6a8-11e4-800c-a3996f5ff9db.png)

**Comment by aginika** [comment]
ノートPCの方も確認終わりました。
デスクトップもノートも下記のことを確認しています。
- 点群が見れるか
- 掃除機の吸い込みをできるか
- challenge.launchができるか
- モデルが正しいか
ノートPCにはすこしきつそうです。

nodeを上げるほど、hzが落ちて行きますね・・・
表示を確認しましたが、やはりOpenCLで走っているはずです。

**Comment by aginika** [comment]
今回のセットアップの関係のためにいくらかREADMEアップデートしました。
何か新しいデスクトップを使っていて問題があったら言ってください。

**Comment by wkentaro** [comment]
了解です。

**Comment by wkentaro** [comment]
Couldn't find an AF_INET
と言われるときはどうすればいいでしょうか。

**Comment by wkentaro** [comment]
133.11.216.214 baxter 011310P0014.local
を/etc/hostsに追加してみます。

**Comment by k-okada** [comment]
新しいマシンはdhcpになっている？

--
◉ Kei Okada

**Comment by wkentaro** [comment]
dhcpです。

**Comment by wkentaro** [comment]
>
133.11.216.214 baxter 011310P0014.local
を/etc/hostsに追加してみます。

で直りました。
