### ISSUE TITLE
吸引ノズルの改良

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#429]
複数の穴をつけるかもしれないです。

**Comment by aginika** [comment]
@m1a1k0o 今どんな感じでしょうか？

**Comment by m1a1k0o** [comment]
落下防止弁がまだ届いていないので、まだ試すことが出来ません。
それ用の吸盤もまだこれから造形なので、まだできていません。
届き次第試してみます。

**Comment by aginika** [comment]
届きましたか？

**Comment by aginika** [comment]
届いたらreopenしてください。
