### ISSUE TITLE
両腕の並列駆動実装

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#430]
* 左右別のnodeで動かす。
* 真ん中のBinから取っている間(左腕)は右腕は動かさない。

**Comment by wkentaro** [comment]
@aginika 
最初にctypeのデフォルトを書き換える方法などありましたか？（以前古田さんと話していたかもしれません）

**Comment by aginika** [comment]
@wkentaro 
```
 setq *ri* (instance baxter-interface :init :type :rarm-controller)
```

**Comment by aginika** [comment]
で動くことを確認しました。
https://github.com/jsk-ros-pkg/jsk_robot/pull/325 がマージされると使えるようになります。

**Comment by wkentaro** [comment]
助かります。
ありがとうございます。

**Comment by wkentaro** [comment]
```
(send *ri* :angle-vector (send *baxter* :angle-vector) :fast :rarm-controller 0)
```
でanglesを送っても、
https://drive.google.com/open?id=0B9P1L--7Wd2vTWtaQ2ZFeFBiNWs&authuser=1

 jsk-ros-pkg/jsk_robot#325 を使っても両腕が動いてしまいます。何か他に変えるところなどありますか？

![image](https://cloud.githubusercontent.com/assets/4310419/7550857/d2a14166-f6ac-11e4-8f68-9e5cfce47dc4.png)

**Comment by aginika** [comment]
I'm not sure, but I think this is bug ?..(I tested on real robot, and I confirmed the real robot is really works only designated arm..)
Please check if you have time below codes
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L278

I reported below
https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/135

**Comment by wkentaro** [comment]
了解です。
バグが治るまでは実機でやることにします。

**Comment by wkentaro** [comment]
```
    (send *ri* :angle-vector-sequence avs :fast :default-controller 0 :scale 2.2)
```
With `:default-controller` argument, there is warning `;; controller-type: 0 not foundnil` and I can't have robot move.

**Comment by wkentaro** [comment]
```
(send *ri* :angle-vector-sequence avs)
```
does work.

**Comment by wkentaro** [comment]
See https://github.com/jsk-ros-pkg/jsk_robot/pull/329/files

**Comment by k-okada** [comment]
もしかしてこれって，やりたいことは，
send *ri* :anlge-vector av tm :larm-controller
だったりする？
その時に，*ri* を作るときには普通につくればいいはず．

--
◉ Kei Okada

**Comment by aginika** [comment]
@k-okada 
完全に右腕と左腕を分けたnodeを立ち上げて、それぞれのinitの時点でcontroller-typeを固定しようとしています。そこだけ変えれば対応箇所だけangle-vectorで送られることを期待してました。

本当は、:angle-vectorすべてにcontrollerをしたくない形が理想ですが、angle-vectorの引数がoptionであるため、なんらかのコントローラを指定しなくてはならないです。

*ri*を普通に作ればできるのですが、全部に指定が必要になってしまいます。

**Comment by k-okada** [comment]
```
(send *ri* :angle-vector-sequence avs :fast (*ri* . controller-type) 0 :scale 2.2)
```
がやりたいことになるのかな．

**Comment by wkentaro** [comment]
そうです。

2015年5月14日木曜日、Kei Okada<notifications@github.com>さんは書きました:

> (send *ri* :angle-vector-sequence avs :fast (*ri* . controller-type) 0 :scale 2.2)
>
> がやりたいことになるのかな．
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/430#issuecomment-101899688>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
```
(defmethod robot-interface
  (:controller-type () controller-type))
```
をつくって，
```
(send *ri* :angle-vector-sequence avs :fast (send *ri* :controller-type) 0 :scale 2.2)
```
という可能性もあります．

`:default-controller`という名前がややこしいですが，そういう名前の:fullbody-controller です．
https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/robot-interface.l#L648
なので，例えば
```
(send *ri* :angle-vector-sequence avs :fast nil 0 :scale 2.2)
```
として，
```
(if (null ctype) (setq ctype controller-type))
```
とするのもあります．

**Comment by wkentaro** [comment]
```
(send *ri* :angle-vector-sequence avs :fast nil 0 :scale 2.2)
```
が一番王道ぽいですね。

**Comment by wkentaro** [comment]
PR送りました。 https://github.com/jsk-ros-pkg/jsk_robot/pull/330

**Comment by k-okada** [comment]
おそくなりました．robot-interface.l　を買えるのでいい気がしますが，どうでしょうか．

**Comment by wkentaro** [comment]
なるほど、これで問題ないですか。
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/138/files

**Comment by k-okada** [comment]
OKでしょうか．

--
◉ Kei Okada

**Comment by wkentaro** [comment]
ありがとうございます。

2015年5月14日木曜日、Kei Okada<notifications@github.com>さんは書きました:

> OKでしょうか．
>
> --
> ◉ Kei Okada
>
>
> On Thu, May 14, 2015 at 3:15 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > なるほど、これで問題ないですか。
> > https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/138/files
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/start-jsk/2014-semi/issues/430#issuecomment-101932338>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/430#issuecomment-101941023>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
I sent PR to pass nil as ctype.
https://github.com/start-jsk/2014-semi/pull/508

**Comment by aginika** [comment]
並列動作の問題点はまだなにかありますか？

**Comment by wkentaro** [comment]
ないです。
closeします。
