### ISSUE TITLE
angle-vectorを変えていって最適な予備姿勢を求めるUtils

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#435]
質問なのですが、angle-vectorを変えていって、目標姿勢への予備姿勢を求めるutilsのようなものはありますか？
リアルタイムにプランニングするのではなく、今回のようにmove_to_target_binなどができるための予備姿勢を準備段階で求めておくようなものです。

**Comment by aginika** [comment]
> angle-vectorを変えていって、目標姿勢への予備姿勢を求める

これは始点と終点だけでなくて、その間の軌道の点も求めるということでしょうか？

>予備姿勢を準備段階で求めて

準備段階とは、試合前に例えば研究室で求めておいて, ということですか？

**Comment by wkentaro** [comment]
> これは始点と終点だけでなくて、その間の軌道の点も求めるということでしょうか？

軌道ではなくて、目標点のIKを解くためにシミュレーション上だけでなる姿勢です。
move_to_target_binだと [ここ](https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/euslisp/motion/move-to-target-bin.l#L7-L9)で、binによっていろいろな予備姿勢になってからIKを解いています。
この予備姿勢を自動的に求められないかと考えて、質問しました。

> 準備段階とは、試合前に例えば研究室で求めておいて, ということですか？

そうです。

**Comment by wkentaro** [comment]
一番愚直にangle-vectorを飛び飛びに変えていってその都度目標点へのIKを解くというのでも、使えそうかなと思ったので。 
そこに今回の並列駆動での要求のように、体の半分から手が出ないようにするなどの条件をつけることができればと思っています。

**Comment by aginika** [comment]
@k-okada どうなのでしょうか？

**Comment by k-okada** [comment]
この手のものと，立ち位置探索は毎年誰かプログラム書いてどこか行っちゃう系なんだけど，

https://github.com/start-jsk/2014-semi/pull/411/files
を復活させてテストコード掛けばいいんだよね？
この程度だったら素直に解けると思うんだけど．

> 今回の並列駆動での要求のように、体の半分から反対へ手が出ないようにする

はどういう意味かな．

**Comment by aginika** [comment]
右手はbaxterから見て右半分側の領域のみを移動可能、
左手はbaxterから見て左半分側の領域のみでの移動可能という形を指していると思います。
並列に動かすときに両方が動作しうる空間をなくしたいためです。

**Comment by aginika** [comment]
結局解決したのでしたっけ？

**Comment by k-okada** [comment]
特に必要はないんような感じですが，
https://github.com/jsk-ros-pkg/jsk_robot/pull/332
でsafeでも全てのbin ( - 90cm) には届くようになっていると思います．
テストコードはreset-poseから始めていますが
https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/baxtereus/baxter-util.l#L4
で一発で解けない時に，untuckからやり直しているので，初期（予備）姿勢にかかわらず
解けるはずだと思っています．


--
◉ Kei Okada

**Comment by wkentaro** [comment]
了解です。
ありがとうございます。
