### ISSUE TITLE
掃除機基盤の複製

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#443]
前に https://github.com/start-jsk/2014-semi/issues/418
で上げましたが、
これで問題ないなら予備としてもう一台作成します。

**Comment by wkentaro** [comment]
@k-okada

**Comment by k-okada** [comment]
これで良いです
ヒートシンクはもう少し大きいほうがいいかな
これで複製しましょう

2015年5月10日日曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> @k-okada <https://github.com/k-okada>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/443#issuecomment-100633010>
> .
>


-- 
--
◉ Kei Okada

**Comment by iory** [comment]
二台目作りました。
ヒートシンクは大きなものに換装します。
二台目を作るついでにデバッグボタンをつけておきました。
これで掃除機を手動でつけれます。
![2015-05-11 07 06 42_mini](https://cloud.githubusercontent.com/assets/4690682/7556494/7fbd2292-f7ad-11e4-911d-0ecc975700a5.jpg)

**Comment by wkentaro** [comment]
一旦これで問題なさそうです。
