### ISSUE TITLE
画像の透明部分を省いて色ヒストグラムを作る

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#452]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/927
でApplyMaskImageのoutputがRGBAにできて、maskの黒い部分を透明にできるので、これに合わせて色ヒストグラムを作るときに透明部分を省く操作を入れてください。 @iory

**Comment by iory** [comment]
了解です

**Comment by aginika** [comment]
ping

**Comment by k-okada** [comment]
これって出来たんだっけ？

つかむ前に一瞬で計算できたら、ランダムに掴みいまのプログラムで
どこから始めるか？(右か左か真ん中か？)かえるといいですね

150点をこえだしたら、やってみたい所。

**Comment by iory** [comment]
これも透明部分を省いてやるのはできています。
つかむのは https://github.com/start-jsk/2014-semi/issues/414 
pick-objectの順番を変えるということでいいでしょうか？

**Comment by k-okada** [comment]
はい、そうです

ただ、まず#414を先にやるのがいいですね


認識すると基本は時間がかかって失敗も多くなるので、まずは認識なしでやってベース作って、認識入れるとそれがどれぐらい良くなるかを調べるのが良いですね

--
◉ Kei Okada

2015/05/19 22:17、ioryz <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/issues/428
の中でということですか？

**Comment by k-okada** [comment]
あ、はい
これです

--
◉ Kei Okada

2015/05/19 23:05、Kentaro Wada <notifications@github.com> のメッセージ:
