### ISSUE TITLE
ros::get-topic-publisherのエラー

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#464]
これはなくさない方針になったのでしょうか。　@aginika

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_roseus/pull/307 で書きなおして下さい @aginika

--
◉ Kei Okada

**Comment by wkentaro** [comment]
#467 で全て書き換えました。

**Comment by aginika** [comment]
@wkentaro このレポジトリ内にもあったのですね。ありがとうございます。

**Comment by wkentaro** [comment]
```
15.irteusgl$ assoc "/vacuum_gripper/limb/right" (ros::get-topics) :test #'equal
("/vacuum_gripper/limb/right" . "std_msgs/Bool")
16.irteusgl$ ros::publish "/vacuum_gripper/limb/right" msg
[ERROR] [1431425214.404707058]: attempted to publish to topic /vacuum_gripper/limb/right, which was not previously advertised. call (ros::advertise "/vacuum_gripper/limb/right") first.
t
17.irteusgl$
```

**Comment by wkentaro** [comment]
上手く行かない時が有ります。

**Comment by k-okada** [comment]
```
rostopic info /vacuum_gripper/limb/right
```
すると，どうなるかな．

--
◉ Kei Okada

**Comment by wkentaro** [comment]
明日また確認します。

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/7604295/3469bbd2-f97b-11e4-9407-911ae9f9e2ba.png)

It is raises also in "/robotsound" ..

**Comment by wkentaro** [comment]
As for `/vacuum_gripper/limb/right`
```
 % rostopic info /vacuum_gripper/limb/right
Type: std_msgs/Bool

Publishers:
 * /robot_main_1431493452715840621 (http://133.11.216.60:51903/)

Subscribers: None
```

**Comment by aginika** [comment]
ros::get-topicはどうやら誰かがpublishしているだけで、自分がadvertiseしてなくても入ってしまうみたいです。

**Comment by k-okada** [comment]
そうですね．
https://github.com/jsk-ros-pkg/jsk_roseus/pull/306
を復活させています．チョット待っていて下さい．

--
◉ Kei Okada


2015-05-13 16:06 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by k-okada** [comment]
ごめんなさい，一番最初の @aginika さんの
https://github.com/jsk-ros-pkg/jsk_roseus/pull/297
が正しいです．ようやく理解しました．

なので，元々のコードでよかったです．すいません．．

**Comment by aginika** [comment]
The PR was merged

**Comment by wkentaro** [comment]
we need to use it in thos repo

2015年5月15日金曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> The PR was merged
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/464#issuecomment-102074762>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
PR: #529
