### ISSUE TITLE
lispでの文字列置換

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#472]
```
In [1]: "oreo_mega_stuf".replace('_', ' ')
Out[1]: 'oreo mega stuf'
```
みたいなことはどうすればいいでしょうか。

**Comment by k-okada** [comment]
```
$ setq aaa "aaa_aaa"
$ setf (schar aaa (position #\_  aaa)) #\-
```

**Comment by wkentaro** [comment]
tnx.

**Comment by wkentaro** [comment]
副作用無しにしたいのですが、文字列のコピーはどうすれば良いでしょうか？

2015年5月12日火曜日、Kei Okada<notifications@github.com>さんは書きました:

> $ setq aaa "aaa_aaa"
> $ setf (schar aaa (position #\_  aaa)) #\-
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/472#issuecomment-101133990>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
copy-list "abc"
とか．

--
◉ Kei Okada


2015-05-12 19:40 GMT+09:00 Kentaro Wada <notifications@github.com>:
