### ISSUE TITLE
Attention clipperとmove-for-verificationの位置合わせ

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#501]
画像が切れてしまったり、右に持っているものが左に写ったりしてしまうので、調整が必要です。

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/7611092/f1471434-f9bc-11e4-93d1-99fd32855ee1.png)

**Comment by wkentaro** [comment]
Let's fix the good parameters after attaching kinect2 with new support.

**Comment by wkentaro** [comment]
Kinectの位置合わせを明日やりたいとおもいます。

**Comment by aginika** [comment]
- 画像が見切れていたのは、organized_passthorughのパラチュンが必要です。
- 右に写っていたものが左に写っているのは、rvizの設定の問題です。

すいません。

**Comment by wkentaro** [comment]
了解です。
ありがとうございます。

2015年5月13日水曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

>
>    - 画像が見切れていたのは、organized_passthorughのパラチュンが必要です。
>    - 右に写っていたものが左に写っているのは、rvizの設定の問題です。
>
> すいません。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/501#issuecomment-101703028>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/7629149/674cdf44-fa65-11e4-803e-87fd747b1726.png)
I'd like to make applyed mask image to have no holes.

**Comment by aginika** [comment]
穴ができてしまうのはkinect2_bridgeから出てる時点でそうみたいですね。
さっき @wkentaro が入っていたように囲まれている領域をつぶすnodeletを作った方がいいかもしれません。

**Comment by wkentaro** [comment]
Closingがいいでしょうか？

2015年5月15日金曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 穴ができてしまうのはkinect2_bridgeから出てる時点でそうみたいですね。
> さっき @wkentaro <https://github.com/wkentaro>
> が入っていたように囲まれている領域をつぶすnodeletを作った方がいいかもしれません。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/501#issuecomment-102070333>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
とりあえずClosingでやってみるのでいいと思います。

**Comment by wkentaro** [comment]
今もerode dilate を組み合わせているのでほぼ同じ操作ですが、
両方のparamがまちまちにはなっているので、
closingの一操作のparam調整してみます。

**Comment by wkentaro** [comment]
まだ左の部分が右に写っています。 2015-05-17 10:00- 実験

**Comment by wkentaro** [comment]
I adjusted the positions at
#562 
Please reopen this when you encounter this again.

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/7683386/bc13c1da-fdb9-11e4-8f18-55a71f2bc710.png)
