### ISSUE TITLE
HandCameraによる把持検出

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#505]
**TODO**
* ノイズを除去するためにガウシアンをかける。
* Kmeansクラスタリングを行う。

**Comment by k-okada** [comment]
Handカメラの画像を添付しておいて下さい．どのぐらいのノイズが有るかみたいです．

**Comment by wkentaro** [comment]
動画で見たほうが分かりやすいと思います
https://drive.google.com/open?id=0B9P1L--7Wd2vT2VuN2FOc0t1UGs&authuser=1

**Comment by wkentaro** [comment]
今日やった感じだと、大きい物掴んでいれば機能する感じはします。
ただ、小さい物体だと、揺れの分の誤差分に入ってしまいがちです。

**Comment by wkentaro** [comment]
championだけの時はとれるように調整しました。
https://github.com/start-jsk/2014-semi/pull/767
