### ISSUE TITLE
baxter のeusモデルの腕が６自由度だったのを７にする

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2014-semi#51]
https://github.com/jsk-ros-pkg/jsk_robot/pull/170
で直しました．また関節の名前が今まで
shoulder-y, shoulde-p, elbow-r, elbow-p, wrist-r, wrist-p だったのを
shoulder-y, shoulder-p , shoulder-r, elbow-p, elbow-r, wrist-p, wrist-r に変更しました．

**Comment by wkentaro** [comment]
issueを閉じてもいいでしょうか。
