### ISSUE TITLE
吸引ハンドの連続吸引時間改善

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#513]
* ものを持った状態では3分程度

**Comment by aginika** [comment]
結局、大丈夫ということでしょうか？
様子見する方針でしょうか？

**Comment by wkentaro** [comment]
より大きな排熱機構をつけたいですが、
可能ですか？ @iory

2015年5月15日金曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 結局、大丈夫ということでしょうか？
> 様子見する方針でしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/513#issuecomment-102069820>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
今のところ、それほど連続吸引はしないので、closeします。
他のを優先的にやりましょう。

**Comment by aginika** [comment]
もし、ほんの少しでも止まる可能性があるのなら
それは限りなくゼロにしたいです。

詳しくなくて申し訳ないのですが、
スイッチを高価なものしても100Vの熱で落ちるものでしょうか？
本番は120Vですが、それでも今と同じ時間持つかも素人の自分には不安です。

和田くんからCPUファンの余りがあることを教えてもらったのですが、
それをつけるとより安定するでしょうか？

**Comment by iory** [comment]
単純にヒートシンクを大きくしたら稼働時間が３分に増えたので、CPUファンをつけたら改善する可能性はあると思います。
そこら辺を含めて急いで対処してみます。

**Comment by aginika** [comment]
右手：10分連続負荷を確かめました。

**Comment by aginika** [comment]
復帰までに17:03秒かかりました。

**Comment by wkentaro** [comment]
on/offのテストの仕方
```
for i in `seq 1 100`; do
    rostopic pub /vacuum_gripper/limb/left std_msgs/Bool 'data: 1' -1
    rostopic pub /vacuum_gripper/limb/left std_msgs/Bool 'data: 0' -1
done
```

**Comment by aginika** [comment]
ファンをつけたらもう一度耐久テストを行います。

**Comment by aginika** [comment]
ファンつけた時にオープンします。
