### ISSUE TITLE
statusをrvizに出す

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#536]

**Comment by aginika** [comment]
Please open when you want to add other information.

**Comment by wkentaro** [comment]
点数を出すのは、tweetするやつと同じようにpublishしておけばいいでしょうか。
それとも、スコアボードに出しましょうか。

2015年5月16日土曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> Please open when you want to add other information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/536#issuecomment-102632958>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
スコアボードは変える予定なので、とりあえず、対応しなくて大丈夫です。
