### ISSUE TITLE
本番直前のための動作チェックスクリプトの用意

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#540]

**Comment by wkentaro** [comment]
```
while [ 1 ] ; do rostopic echo /robot/state; sleep 1; done
```

**Comment by k-okada** [comment]
あとrosnode listして裏で上がっていないかも確認したいですね

2015年5月16日土曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> while [ 1 ] ; do rostopic echo /robot/state; sleep 1; done
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/540#issuecomment-102584529>
> .
>


-- 
--
◉ Kei Okada

**Comment by aginika** [comment]
```
watch rostopic echo /robot/state;
```

**Comment by k-okada** [comment]
1) baxter.launchをあげてもいいかの確認
- [ ] /robot/state　が来ていること
- [ ] うらでbaxter.launchが走っていないこと

2) challenge.launch を上げてもいいかの確認
- [ ] JointTrajectoryAction
- [ ] Kinectカメラ
- [ ] Handカメラ

参考：https://github.com/jsk-ros-pkg/trans_system/blob/master/jaxon_ros_bridge/scripts/check_jaxon_sanity.py
https://github.com/jsk-ros-pkg/trans_system/pull/264

**Comment by aginika** [comment]
ありがとうございます。
それらの確認するscriptを書きます。

**Comment by wkentaro** [comment]
arduinoの右手と左手が逆についていないか確認したい。
（抜き差しが多くなると、左右逆につけてしまう可能性もあると思います。）
（2015-05-17 10:00-) の実験で発生)

**Comment by aginika** [comment]
@wkentaro 何かparamter等で確認する必要のあることはありますか？

**Comment by aginika** [comment]
@wkentaro arduinoに関してはbaxter.launchやchallenge.launchが立ち上がっている状態でないと無理でしょうか？

そうすると、このスクリプトは、baxter.launchもchallenge.launchも全くない状態からやるべきものなので、
このスクリプトとは別に用意する必要がありそうです。

**Comment by wkentaro** [comment]
あと、binの位置調整ですが、それぞれのモーションがうまく行くことを確認する必要があるので、そのチェックスクリプトも必要ですね。 > @wkentaro

**Comment by aginika** [comment]
@k-okada handカメラはそもそもnodeを立ち上げてないです。
