### ISSUE TITLE
練習する

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2014-semi#541]
| 時間        | order   | 得点 |正解|失敗|違反| 時間  | 担当       | 備考    　　　　　　　     　　　　　　　|
|------------:|:--------|:-----|---:|---:|---:|:------|:-----------|:-----------------------------------------|
|  16 日15:00 |  A      |  40/186  | 7  | 1  | 3  | 19:11 | @k-okada   |  #543(HighLandを掴んでいるけどつかんでいないという）,  ~~#544（吸盤が取れる）~~ , ~~#545（シリアルポートからデータが取れない）~~, #540（チェックスクリプト）   |
|       18:00 |  B      |   70   |  5  | 0 |  1  |  16:03  | @aginika   |   ~~#545(serialが停止して試合終了)~~, #550(return-objectでふりふり落https://github.com/start-jsk/2014-semi/issues/634とせず), #551(return-object時の把持物体の落下) , #https://github.com/start-jsk/2014-semi/issues/544#issuecomment-102611265 (結束帯の付け方によってグリッパがななめになってしまい大失敗) |
|  17 日10:00 |  C      |   69/199   |  6  |  1  | 2   |  16:39   | @wkentaro     | https://github.com/start-jsk/2014-semi/issues/281#issuecomment-102749406 ( 掃除機を引きずり出してしまう), ~~https://github.com/start-jsk/2014-semi/issues/545#issuecomment-102736685 (serialが停止して試合終了)~~, https://github.com/start-jsk/2014-semi/issues/551#issuecomment-102733000 (genuinが戻せない), https://github.com/start-jsk/2014-semi/issues/501#issuecomment-102733020 (セグメント失敗) |
|       15:00 |  B      |      |    |    |    |       | @iory      |     |
|       18:00 |  D     |   0(-27)   |  0  |  1  |  2  |   13:50    | @aginika   |   #570(エラーにより停止),   https://github.com/start-jsk/2014-semi/issues/544#issuecomment-102798641 (グリッパが斜めについてちゃんととれない), https://github.com/start-jsk/2014-semi/issues/551#issuecomment-102797427 (return時に失敗)|
|        22:00 |  D      |   69/194   |    |    |    |   18:24    | @aginika    |  https://github.com/start-jsk/2014-semi/issues/341#issuecomment-102825067 (ブラシを取ったつもりで空振り 1:40秒) https://github.com/start-jsk/2014-semi/issues/27#issuecomment-102825327 (twitterの写真取るのが遅い)  #575 (前半5:23/ 10:57.掃除機の稼働中に動作が遷移&落下) #578 (7:30 genuineが中途半端把持になり失敗) 謎の失敗(9:31秒) #586 #577  (left verifacationが途中で死亡) #574 (11:04 / 後半1/26 return-objectの距離短く再把持) https://github.com/start-jsk/2014-semi/issues/551#issuecomment-102797427 (後半2:25 IKが解けずIのreturn-objectで死亡) #544 (グリッパの頻繁なずれの問題)|
|  18 日10:00 |  B      |      |    |    |    |       | @k-okada   |     |
|       15:00 |  E      |   -7/188   | 4   |  5  |  1  |       | @wkentaro   | https://github.com/start-jsk/2014-semi/issues/602 (Eの棚のpick), https://github.com/start-jsk/2014-semi/issues/604 (判別回数), https://github.com/start-jsk/2014-semi/issues/601 (hand camera認識), https://github.com/start-jsk/2014-semi/issues/603 (first_yearを落とす), #544 (グリッパの頻繁なずれの問題)  |
|       18:46 |  F      |  120/188    |    |    |    |   15:00  | @iory   |~~ #545(シリアルポートのエラーが依然出るが、止まらずに最後まで行った) ~~, highlandをすってとったが、箱を出るときに微妙な段差で躓いて離してしまった。|
|  19 日13:00 |  G      |   no rate   |    |    |    |      | @iory      |   https://github.com/start-jsk/2014-semi/issues/617 交差して落ちる. このあと落としてobject verificationで止まってしまった.  https://github.com/start-jsk/2014-semi/issues/310 右手のグリッパーがとれる　|
|       15:00 |  I     |   -41/188   | 2  | 2 | 5 |   19:00    | @wkentaro  |  https://github.com/start-jsk/2014-semi/issues/636, https://github.com/start-jsk/2014-semi/issues/635, https://github.com/start-jsk/2014-semi/issues/634,  新しいグリッパーでは落とすことが多い.. |
|       18:00 |  A      |      |    |    |    |       | @k-okada   |     |
|  20 日10:00 |  B      |      |    |    |    |       | @aginika   |     |
|       16:00 |  C      |   30/186   | 3  |  0  | 4   | 10:00    | @wkentaro   |  落とすことが多い、立てかけてあるものがとれない  |
|       18:00 |  A      |      |    |    |    |       | @iory      |     |
|  21 日10:00 |  H      |    69/186  | 6   |  1  | 2   |   13:00    | @wkentaro  | https://github.com/start-jsk/2014-semi/issues/603#issuecomment-104092860, https://github.com/start-jsk/2014-semi/issues/689, https://github.com/start-jsk/2014-semi/issues/688, https://github.com/start-jsk/2014-semi/issues/687     |
|       19:02 |  I      |   37   |    |    |    |       | @k-okada   |   次回までに，#703 と#704 をやりpick-objectでつかめないという状況を少なくする． |
|       23:09 |  A      |  52/188    |  5  |  1  |  1  |    20:00   | @k-okada   | #706を試した。使い方は#704, Kが取れるまで調整してテスト実行。ただし、CとJで失敗。次はK,C,Jでとれるまで調整が必要。    |
|  22 日 6:00 |  I      |  30/180    |  4 |  1  | 2   |  20:00     | @iory   | #670 と https://github.com/start-jsk/2014-semi/pull/721 の試験, #722 カラフルな球がとっているのにとれてないという問題  |
|       15:00 |  C      |    69/190 |  6  |  0  |  1  |   20:00    | @aginika      |     |
|       18:00 |  A      |      |    |    |    |       | @wkentaro  |     |

- プログラムの動かし方 
|  17 日10:00 |  C      |   69/199   |  6  |  1  | 2   |  16:39   | @wkentaro     | https://github.com/start-jsk/2014-semi/issues/281#issuecomment-102749406 ( 掃除機を引きずり出してしまう), https://github.com/start-jsk/2014-semi/issues/545#issueco
```
sudo pkill mongod
roslaunch jsk_2014_picking_challenge baxter.launch 
roslaunch jsk_2014_picking_challenge setup.launch
roslaunch jsk_2014_picking_challenge main.launch json:=`rospack find jsk_2014_picking_challenge`/data/apc-h.json
```

- 新しいapc.jsonの作り方
```
roscd jsk_2014_picking_challenge/scripts
./interface_generator.py
cp apc.json ../data/apc-*.json
```
apc-*は適宜適切なアルファベットにしましょう。setup.launchの引数も適切に変えましょう。
また、実験をするときは棚全体の物体のおき方が見えるように写真をとりましょう。
新しく生成したjsonは`git commit`しましょう。

- ビンの並べ方
 - A(186点満点）: https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/data/apc-a.json
- 得点の確認法
 - `rosrun jsk_2014_picking_challenge score_calculator.py`を実行すべし(最後に出る満点と点数を控える)
- 正解：オーダ通りのものを掴んでオーダビンに入れたものの個数（すべて正解）
- 失敗：オーダとは違うものでオーダビンに入れたものの個数（認識がミス）
- 違反：ものを落としたり壊したりしたものの個数（つかみ, 把持認識ミス）
- 16 - (正解 + 失敗 + 違反) 把持に失敗したもの数

**Comment by aginika** [comment]
稲垣です。通します。以下の写真の状況です。
![image](https://cloud.githubusercontent.com/assets/3803922/7665823/3a632e5c-fc04-11e4-96fd-ad0385a5655a.jpg)

**Comment by m1a1k0o** [comment]
申し訳ございません。
明日は私用で研究室に行くことが出来ません。
月曜日にいろいろ教えていただきながらやりたいと思っています。

**Comment by wkentaro** [comment]
明日は僕も18:30に帰らなければならないので、18時の回は出られないです。
そのため朝の杉浦さんの代わりをやります。

2015年5月16日土曜日、Makoto Sugiura<notifications@github.com>さんは書きました:

> 申し訳ございません。
> 明日は私用で研究室に行くことが出来ません。
> 月曜日にいろいろ教えていただきながらやりたいと思っています。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/541#issuecomment-102633493>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
僕がやります。

**Comment by m1a1k0o** [comment]
すみません。
よろしくおねがいします。

**Comment by wkentaro** [comment]
apc-c.jsonで実験します。
![2015-05-17 10 51 43](https://cloud.githubusercontent.com/assets/4310419/7668742/8ca6be3e-fc83-11e4-902a-1509ca113f39.jpg)

**Comment by iory** [comment]
１５時の回には所要で出られないので後の時間に戻ってやります。

**Comment by aginika** [comment]
apc-d開始します。
![image](https://cloud.githubusercontent.com/assets/3803922/7670108/b0296e12-fcd1-11e4-8515-4307aee83c04.jpg)

**Comment by aginika** [comment]
apd-dの２度目のチャレンジを行います。
![img_4530](https://cloud.githubusercontent.com/assets/3803922/7670669/c3efcc04-fce8-11e4-969a-e888b7803d6b.JPG)

**Comment by aginika** [comment]
上に `新しいapc.jsonの作り方`を追加しました。知らない人お読みください。

**Comment by wkentaro** [comment]
今日の10時から岡田先生になっていますが、僕は2限があるので、今日は12時過ぎに研究室へ行きます。

2015年5月18日月曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 上に 新しいapc.jsonの作り方を追加しました。知らない人お読みください。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/541#issuecomment-102832208>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
Bで並べましたが，得点の数え方とかわからないので，分かる人が来てから始めようと思います．
https://github.com/start-jsk/2014-semi/issues/27#issuecomment-102825327 は
https://github.com/start-jsk/2014-semi/pull/591
でたいおうしました．まだ，shetaのdevelopにはいれていないので，やる前にマージする必要が有ります．

**Comment by wkentaro** [comment]
apc-e.json
![2015-05-18 16 27 24](https://cloud.githubusercontent.com/assets/4310419/7677846/87f398d2-fd8a-11e4-9022-9fb8ef77e86b.jpg)

**Comment by iory** [comment]
今日の１０時からですが、少し時間をずらして午後の１時から行います

**Comment by iory** [comment]
no rate でしたがGの回の画像です。
![2015-05-19 13 21 44_mini](https://cloud.githubusercontent.com/assets/4690682/7695593/bbe4a59e-fe2c-11e4-859a-3b8a2859ea66.jpg)

**Comment by wkentaro** [comment]
Gというのはapc-g.jsonということですか？
PRを送っておいてください。

**Comment by wkentaro** [comment]
![2015-05-19 19 19 07](https://cloud.githubusercontent.com/assets/4310419/7702441/13b8e6d4-fe6b-11e4-88a5-fc9bad43de7e.jpg)

**Comment by aginika** [comment]
10:30くらいに始めます。

**Comment by aginika** [comment]
![image](https://cloud.githubusercontent.com/assets/3803922/7717476/0219ef96-fedd-11e4-96c4-a5e38ee47923.jpg)

**Comment by wkentaro** [comment]
Hです。
今から始めます。
![image](https://cloud.githubusercontent.com/assets/4310419/7720682/2313c59a-ff0b-11e4-8b1b-c0435e3a11e2.jpg)

**Comment by aginika** [comment]
apc-i again
![image](https://cloud.githubusercontent.com/assets/3803922/7743724/5c13bf94-ffd8-11e4-9b71-e013b7266445.jpg)

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/7770634/9c7d588a-00cb-11e5-83b1-3a7e007d5a93.jpg)

**Comment by wkentaro** [comment]
今日は眼科によっていくので、少し13時前くらいになると思います。

**Comment by aginika** [comment]
僕も13時過ぎに着きます

**Comment by aginika** [comment]
最近いろいろ変更があったと思うので、
全体を試せるとうれしいです。

**Comment by wkentaro** [comment]
準備に結構時間がかかり、14時半くらいに研究室へつくことになりそうです。

2015年5月24日日曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 最近いろいろ変更があったと思うので、
> 全体を試せるとうれしいです。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/541#issuecomment-104978078>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
僕も過ぎます。

**Comment by aginika** [comment]
あとは本番のみとなったため、closeしようと思います。
