### ISSUE TITLE
HighLand を持っているのに、持っていないと言われる

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#543]
https://github.com/start-jsk/2014-semi/issues/505
で対応しようとしている。

**Comment by aginika** [comment]
単体でテストしてみてもいいかもしれませんね.

**Comment by aginika** [comment]
これはどうなったのでしょうか？

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/666
で直しました。
左手も右手のカメラを見ていたのが原因でした。
