### ISSUE TITLE
吸盤が外れてしまう

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#544]
@m1a1k0o に靴下のような形状をお願いしています。

**Comment by wkentaro** [comment]
とりあえず今のものは結束帯で固めました。

**Comment by iory** [comment]
アロンアルファとかで止めるとかはしないんですかね
最終的に取れないように固めてしまっていいかもしれないです

**Comment by wkentaro** [comment]
結束帯は付けない方が良さそうです。

**Comment by aginika** [comment]
![img_4513](https://cloud.githubusercontent.com/assets/3803922/7666089/2317969a-fc11-11e4-8e9c-9425c41ac4a3.JPG)

**Comment by k-okada** [comment]
ううう，ごめんなさい．
靴下が来るまでは
- テープで止める
- 接着剤で付ける
で対応でしょうか．．．

**Comment by m1a1k0o** [comment]
靴下バージョンができるのは月曜日以降になってしまいそうです。

接着剤で固定するのはあまりよくないのではないかと考えています。
接着剤で固定すると接着剤がついた部分は固まってしまいゴムが硬くなってものにぶつかったときの柔軟な変形がなくなってしまう可能性があります。
また、接着剤でしっかり固定できるかもわかりません。

テープで固定するほうがいいかとは思いますがしっかり固定できるかはわかりません。

**Comment by aginika** [comment]
今回のテストランでは結束帯を外して実験しました。

外れることはなかったですが、抑えるものが何もないため、
傾いてしまっていました。
実験前につけたものと実験後の状態を貼っておきます。

**Comment by aginika** [comment]
実験前
![img_4516](https://cloud.githubusercontent.com/assets/3803922/7670333/db728ba8-fcdb-11e4-882c-6885a0fa566c.JPG)
![img_4517](https://cloud.githubusercontent.com/assets/3803922/7670332/db7061de-fcdb-11e4-9c82-849a211f3ca7.JPG)

**Comment by aginika** [comment]
実験後
![img_4524](https://cloud.githubusercontent.com/assets/3803922/7670336/e96256a8-fcdb-11e4-9a4d-dc83c32401d9.JPG)
![img_4525](https://cloud.githubusercontent.com/assets/3803922/7670335/e961c346-fcdb-11e4-8b8e-bf2b098d7f81.JPG)

**Comment by aginika** [comment]
付け方に問題があるのかもしれません。
結束帯とは別の理由でずれてしまいます。

**Comment by aginika** [comment]
リベンジでも同様な形になってしまいます。
おそらくこの付け方に問題があるので、ひっかかる形にしたいとおもいます。

**Comment by aginika** [comment]
@m1a1k0o 
閉めると形が崩れ閉めないとずれていき、結束対で固定しようとしてもずれていってしまうので、
メカ的に吸盤先の水平を担保したいです。

長靴下とは別の案なのですが、
以下のようにlongのほうと吸盤の方両方とも変形してとれにくくまた形が崩れにくくすることは可能でしょうか？
ゴムの液体って下のほうに柔らかいやつを入れて、上のほうを固い液体を流し込むってことは可能でしょうか？

**Comment by aginika** [comment]
長靴下により外れなくなりました。
ただ使用回数に限度がありそうです。
この問題は解決したものと思われますので、closeします。
