### ISSUE TITLE
把持検出の問題: シリアルポートからデータを受け取れないことがある

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#545]
```
[WARN] [WallTime: 1431763466.278169] Serial Port read returned short (expected 1 bytes, received 0 instead).
[WARN] [WallTime: 1431763466.278511] Serial Port read returned short (expected 2 bytes, received 0 instead).
[WARN] [WallTime: 1431763466.278772] Serial Port read failure: 
[WARN] [WallTime: 1431763466.279059] Serial Port read failure: 
[INFO] [WallTime: 1431763466.279386] Packet Failed :  Failed t
```

**Comment by wkentaro** [comment]
掴んでいても、/gripper_grabbed/limb/left/stateがfalseだったりします。

**Comment by k-okada** [comment]
最初はいいんだけど10分ぐらいすると起こるようです

**Comment by iory** [comment]
これ何が原因なんでしょう？
とりあえずarduinoのコードをdelay(100)で待つようにはしました

**Comment by iory** [comment]
早すぎが原因なんですかね
これで運用してみます。
https://github.com/start-jsk/2014-semi/pull/548

**Comment by aginika** [comment]
今回は１６分稼働していたら止まってしまいました。

**Comment by iory** [comment]
baud rateがおかしいのかもしれないです

**Comment by iory** [comment]
rosserial.launchの中を
'''
<node pkg="rosserial_python" type="serial_node.py" name="serial_node">
    <param name="port" value="/dev/ttyUSB0" />
    <param name="baud" value="57600" />
</node>
'''
に変更してみました。
これでもう一度やってみましょう

**Comment by iory** [comment]
delayを増やしてdelay(1000)にしたら出なくなりました。
一応最新のrosserial_python ではいままでqueue_sizeの指定がなかったのが,  10と指定されています。
https://github.com/ros-drivers/rosserial/commit/f830a3e722b7df5d5337b1c1b1d028acbb48f9a3

**Comment by wkentaro** [comment]
了解です。
また明日のテストで出たらopenしましょう。

**Comment by k-okada** [comment]
ちょっと怖いですね．

57600で100hz
で，std_msgs/Boolだけ，というのはそれほど多くないきがするので，1000までにしなくても動く気はします．なにかおかしいのかな．
rosserialとして，あまりテストされていなさそうな項目としては

- ボードを２つつける (両方の基板とも共読めなくなっていますか）
- メッセージが２つくる(ON/OFFも読めないですよね？）

でしょうか．ボードが２つは必須なんだっけ？

時間があれば，delayを10ぐらいにして，
https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/launch/rosserial.launch
だけ立ち上げて２０分ぐらい動作させて，最初にserial read failureがでる前後のメッセージを見たいところです．


queueサイズは rosserial_python -> 他のrosノードの通信で，今回問題なのは
arduino -> rosseril_pythonの通信なので，チョット違うかもです．



--
◉ Kei Okada

**Comment by aginika** [comment]
もう一つのPCが使えるようになれば、そちらにrosserial使うことも可能かもしれません

**Comment by wkentaro** [comment]
arduinoに書き込んでいるソースのApiはちょっと古いのかもしれませんが、queue_sizeを書き込んであるコードでも指定すべきなのではないでしょうか。
rosserial_pythonのqueue_size方は関係ないかもですが、書き込んである方がもし0がデフォルトとかになっていると無限に出そうとして詰まったという可能性はあると思います。


2015年5月17日日曜日、Kei Okada<notifications@github.com>さんは書きました:

> ちょっと怖いですね．
>
> 57600で100hz
> で，std_msgs/Boolだけ，というのはそれほど多くないきがするので，1000までにしなくても動く気はします．なにかおかしいのかな．
> rosserialとして，あまりテストされていなさそうな項目としては
>
> - ボードを２つつける (両方の基板とも共読めなくなっていますか）
> - メッセージが２つくる(ON/OFFも読めないですよね？）
>
> でしょうか．ボードが２つは必須なんだっけ？
>
> 時間があれば，delayを10ぐらいにして，
>
> https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/launch/rosserial.launch
> だけ立ち上げて２０分ぐらい動作させて，最初にserial read failureがでる前後のメッセージを見たいところです．
>
>
> queueサイズは rosserial_python -> 他のrosノードの通信で，今回問題なのは
> arduino -> rosseril_pythonの通信なので，チョット違うかもです．
>
>
>
> --
> ◉ Kei Okada
>
>
> On Sat, May 16, 2015 at 11:35 PM, ioryz <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > delayを増やしてdelay(1000)にしたら出なくなりました。
> > 一応最新のrosserial_python ではいままでqueue_sizeの指定がなかったのが, 10と指定されています。
> > ros-drivers/rosserial@f830a3e
> > <
> https://github.com/ros-drivers/rosserial/commit/f830a3e722b7df5d5337b1c1b1d028acbb48f9a3>
>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/start-jsk/2014-semi/issues/545#issuecomment-102632853>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/545#issuecomment-102637461>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
左手が反応しなくなりました。
スイッチだとついていたので、rosserialの問題かと思います。
エラーは出ていなかったですが、rosserial.launchを立ち上げ直すとつきました。

**Comment by wkentaro** [comment]
src内にrosserialがありますが、これは必要ですか？ @iory

**Comment by iory** [comment]
いらないです。

**Comment by wkentaro** [comment]
Please remove it > @iory

**Comment by iory** [comment]
where is src? > @wkentaro

**Comment by wkentaro** [comment]
sheetaに入れてなかった？

2015年5月18日月曜日、ioryz<notifications@github.com>さんは書きました:

> where is src? > @wkentaro <https://github.com/wkentaro>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/545#issuecomment-102945570>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by iory** [comment]
I got it

**Comment by iory** [comment]
やはりserial portのエラーが出るようです。


[WARN] [WallTime: 1431941925.286472] Serial Port read returned short (expected 2 bytes, received 1 instead).
[WARN] [WallTime: 1431941925.288353] Serial Port read failure: 
[INFO] [WallTime: 1431941925.308679] Setup publisher on /vacuum_gripper/limb/left/state [std_msgs/String]
[INFO] [WallTime: 1431941925.316867] Setup publisher on /gripper_grabbed/limb/left/state [std_msgs/Bool]

[WARN] [WallTime: 1431942170.995069] Serial Port read returned short (expected 6 bytes, received 0 instead).
[WARN] [WallTime: 1431942170.995957] Serial Port read failure: 
[INFO] [WallTime: 1431942171.016530] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1431942171.017022] msg len is 1
[INFO] [WallTime: 1431942171.038790] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431942171.046704] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431942253.636532] Serial Port read returned short (expected 7 bytes, received 3 instead).
[WARN] [WallTime: 1431942253.637574] Serial Port read failure: 
[INFO] [WallTime: 1431942253.638656] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1431942253.639329] msg len is 1
[INFO] [WallTime: 1431942253.659271] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431942253.667102] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431942392.538156] Serial Port read returned short (expected 6 bytes, received 4 instead).
[WARN] [WallTime: 1431942392.538641] Serial Port read failure: 
[INFO] [WallTime: 1431942392.538958] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1431942392.539128] msg len is 1
[INFO] [WallTime: 1431942392.559971] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431942392.569055] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431942440.418753] Serial Port read returned short (expected 2 bytes, received 0 instead).
[WARN] [WallTime: 1431942440.419473] Serial Port read failure: 
[INFO] [WallTime: 1431942440.441478] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431942440.450574] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431942484.229248] Serial Port read returned short (expected 2 bytes, received 1 instead).
[WARN] [WallTime: 1431942484.230474] Serial Port read failure: 
[INFO] [WallTime: 1431942484.250837] Setup publisher on /vacuum_gripper/limb/left/state [std_msgs/String]
[INFO] [WallTime: 1431942484.259902] Setup publisher on /gripper_grabbed/limb/left/state [std_msgs/Bool]
[WARN] [WallTime: 1431942509.425635] Serial Port read returned short (expected 1 bytes, received 0 instead).
[WARN] [WallTime: 1431942509.426533] Serial Port read failure: 
[INFO] [WallTime: 1431942509.449413] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431942509.457126] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431942512.525411] Serial Port read returned short (expected 7 bytes, received 5 instead).
[WARN] [WallTime: 1431942512.525982] Serial Port read failure: 
[INFO] [WallTime: 1431942512.526783] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1431942512.527295] msg len is 1
[INFO] [WallTime: 1431942512.547179] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431942512.558462] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431942829.709172] Serial Port read returned short (expected 2 bytes, received 0 instead).
[WARN] [WallTime: 1431942829.709294] Serial Port read returned short (expected 1 bytes, received 0 instead).
[WARN] [WallTime: 1431942829.709720] Serial Port read failure: 
[WARN] [WallTime: 1431942829.709746] Serial Port read failure: 
[INFO] [WallTime: 1431942829.710237] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1431942829.710506] msg len is 7
[INFO] [WallTime: 1431942829.730190] Setup publisher on /vacuum_gripper/limb/left/state [std_msgs/String]
[INFO] [WallTime: 1431942829.734691] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431942829.738033] Setup publisher on /gripper_grabbed/limb/left/state [std_msgs/Bool]
[INFO] [WallTime: 1431942829.740379] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431942884.040709] Serial Port read returned short (expected 7 bytes, received 4 instead).
[WARN] [WallTime: 1431942884.041689] Serial Port read failure: 
[INFO] [WallTime: 1431942884.042406] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1431942884.043138] msg len is 1
[INFO] [WallTime: 1431942884.063087] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431942884.071206] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431943180.747368] Serial Port read returned short (expected 6 bytes, received 2 instead).
[WARN] [WallTime: 1431943180.748140] Serial Port read failure: 
[INFO] [WallTime: 1431943180.748631] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1431943180.748922] msg len is 1
[INFO] [WallTime: 1431943180.770220] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431943180.777894] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431943183.802177] Serial Port read returned short (expected 6 bytes, received 1 instead).
[WARN] [WallTime: 1431943183.803409] Serial Port read failure: 
[INFO] [WallTime: 1431943183.804131] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1431943183.804561] msg len is 1
[INFO] [WallTime: 1431943183.824430] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431943183.833351] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]
[WARN] [WallTime: 1431943208.037830] Serial Port read returned short (expected 2 bytes, received 0 instead).
[WARN] [WallTime: 1431943208.039344] Serial Port read failure: 
[INFO] [WallTime: 1431943208.060176] Setup publisher on /vacuum_gripper/limb/right/state [std_msgs/String]
[INFO] [WallTime: 1431943208.069079] Setup publisher on /gripper_grabbed/limb/right/state [std_msgs/Bool]

**Comment by iory** [comment]
常にspinOnceをしてbufferを詰まらせないようにしました。
さっき、動かしてみたところpackage failedが出なかったので直ったのかもしれませんが、またエラーが出たら報告してください。
https://github.com/start-jsk/2014-semi/pull/607

**Comment by wkentaro** [comment]
１０分連続稼働でも起こらなくなったので、いったんcloseします。

**Comment by wkentaro** [comment]
またテスト中に起こったら開けてください。

**Comment by aginika** [comment]
test.sh １２分やりましたが、エラー分は一切ありません。
