### ISSUE TITLE
[robot_main] 並列が上手く行かないときがある

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#547]
ステータスの変わり目などでは並列ができなくなる

**Comment by aginika** [comment]
具体的にどのタイミングが知りたいですね。
apc-aの時に両手もpickし終わった後になりかけてたような気がします。

**Comment by wkentaro** [comment]
別のケースについては、テストの中で見つかったときに直していきたいですが、
現状のコードで並列できないケースとしては、右手がpick_object状態だけどwaitしていないときに、左手がpick_objectを始めてしまうということです。
これは、waitステータスを追加すれば解決できると考えています。

**Comment by wkentaro** [comment]
#564

**Comment by wkentaro** [comment]
直ったと思うので、次のテスト(apc-a.json)で検証してください。
