### ISSUE TITLE
return-objectのときに把持物体が棚にぶつかって

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#551]
落としてしまう。

**Comment by wkentaro** [comment]
どういう場合でしたか。
* 物体
* bin名
* 手を入れる時 or 手をbin前に持ってくる時

**Comment by wkentaro** [comment]
genuinをDに手を入れるときに落としてしまう

**Comment by aginika** [comment]
遅くなりました。
- 物品
 - kong_air_dog_squeakair_tennis_ball
- bin名
 - I
- タイミング
 - 手を入れるとき

**Comment by wkentaro** [comment]
ビデオ確認しました。
ありがとうございます。
ちなみにこれは、
kyjen_squeakin_eggs_plush_puppies
です。

**Comment by wkentaro** [comment]
binの口から離れた位置で上昇するように変更したので、落としにくくなったと思います。

**Comment by wkentaro** [comment]
また起こったらopenしてください.

**Comment by wkentaro** [comment]
I では上昇する部分のIKが解けないようで、returnに失敗します。

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/580
