### ISSUE TITLE
自分たちが想定ている商品単語名と主催者が思っているものの違いを確認する。

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#577]

**Comment by aginika** [comment]
@wkentaro 物品名がハードコーディグされているのは、object_listsのみでしょうか？interface_geneを除いて。

**Comment by wkentaro** [comment]
はい。実際にスクリプトなどで使われる名前はobject_list.ymlだけに書かれています。
判別でも使っていますが、インデックスは変更ないので問題ありません。

**Comment by aginika** [comment]
了解です。
では、直前にobject_list.yamlが正しいことだけをチェックするようにします。
In https://github.com/start-jsk/2014-semi/issues/293
