### ISSUE TITLE
再起動時のroscd, roslaunchが遅くなってしまう

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#599]
キャッシュを作っているのでしょうか？
これを設定で変更して頻繁に再起動しても問題ない様にしたいです。

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_common/issues/617#issuecomment-94166004

を試してみて下さい．

--
◉ Kei Okada


2015-05-18 17:15 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by wkentaro** [comment]
やりました。
また遅かったら開けてください。
