### ISSUE TITLE
first_yearsを落としてしまう

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#603]

**Comment by wkentaro** [comment]
グリッパーを変えても起こったら開けてください。

**Comment by wkentaro** [comment]
新しいグリッパーでいくつかの持ち方で試しましたが、落としていません。

**Comment by wkentaro** [comment]
グリッパーの編みを2cm奥につけてもらうことになりました。

**Comment by m1a1k0o** [comment]
網をずらしました。
造形の順番待ちがあるためできるのが遅くなりそうです。

![long2kai](https://cloud.githubusercontent.com/assets/11226577/7713972/3b928764-feb6-11e4-90e8-70f71717d30f.png)

**Comment by wkentaro** [comment]
championも落としてしまいますが、同様にグリッパーのこの変更で取れそうな感じでした。

**Comment by wkentaro** [comment]
この変更の前に、自分たちで切ってつけたりできないでしょうか。
@m1a1k0o

**Comment by aginika** [comment]
ずらしので試してみます。
開けたらオープンし直します。
