### ISSUE TITLE
rosbagを再生して認識のテスト

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#611]

**Comment by aginika** [comment]
これはどのようなissueなのでしょうか？

**Comment by wkentaro** [comment]
グリッパーをつけっぱなしにできないので、認識のテストにrosbagを使うということです。

**Comment by wkentaro** [comment]
大きめのファンがついたので、実際に手で持ってテストをしたいと思います。

**Comment by wkentaro** [comment]
Siftだけだと心もとないので色も使います。
See https://github.com/start-jsk/2014-semi/issues/768
