### ISSUE TITLE
商品が交差して落ちる

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#617]
２つの腕で同時に取るときに、片方の商品が大きかったりすると交差して落ちる場合があります。

![2015-05-19 13 32 16_mini](https://cloud.githubusercontent.com/assets/4690682/7695544/207c8324-fe2c-11e4-8741-02b130fa3f59.jpg)

**Comment by wkentaro** [comment]
左が真ん中の棚を目標にしている間は右は待つはずなのですが、どういう場合に起こりますか。

* 右のtarget bin
* 左のtarget bin
* 右のstate
* 左のstate

**Comment by wkentaro** [comment]
* 右手がI
* 左手がH
* 右手が2回目のPick
* 左手がPick

のときに起こるようです。

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/620

で待つときはホールドポーズになるようにしました。
