### ISSUE TITLE
ケースをつくる

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#621]
回路基板が危ないのでケースの作成を行います。

**Comment by iory** [comment]
https://github.com/start-jsk/2014-semi/issues/513
稼働時間に係る問題ですが、ケースにファンをつけようかと思います。

**Comment by iory** [comment]
ケース出来ました
![2015-05-20 02 26 11_mini](https://cloud.githubusercontent.com/assets/4690682/7711601/848aaf56-fea6-11e4-9187-733dd562d87d.jpg)

**Comment by aginika** [comment]
後はファンですね。

**Comment by iory** [comment]
即効でできる対策としてヒートシンクとトライアックの放熱部にシリコンを塗りました。
以前より密着度が上がったので放熱性は良くなったと思います。
あとはファンをつけます

**Comment by wkentaro** [comment]
かなり放熱性は良くなっていると感じました。
ファンお願いします。

**Comment by iory** [comment]
誰か１２Vの電源持ってませんか？

**Comment by k-okada** [comment]
あのファン，５Vではまわらないかな．

--
◉ Kei Okada

**Comment by iory** [comment]
上月さんから１２Vのファンをもらったのでそれを使おうかと思っていました。

**Comment by k-okada** [comment]
１２Vのファンに５Vつなげるとどうなるかな？

--
◉ Kei Okada

**Comment by iory** [comment]
ファンをとりつけました
