### ISSUE TITLE
以前より物を落とすようになっている気がする

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#651]
Genuineやアヒル、さまざまなものが落ちています。
吸盤のせいかもしれません。

**Comment by wkentaro** [comment]
今日中に
* 固めの吸盤
* 最新の柔らかい吸盤
のどちらを量産するか決定します。

**Comment by wkentaro** [comment]
柔らかめで本番に臨もうと思います。

**Comment by aginika** [comment]
吸盤の周りに
エリザベスカラーのようなものを周りにつけるのはどうでしょうか？

**Comment by k-okada** [comment]
買ってきてみてください

2015年5月21日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 吸盤の周りに
> エリザベスカラーのようなものを周りにつけるのはどうでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/651#issuecomment-104108767>
> .
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
See: https://github.com/start-jsk/2014-semi/issues/603
