### ISSUE TITLE
ゴムがえぐれてしまう。

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#664]
やはり、長靴下はちゃんと表面ができているのですが、
棚とあたるとえぐれてしまうので、黒いのをまこうと思います。

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/7720006/d58e2fde-ff02-11e4-92ed-7dd381ec4f39.jpg)
巻きました。
