### ISSUE TITLE
無線の中継機として使う方法の手順を書いておいてもらえますか？

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#667]
資材集めが終わってからでいいと思いますが、
これを試したいのと手順を知りたいです。

**Comment by wkentaro** [comment]
@iory

**Comment by iory** [comment]
了解っす

**Comment by iory** [comment]
ここを見ればできると思います。
http://nw-knowledge.blogspot.jp/2015/02/buffalo-converter.html

**Comment by iory** [comment]
無線のipを192.168.11.200に変更しました
