### ISSUE TITLE
立てかけてあるものがとれない

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#670]

**Comment by iory** [comment]
作戦としては
pick-objectでたてかけてるものをうまくとれるようにするか
あえて最初にたてかけてあるものを倒してから、pick-objectの他のパターンで倒れたものをとるといいかなと思います

**Comment by iory** [comment]
#715 
でpick-object のパターンが増えていますが、本などはとれましたが、cheezitがうまくとれないので
rotate-wristの調整などもいると思います。

**Comment by iory** [comment]
パラメータを調整するのと、戦略として、
rotate-and-left/rightとしたあとに、とれればOKなのですが、取れなかった場合にも本などが倒れるので、
次の動作がleft/right-mostですぐに倒れたものを掴みにいくようにしました。
https://github.com/iory/2014-semi/commit/54523cb7c63bece987bac81e8a4af2c96dcac7bb
