### ISSUE TITLE
kinectは見えているけど、mask?は見えない

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#672]
みたいになっているのはどうしたら治りますか？また、チェックスクリプトでチェックできますか？

![screenshot from 2015-05-20 17 06 07](https://cloud.githubusercontent.com/assets/3803922/7721438/96da65d6-ff12-11e4-9bbc-faef1ebb5e9b.png)

**Comment by k-okada** [comment]
勘違いでした
