### ISSUE TITLE
認識のための画像が来ない

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#680]
verify_objectはtimeoutを20秒にしているのですが、結構頻繁にtimeoutします。

**Comment by wkentaro** [comment]
rosbagを取っていないと、起こっていないと思います。
verify_object内でtimotutをすると、error msgとして表示するように（前はwarn）したので、
テストの際に見ておいてください。
https://github.com/start-jsk/2014-semi/pull/679

**Comment by aginika** [comment]
それはすごくいい情報です。
念のためいくらかのプロセスをカットして軽くします。

**Comment by wkentaro** [comment]
@aginika 
によると、imagesiftもかなり重かったということです。
envを設定して対応していただけるとのこと。

**Comment by aginika** [comment]
With #696
