### ISSUE TITLE
できるだけ床につかないようにする

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#683]

**Comment by aginika** [comment]
ハードウェア的に担保するのは難しそうですが、思いつきたいです。

**Comment by iory** [comment]
https://github.com/start-jsk/2014-semi/pull/715
これで自動的に床につくぎりぎりを求めるようになりました

**Comment by iory** [comment]
次は棚の右左につかないようにします

**Comment by iory** [comment]
https://github.com/iory/2014-semi/blob/adjust-pick-object-from-wall/jsk_2014_picking_challenge/euslisp/robot-test.l#L196
テスト関数を作りましたがすべての箱をやると時間がかかりそうです

**Comment by k-okada** [comment]
何時間ぐらいかかるかな？

--
◉ Kei Okada

**Comment by iory** [comment]
一つのパターンをやるのに３分くらいかかるので、
あとはdepth(3パターン)とと箱の数(１２パターン)倍で
二時間くらいかかるのですが、こんなにやる必要があるかは微妙です。

**Comment by k-okada** [comment]
MAX２０分ぐらいだとして，どれだけやるか決めましょう．
右手と左手で４段で，並列でやるとして１２分にならないかな．

--
◉ Kei Okada


2015-05-23 14:28 GMT+09:00 ioryz <notifications@github.com>:

**Comment by iory** [comment]
両方同時に動かしてやってみれば、箱の数を減らせばそのくらいになれるかもしれないです
