### ISSUE TITLE
棚の設置の際に用いるテスト関数（pick_objectに関する）を作成する

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#684]
棚の位置調整の手順をここに書いてください。
z と depth1 の位置調整です。

**Comment by iory** [comment]
テストすることは
・ikが解けているか
・吸盤が床にはりつかないか

です。

**Comment by aginika** [comment]
棚との位置調整は、check_shelf_pos.pyで
そのあとにpick_objectのテストです。

**Comment by aginika** [comment]
これに対応するPRはありますか？

**Comment by iory** [comment]
diffが汚いですが
https://github.com/start-jsk/2014-semi/pull/721/
