### ISSUE TITLE
rviz で掴んだと認識しているか表示する

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#688]
テストの際にほしいです

**Comment by wkentaro** [comment]
時間も表示したいです

**Comment by aginika** [comment]
時間というは開始してからのですよね？

**Comment by wkentaro** [comment]
はい

2015年5月21日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> 時間というは開始してからのですよね？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/688#issuecomment-104091404>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
外部のvisualizationスクリプトを作って、パラメータ監視しておけばいいかと思いましたが、
面倒かもなので、vacuumだけでも大丈夫です。
（割と時間もないですし..)

**Comment by aginika** [comment]
#699
