### ISSUE TITLE
[announce] imageshiftのCPU使用率が100%だったので

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#692]
export OMP_NUM_THREADS=4にする設定を.bashrc と .zshrcに書いています。
4だと使用率226%でだいぶマシな気がします。

@k-okada .bashrcや.zshrcに書く以外に環境変数を設定するいい方法はありませんか？launchにかける方法があるといいのですが。。。paramのcommandとかでしょうか？

**Comment by k-okada** [comment]
envに書けばいいんじゃないかな．

--
◉ Kei Okada


2015-05-21 13:30 GMT+09:00 Yuto Inagaki <notifications@github.com>:

**Comment by k-okada** [comment]
launchの

--
◉ Kei Okada


2015-05-21 13:31 GMT+09:00 Kei Okada <k-okada@jsk.t.u-tokyo.ac.jp>:

**Comment by aginika** [comment]
before
![before](https://cloud.githubusercontent.com/assets/3803922/7741716/1b1560b6-ffbe-11e4-84d3-eff55e800d3a.png)
after
![after](https://cloud.githubusercontent.com/assets/3803922/7741717/1b16d77a-ffbe-11e4-9868-e004e05d9e74.png)

**Comment by aginika** [comment]
@k-okada できました。ありがとうございます。
