### ISSUE TITLE
[Suggestion] jsk_2014_picking_challenge/scriptsをPATHに加える

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#711]
楽にするためだけですが。
check_スクリプト系で毎回 rosrun jsk_2014_picking...とうつの大変かなと思いますが、どうでしょうか？

**Comment by wkentaro** [comment]
同感です。Path通させるようにお願いします。

**Comment by aginika** [comment]
とりあえず、.bashrc と .zshrcに加えました。
