### ISSUE TITLE
main.launchでいつyes_noを押していいのかわからない

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#713]
main.launchが待っている状態になったらコマンドに出してほしいです。

**Comment by wkentaro** [comment]
押したら直ぐに始まるようにしたいということでしょうか。
irtviewerが二つ立ち上がったらと考えていますが、rosinfoで出すようにします。
ちなみにボタンは押せるようになったらいつ押しても大丈夫です。

2015年5月21日木曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> main.launchが待っている状態になったらコマンドに出してほしいです。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/713>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by aginika** [comment]
>> 押したら直ぐに始まるようにしたいということでしょうか。
いや、main.launchを実行してどのくらいたったらやっていいのかわからなかったという感じです。

irtviewerが立ち上がったらの目安なのですね。
ros-infoお願いします。

**Comment by wkentaro** [comment]
PR
https://github.com/start-jsk/2014-semi/pull/726/
