### ISSUE TITLE
rqt yes no buttonが死ぬ

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#714]
何度かmain.launchを立ち上げ直したら治る？

**Comment by wkentaro** [comment]
テスト中もmain.launchを立ち上げるごとに3回に一回位死んでいたのですが、まだ原因はわかっていません。調べてみます。

**Comment by wkentaro** [comment]
https://github.com/jsk-ros-pkg/jsk_visualization/pull/405
で治ったと思います。
