### ISSUE TITLE
ものを戻すときに奥深くまで戻す

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#716]

**Comment by iory** [comment]
これをするときに他の商品を巻き込まないでうまく戻せるかが大事です。
案
一旦セーブポイント的な場所を用意しておいて、間違った商品はそこに一旦保留しておいて、正しいものをリリースできたら最後に箱の中に戻す

**Comment by aginika** [comment]
とったy座標を通るように戻すのが、最も簡易でしょうか？

**Comment by iory** [comment]
そうですね。
それが簡易な気がしますが、重なっているものがあるとそれがうまく行かないかもしれないです。

**Comment by aginika** [comment]
本以外は寄っ掛かることはないはずなのですが、
どういったものの重なりでしょうか？

**Comment by iory** [comment]
本などが倒れて他の小さいもの(鉛筆)などに重なる場合です。
（物体が最初から重なっていることってないんでしたっけ？）

**Comment by aginika** [comment]
小さいものや倒れた本なら上を通過すればぶつからない気もしますが、セーブポイントをやってみるのもいいかもしれません。pick-objectがかなり安定してできるようになったようでしたら、セーブポイントの箱？テーブルをぶつからない高さで作って、動作をつくってみるのもありかもです。

> （物体が最初から重なっていることってないんでしたっけ？）
ないです。本がよっかかるしかないはずです。y座標はそれ以外で重なりません。

**Comment by aginika** [comment]
これはどうなりましたか？ @iory

**Comment by iory** [comment]
セーブポイント用のスペースがないのでやりません。

**Comment by aginika** [comment]
今は深く戻すようになっている感じですか？確かそうだったと思ってるのですが、自信ないです。

**Comment by iory** [comment]
そうなってます

**Comment by iory** [comment]
簡易ですがこれで被らないように対応してみました
https://github.com/start-jsk/2014-semi/pull/786

**Comment by wkentaro** [comment]
これは、戻した物体をもう一度とってしまうことがあるという問題です。
二度目以降は奥までとりにいかないということで対応しましょう。
