### ISSUE TITLE
つかめているのに、つかめていない判定が出る。

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#722]
テスト中にeggs_plush_puppiesが箱の中で掴んでいそうなのに, つかんでいない判定が出ていました.
テスト終了後にこれだけ掴ませてみると,
```
/grabbed_gripper/limb/left/state
```
がFalseが返ってきていました. joke本などではTrueが帰ってきていたので, センサーの故障とかではないようです.
![2015-05-22 06 27 35_mini](https://cloud.githubusercontent.com/assets/4690682/7759630/12d20c66-004e-11e5-84a8-2bcd74f9da9e.jpg)

**Comment by k-okada** [comment]
ハンドの中の格子を置くに付けることで治る，とされています．新しいハンドはつくてもらっています．

**Comment by k-okada** [comment]
新しいハンドが来たら確認しましょう．

**Comment by aginika** [comment]
@iory 試しましたか？

**Comment by iory** [comment]
どっちにしろつかめていない時はつかめていない判定が来ます
