### ISSUE TITLE
move_to_target_binで真ん中の棚に対する動作が今までと異なる

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#725]

**Comment by wkentaro** [comment]
baxtereusの最新のものを使うか否かで異なります。

**Comment by aginika** [comment]
Move to target binno?

**Comment by wkentaro** [comment]
move_to_target_binで真ん中の棚に対する動作が今までと異なる

**Comment by aginika** [comment]
腕の起動が確かに異なっています。expandの影響？なのでしょうか
一部リミットが180と-180を超えているところがあったので、超えないようにしましたが、
効果はありませんでした。

**Comment by wkentaro** [comment]
https://github.com/start-jsk/2014-semi/pull/732
