### ISSUE TITLE
バックアップの掃除機もセットアップする

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2014-semi#735]
バックアップの掃除機、まだ開封していなければ開封してスペアの基盤を付けてテストしましょう

前はもっと吸引力有ったのになぁ、というのは
もしかしたら掃除機本体の吸引力が下がったのかも
しれません。

吸引力が下がらない掃除機は世界で一つしかないですからね

と、ふと思いました。

**Comment by aginika** [comment]
すべきですね。

もし低かったら新しいのを買ってもいいのでしょうか？

**Comment by k-okada** [comment]
必要なものは何でも買ってください

2015年5月22日金曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> すべきですね。
>
> もし低かったら新しいのを買ってもいいのでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/735#issuecomment-104667917>
> .
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
@iory 掃除機への基板をつけてもらえますか。

**Comment by iory** [comment]
backupの掃除機のセットアップも終わりました。
これで合計３台の掃除機が使えます。

あと掃除機のモータ用のケーブルも太くて丈夫なものに換装したので、前より良くなると思います。

![2015-05-23 10 14 56_mini](https://cloud.githubusercontent.com/assets/4690682/7781869/10167768-0135-11e5-9440-8ab1753dc9f9.jpg)

**Comment by aginika** [comment]
ないすです。
今日動作確認します

**Comment by aginika** [comment]
先程、手先を古いの新しいのに入れてみたり、おレオをもたせたりしましたが、
どちらも同じような気がします。
ので追加購入はいらないと考えています。
故障したときのためにもうひとつ買っておくのはありかもしれませんが。
