### ISSUE TITLE
黒い箱の鍵がない

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#751]

**Comment by k-okada** [comment]
わからないです
鍵はどうせ飛行機はずされるのでいいのでは？

--
◉ Kei Okada

2015/05/23 19:36、Yuto Inagaki <notifications@github.com> のメッセージ:

**Comment by k-okada** [comment]
とはいえ、あるとしたら箱のなかなんだけど
残っていないかな

--
◉ Kei Okada

2015/05/23 19:49、Kei Okada <kei.okada@gmail.com> のメッセージ:

**Comment by aginika** [comment]
見つけました。
Baxterの下に追っこってました。

**Comment by k-okada** [comment]
大丈夫だとおもうけど
鍵はせずに各自鍵を持っていきましょう
検査でなかを開けるけどその後かぎがしまることがあるらしい

2015年5月23日土曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> Closed #751 <https://github.com/start-jsk/2014-semi/issues/751>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/751#event-312294820>.
>


-- 
--
◉ Kei Okada
