### ISSUE TITLE
梱包材がない

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#752]
@k-okada 
荷物を入れるようの梱包材がないです。
どこか置いてある場所知っていますか？

**Comment by k-okada** [comment]
b1の上月君の机後ろの棚の一番うえにあるダンボールのなかかな

--
◉ Kei Okada

2015/05/23 19:39、ioryz <notifications@github.com> のメッセージ:

**Comment by iory** [comment]
袋に入った奴はないですか？

**Comment by k-okada** [comment]
あれは色々なとこからかき集めました
b2の昔の室岡君の机のうえにあるダンボールに断熱シートがあるからそれとか、
なかの梱包材の粒は大量にあるからコンビニ袋に入れるとか

2015年5月23日土曜日、ioryz<notifications@github.com>さんは書きました:

> 袋に入った奴はないですか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/752#issuecomment-104882186>
> .
>


-- 
--
◉ Kei Okada

**Comment by iory** [comment]
了解です。

**Comment by k-okada** [comment]
あとは自分の服を梱包材にしましょう

--
◉ Kei Okada

2015/05/23 20:05、ioryz <notifications@github.com> のメッセージ:

**Comment by aginika** [comment]
なんとか足りそうです。
