### ISSUE TITLE
Baxterを含む閉鎖的なローカルネットワークの構築方法がわからない。

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#759]
@k-okada 明日夕方ごろに、hubだけを使った方法をできるようにしてみたいのですが、
手伝っていただけないでしょうか？

**Comment by k-okada** [comment]
はい

でも、マシンの/etc/hostsにbaxterのipを書けばいいはずです

2015年5月23日土曜日、Yuto Inagaki<notifications@github.com>さんは書きました:

> @k-okada <https://github.com/k-okada> 明日夕方ごろに、hubだけを使った方法をできるようにしてみたいのですが、
> 手伝っていただけないでしょうか？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/759>.
>


-- 
--
◉ Kei Okada

**Comment by aginika** [comment]
ありがとうございます。

Baxterのipって僕らは設定できるのでしょうか？
それともdhcpはなかったときに自身で決定されるIPがあるのでしょうか?
本番はRethinkの人が設定してくれると言って頂いてるということは、
デフォルトゲートウェイとネットマスクを適当に共通化すればネットワークとしては
機能するのでしょうか？

**Comment by k-okada** [comment]
サービスメニューからやればIPをセットできるから研究室と同じものにしてもいいだろうけど
その場にあるロボットのIPと、僕たちがつかったらいいＩＰをおしえてもらえるとおもいます
なので、それで自分のマシンのＩＰを決めるんだと思います

--
◉ Kei Okada

2015/05/24 0:58、Yuto Inagaki <notifications@github.com> のメッセージ:

**Comment by aginika** [comment]
なるほど、了解です。ありがとうございます。

**Comment by aginika** [comment]
本番でよろしくお願いします。
