### ISSUE TITLE
変圧器が見当たらない

### ISSUE THREAD

**Issue by aginika** [start-jsk/2014-semi#760]

**Comment by aginika** [comment]
見つからなかったので買いましょう。
買いに行ける人いますか？

**Comment by wkentaro** [comment]
買いに行きます。

**Comment by wkentaro** [comment]
上野で買います。

**Comment by aginika** [comment]
ぎりぎりに乗ったため空港で買う時間がありませんでした。

**Comment by k-okada** [comment]
超過料金は大丈夫だったかな？

--
◉ Kei Okada

**Comment by aginika** [comment]
すべてのカバンで約1万円の追加料金を支払いました。
sheetsが32kg以上だったのですが、さらに一段階上の料金にはなりませんでした。

**Comment by wkentaro** [comment]
@k-okada
変圧器を買う時間がなかったのですが、買ってきていただくことは可能でしょうか。

On Sunday, May 24, 2015, Kei Okada <notifications@github.com> wrote:

> 超過料金は大丈夫だったかな？
>
> --
> ◉ Kei Okada
>
>
> On Mon, May 25, 2015 at 10:31 AM, Yuto Inagaki <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > ぎりぎりに乗ったため空港で買う時間がありませんでした。
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/start-jsk/2014-semi/issues/760#issuecomment-105084362>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/760#issuecomment-105093272>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
はい．買います．

--
◉ Kei Okada

**Comment by k-okada** [comment]
掃除機何wかな
変圧器max 270wのしかない


2015年5月25日月曜日、Kei Okada<k-okada@jsk.t.u-tokyo.ac.jp>さんは書きました:

> はい．買います．
>
> --
> ◉ Kei Okada
>
>
> On Mon, May 25, 2015 at 2:12 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> @k-okada
>> 変圧器を買う時間がなかったのですが、買ってきていただくことは可能でしょうか。
>>
>> On Sunday, May 24, 2015, Kei Okada <notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>>
>> > 超過料金は大丈夫だったかな？
>> >
>> > --
>> > ◉ Kei Okada
>> >
>> >
>> > On Mon, May 25, 2015 at 10:31 AM, Yuto Inagaki <
>> notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
>> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
>> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
>> > wrote:
>> >
>> > > ぎりぎりに乗ったため空港で買う時間がありませんでした。
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/start-jsk/2014-semi/issues/760#issuecomment-105084362>
>>
>> > > .
>> > >
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/start-jsk/2014-semi/issues/760#issuecomment-105093272>
>>
>> > .
>> >
>>
>>
>> --
>> 和田 健太郎 / Kentaro Wada
>> http://wkentaro.com <http://www.wkentaro.com>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/start-jsk/2014-semi/issues/760#issuecomment-105127775>
>> .
>>
>
>

-- 
--
◉ Kei Okada

**Comment by aginika** [comment]
1200Wみたいです。

**Comment by k-okada** [comment]
200wを買ったけど多分ダメだね

とりあえず一個繋げて爆発しないかテストしてダメならhomedepoで買ってくるのかな

--
◉ Kei Okada

2015/05/25 22:13、Yuto Inagaki <notifications@github.com> のメッセージ:

**Comment by wkentaro** [comment]
掃除機のテストを短時間ですが行いました。
電圧の許容範囲からおそらく競技中はいつも通り使えると思われます。
