### ISSUE TITLE
掃除機のモータが勝手に止まる

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#766]
今までトライアックが勝手に電気を止めるのかと思っていましたが、実は掃除機のモータ？が熱くなると勝手に止まることが分かりました。

**Comment by iory** [comment]
モータの中は見ていないのでわからないのですが、実は昔のこたつと同じでバイメタルみたいなものが入っていて熱くなると離れて電気的に絶縁されるとかになっているのかもしれません。

**Comment by k-okada** [comment]
うーん
これはしょうがないですね。
温度計と扇風機を持って行ってちゃん事前に冷やすしかないかねぇ。

--
◉ Kei Okada

2015/05/24 1:12、ioryz <notifications@github.com> のメッセージ:

**Comment by iory** [comment]
ドライアイスを箱の中に詰めて常に冷やそうという案もあります。
main.launchで練習している時に死ぬことはなかったので、よっぽど連続稼働しなければ大丈夫な気がします。
一応今日掃除機を買ってきて、モータを分解してみようかと思います。

**Comment by k-okada** [comment]
ドライアイスはかっこいいですね

首に巻くアイスノンみたいなのだとロスで再利用できるかもしれません
それか第一購買にあるみたいに氷をビニール袋に入れても良いかも。これなら現地調達できそう。

--
◉ Kei Okada

2015/05/24 2:37、ioryz <notifications@github.com> のメッセージ:

**Comment by iory** [comment]
ではそういう方針で行きます

**Comment by aginika** [comment]
掃除機は新しく買い換える必要があるのでしょうか？

**Comment by iory** [comment]
時間があったら買いに行きたいですが、いつ頃研究室きますか？

**Comment by aginika** [comment]
僕は3過ぎです。

**Comment by wkentaro** [comment]
robot-main.lが正常に動く限り、掃除機が死ぬことはないので、買わないことにします。
Closing.
