### ISSUE TITLE
Travisのテストが通らない

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#816]
https://github.com/start-jsk/2014-semi/pull/814
のように変更なしでPRを送っても通らなくなっています。
hydroでは
```
-- run_tests.py: verify result "/workspace/ros/ws_2014-semi/build/jsk_2014_picking_challenge/test_results/jsk_2014_picking_challenge/nosetests-test.test_robot_input.py.xml"


Built target _run_tests_jsk_2014_picking_challenge_nosetests_test.test_robot_input.py


Scanning dependencies of target _run_tests_jsk_2014_picking_challenge_nosetests


Built target _run_tests_jsk_2014_picking_challenge_nosetests


;; loading roseus("") on euslisp((9.12 host08.storm.ros.org Fri May 22 20:44:31 UTC 2015  1.0.6))


[ERROR] [1435037463.443262996]: Could not find roseus messages for pr2_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)


try rosrun roseus generate-all-msg-srv.sh pr2_msgs


[ERROR] [1435037463.443482127]: Could not find nil/manifest.l


try rosrun roseus generate-all-msg-srv.sh pr2_msgs


[ERROR] [1435037463.447848546]: Could not find roseus messages for pr2_controllers_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)


try rosrun roseus generate-all-msg-srv.sh pr2_controllers_msgs


[ERROR] [1435037463.448013096]: Could not find nil/manifest.l


try rosrun roseus generate-all-msg-srv.sh pr2_controllers_msgs


[ERROR] [1435037463.448171106]: Could not find roseus messages for control_msgs under (/workspace/ros/ws_2014-semi/devel/share/roseus/ros /workspace/ros/ws_2014-semi/devel/share/roseus/ros /opt/ros/indigo/share/roseus/ros)


try rosrun roseus generate-all-msg-srv.sh control_msgs


[ERROR] [1435037463.448298376]: Could not find nil/manifest.l


try rosrun roseus generate-all-msg-srv.sh control_msgs


/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl roseus-error: no such package CONTROL_MSGS in (apply #'ros::load-org-for-ros ros::fullname args), exitting...


testrobot_test ... FAILURE!


FAILURE: test [robot_test] did not generate test results


  File "/usr/lib/python2.7/unittest/case.py", line 331, in run


    testMethod()


  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 160, in fn


    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)


  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue


    raise self.failureException(msg)
```
と出ていても通っていたりします。

**Comment by wkentaro** [comment]
今まで通っていたのは、偶然というか、testが失敗してもSuccessになっていたからみたいです。

**Comment by k-okada** [comment]
これ，hydroだと，run_testsした時にちゃんとテスト結果のxmlファイルがかかれずに
https://github.com/jsk-ros-pkg/jsk_travis/blob/master/travis.sh#L152
で消していて無視していました．

多分ですが，
  # for test_results bug
  - (cd /opt/ros/$ROS_DISTRO/lib/python2.7/dist-packages; wget
--no-check-certificate
https://patch-diff.githubusercontent.com/raw/ros/ros/pull/82.diff -O - |
sudo patch -p4 )
  - (cd /opt/ros/$ROS_DISTRO/lib/python2.7/dist-packages; wget
--no-check-certificate
https://patch-diff.githubusercontent.com/raw/ros/ros_comm/pull/611.diff -O
- | sudo patch -f -p4 || echo "ok" )
  - (cd /opt/ros/hydro/share; wget --no-check-certificate
https://patch-diff.githubusercontent.com/raw/ros/ros_comm/pull/611.diff -O
- | sed s@.cmake.em@.cmake@ | sed 's@/${PROJECT_NAME}@@' | sed 's@
DEPENDENCIES ${_rostest_DEPENDENCIES})@)@' | sudo patch -f -p2 || echo "ok"
)
として，
  - catkin run_tests
  - catkin_test_results build
とするのが正解なきがします．

ただ，これは
https://github.com/jsk-ros-pkg/jsk_roseus/pull/319
で前はちゃんと全部ファイルが作られたけどできなくなってしまった，という問題だと思います．
ココを直さないとダメですね．

--
◉ Kei Okada

**Comment by wkentaro** [comment]
geneusかroseusのいつかの変更で作られなくなったと考えていいでしょうか。

https://github.com/jsk-ros-pkg/jsk_roseus/pull/319
をマージできるようにするのが最優先事項ということであっていますか？

**Comment by wkentaro** [comment]
ただ、indigoでも
https://github.com/start-jsk/2014-semi/pull/810
の時点では同じエラーが出ているのにsuccessになっているのは、原因がわかりませんね。

**Comment by k-okada** [comment]
はい．そうおもっています．


--
◉ Kei Okada


2015-07-03 19:03 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by k-okada** [comment]
エラーはでていて、そのエラーをキャッチできていないですね
run_testsはエラーがあってもexit statusが変わらなようです
catkin_results_tests
が必要です

2015年7月3日金曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> ただ、indigoでも
> #810 <https://github.com/start-jsk/2014-semi/pull/810>
> の時点では同じエラーが出ているのにsuccessになっているのは、原因がわかりませんね。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/816#issuecomment-118304807>
> .
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
indigoだとエラーとなっているのは、patchが反映されているからでしょうか。
https://github.com/jsk-ros-pkg/jsk_travis/pull/108
