### ISSUE TITLE
春季休業中の第一回MTGについて.

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#89]
2/13(金)にMTGをしようと話をしています。
（パターン情報学のレポート提出日のため、この日にしました。）
@jiangjun0105 もできれば参加してください。

#### MTGのアジェンダ
* 現状確認(15分程度): 提出した動画等はどうなったか。ゼミでやったことの確認。
* 今後の進め方(1時間程度): スケジュール、集まる頻度、役割など。
* 次回やること(15分程度): 次回集まった時のTodo。
* 次回までにやること(15分程度): 次回やることに向けた準備。

@k-okada できれば研究室で行いたいのですが、可能でしょうか？

@jiangjun0105 @iory @Tnoriaki @umoji 時間はいつ頃にしましょうか？
僕は13:45からでいいかなと考えているのですがどうでしょうか。
（事務室が開くのが13:30なので）

**Comment by jiangjun0105** [comment]
私はその日レポートを提出すること他に、なんの用事もないから、いつでもいいです。

**Comment by k-okada** [comment]
お，いいですね．
試験，レポートは全部終わったかな．研究室でOKです．

いくつかアップデート
- ビデオ審査は通って，物品がちょうど明日か明後日には届くというう連絡が有りました．
- ３月にもう一回ビデオ審査が有り，これに通らないと旅費が出ない
- baxterがindigoになりました

ぐらいかな．@aginikaも参加しましょう．

本番に向けて本気をだすようにするために，
- 基本的な動作生成法をmoveit + eus の構成にする．(ただしほとんどの状況でmoveitはdisableの可能性が高い）
-いくつかの基本動作を作る．（ものを箱に入れる，ものを掴んでいるか確認する．手をチョット降って物がおちないか調べる，持っているものを離して別のものをつかむ）
-認識プログラムを作る（http://rll.berkeley.edu/amazon_picking_challenge/) まずはimagesiftか


==
Dear APC Team,

Congratulations! Based on your equipment proposal video submission we have
decided your team has qualified to participate in the 2015 Amazon Picking
Challenge at ICRA. You do not need to send in any additional information to
qualify. If you decide you will not be participating in the challenge
please inform us via email.

We encourage you to submit an updated video application for travel support
in March, and look forward to seeing you there!

Sincerely,
Joe Romano
Research Scientist, Kiva Systems


--
◉ Kei Okada


2015-02-11 16:29 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
ありがとうございます。試験は終わりました。
レポートは金曜日が終われば自主プロの課題だけなので大丈夫かと思います。

ちなみにbaxterがindigoになったということは、PCの方もアップグレードしていいということでしょうか。

**Comment by iory** [comment]
集合時間は何時にしましょうか？

**Comment by k-okada** [comment]
時間はわたしは何時でもいいです．

--
◉ Kei Okada

**Comment by umoji** [comment]
自分も何時でも大丈夫です。

**Comment by iory** [comment]
午前中に用事があるので午後3時くらいで大丈夫でしょうか？

**Comment by Tnoriaki** [comment]
僕は午後3時からで大丈夫です！

**Comment by umoji** [comment]
大丈夫です。

**Comment by wkentaro** [comment]
僕も大丈夫なので、
全員、午後3時に研究室集合ということで大丈夫そうですね。
