### ISSUE TITLE
掴んだものをみて画像をとるプログラム

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2014-semi#9]

**Comment by wkentaro** [comment]
This is old. I close.

**Comment by YuOhara** [comment]
ここでの議論は適切にマージされましたでしょうか（どこかのlaunchの中にimage_viewを入れるとか）

それとも，もう作戦上必要ない？

**Comment by wkentaro** [comment]
He sent PR.
https://github.com/start-jsk/2014-semi/pull/54/files

But it is not merged, and it's not used.
