### ISSUE TITLE
baxterのグリッパーを考える

### ISSUE THREAD

**Issue by iory** [start-jsk/2014-semi#90]
100均のアイテムなどをうまく使って、楽に吸い込めるようにしましょう。

ドラえもんアーム
https://vimeo.com/16185356

**Comment by k-okada** [comment]
- コンプレッサーと掃除機とどちらがよいか？

**Comment by k-okada** [comment]
- 物品がすべてつかめることを確認

**Comment by iory** [comment]
gripper
https://www.youtube.com/watch?v=NZtRTPf1uk4

**Comment by wkentaro** [comment]
baxterのvacuumとpanasonicの掃除機の性能比較
https://gist.github.com/wkentaro/ec6a48fd9990bebf1b52

吸引仕事率: http://dyson-twinbird.seesaa.net/article/272491259.html
# [W]
baxter_vacuum_work: 741.607121729
pana_vacuum_work: 430

**Comment by wkentaro** [comment]
@k-okada 
ウレタン素材のクッションが使えるんじゃないかと考えていて、
02/23(月)にドイトへそれ以外の素材も含めて見に行こうと考えているのですが、
購入するときはカードを持っていった方がいいのでしょうか。

**Comment by k-okada** [comment]
はい．７３B1の部屋の人がカードをもっているのでもらってみてください．
買いに行く前に，B1の人にどういうものが欲しいか説明すると，実は学校に有るものだったりすることも
あるので，相談してみてください．

--
◉ Kei Okada


2015-02-21 15:52 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
了解です。
ありがとうございます。

**Comment by wkentaro** [comment]
掃除機を腕に取り付けるという方針で、OnOffをrosで行えるようにしようと考えています。
https://github.com/start-jsk/2014-semi/issues/111

**Comment by m1a1k0o** [comment]
M1杉浦です．とりあえず，バクスターのハンドのアタッチメントと掃除機の先をつなげたようなものを作ろうと思っています．

**Comment by k-okada** [comment]
よいですね．がんばってください．CADができたらおしえてください．

**Comment by m1a1k0o** [comment]
これらをお借りします.

![dsc_0191](https://cloud.githubusercontent.com/assets/11226577/6411575/4d43450e-bebd-11e4-9400-1c1005039fdb.JPG)

**Comment by m1a1k0o** [comment]
バクスターに掃除機の先端が連結できるようにアタッチメントを作成してみました．

![jigu](https://cloud.githubusercontent.com/assets/11226577/6450618/721a5546-c16c-11e4-885e-c5f2354e88b9.png)

**Comment by wkentaro** [comment]
ありがとうございます。
これは注文する形になりますか。

**Comment by m1a1k0o** [comment]
3Dプリンターでプリントしてしまう予定です。

**Comment by wkentaro** [comment]
了解です。
お願いします。

2015年3月3日火曜日、Makoto Sugiura<notifications@github.com>さんは書きました:

> 3Dプリンターでプリントしてしまう予定です。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/90#issuecomment-76895661>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
お、早速できたね
いい感じじゃない。試してみましょう。

2015年3月3日火曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> 了解です。
> お願いします。
>
> 2015年3月3日火曜日、Makoto Sugiura<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
> > 3Dプリンターでプリントしてしまう予定です。
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/start-jsk/2014-semi/issues/90#issuecomment-76895661>.
>
> >
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com <http://www.wkentaro.com>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/90#issuecomment-76903319>.
>


-- 
--
◉ Kei Okada

**Comment by m1a1k0o** [comment]
3Dプリントしてみましたが、途中で3Dプリンターのサポート材がきれてしまったためねじ穴が半分になってしまいました。
穴の大きさ等を調整して、材料が届いて順番があき次第もう一度作成したいと思います。

![jigu_pre](https://cloud.githubusercontent.com/assets/11226577/6480699/e49b196a-c299-11e4-9e66-6dd59740bf9e.jpg)

**Comment by iory** [comment]
すごく綺麗にできるんですね
よろしくお願いします

**Comment by k-okada** [comment]
物品が届いて棚に入れてみました．
よく考えると物は棚の各小部屋の底面に置かれていて，その各小部屋には横からしかアクセスできないので，手首を９０度まげるとか，手首を４５度曲げて，かつ，掃除機の先が４５度まがっているとか，
掃除機の先が９０度曲がったL字型になっているとか，必要そうです．
実際に取り付けて試してみてください．

**Comment by m1a1k0o** [comment]
わかりました．
先端部分を90度まがったものも作成したいと思います．

**Comment by k-okada** [comment]
あと，穴の位置がづれていたのと，ホースの取り回しのためと，ロボット的な操作性の向上のために，チョット手先の前側に穴をつけて，
ホースの入り口は４５度ぐらい傾いているといいらしい，という感じでした．
文章だと伝わりにくいのであとで口頭で説明します．

--
◉ Kei Okada

**Comment by iory** [comment]
新しいアタッチメントはいつ頃できるでしょうか？

**Comment by m1a1k0o** [comment]
作ってみました．問題なければ３Dプリントしてみます．

![jigu_kai](https://cloud.githubusercontent.com/assets/11226577/6550800/35e7e318-c671-11e4-8981-47b8fc19fb9f.png)

**Comment by iory** [comment]
大丈夫だと思います。
よろしくお願いします。

**Comment by m1a1k0o** [comment]
3Dプリンターのサイズに入らなかったため全体的に少し短くしました．

![jigu_kai2](https://cloud.githubusercontent.com/assets/11226577/6552663/9203fbd6-c68b-11e4-9a0a-7946aa554d4f.png)

**Comment by wkentaro** [comment]
水曜日にできるということでしたが、用事があり、研究室には集まらないので木曜日に見せてください。

2015年3月9日月曜日、Makoto Sugiura<notifications@github.com>さんは書きました:

> 3Dプリンターのサイズに入らなかったため全体的に少し短くしました．
>
> [image: jigu_kai2]
> <https://cloud.githubusercontent.com/assets/11226577/6552663/9203fbd6-c68b-11e4-9a0a-7946aa554d4f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/start-jsk/2014-semi/issues/90#issuecomment-77824093>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by m1a1k0o** [comment]
３Dプリンターの扉が開かなくなり、業者に対応してもらうことになり、最短でも木曜日にならないと厳しいかもしれないということになってしまいました．

よろしくお願いいたします．

**Comment by k-okada** [comment]
研究室のdimensionもつかってみましょう．

--
◉ Kei Okada


2015-03-10 18:48 GMT+09:00 Makoto Sugiura <notifications@github.com>:

**Comment by m1a1k0o** [comment]
3Dプリンターの扉が開いたようなので明日の朝には73B2の机の上にアタッチメントをおいておきたいと思います．

**Comment by m1a1k0o** [comment]
完成したアタッチメントです．
73B2においておきたいと思います．

![dsc_0197](https://cloud.githubusercontent.com/assets/11226577/6586769/a08870da-c7bf-11e4-8179-c0dfefb15b8a.JPG)

**Comment by iory** [comment]
ありがとうございます。
早速試してみます。

**Comment by iory** [comment]
baxterに装着してみました。
良い感じです。 ありがとうございます。

![img_20150311_103856](https://cloud.githubusercontent.com/assets/4690682/6588882/91a896d2-c7db-11e4-87fe-efa07f7ae2a6.jpeg)
![img_20150311_103913](https://cloud.githubusercontent.com/assets/4690682/6588883/94aae98e-c7db-11e4-83e4-b0de742e5bd6.jpeg)

**Comment by aginika** [comment]
今回は空気はもれてなさそうでしょうか？

**Comment by iory** [comment]
大丈夫そうです。

**Comment by m1a1k0o** [comment]
先ほど言っていたキネクトとbaxterを固定するものを作ってみました．
キネクトをbaxterのフタから30mm高くして突起部分でキネクトの振動を防ぐものです．
キネクトのネジがカメラの固定用のネジで1/4インチのネジでおそらく研究室内に存在しないのでドイトあたりで入手しないといけないと思います．

![kotei](https://cloud.githubusercontent.com/assets/11226577/6617554/1d9c68ea-c8fd-11e4-8a61-f233f16bd4a0.png)

**Comment by aginika** [comment]
ありがとうございます。完璧です。

**Comment by k-okada** [comment]
完璧ですね．
カメラネジは研究室にいっぱい有ると思うのでメールして聞いてみてください．

--
◉ Kei Okada

**Comment by m1a1k0o** [comment]
カメラネジは工作室にありました．

![dsc_0206](https://cloud.githubusercontent.com/assets/11226577/6650578/490827f6-ca5d-11e4-947a-06267f1c1e1c.JPG)

**Comment by m1a1k0o** [comment]
グリッパーに関して長さなど改善してほしい点などありましたら教えてください.

**Comment by wkentaro** [comment]
いま考えているのは、

* グリッパーの長さをもう少し長くしたい
    * baxterの腕を入れなくても（入れると商品を奥に押し込んでしまう）グリッパーだけで中の物が取れるようにしたい
    * ３Dプリンターに入りきらないので、組み立て式にする必要があるかもしれません
* グリッパーのカーブ後の長さは短いほうがいいのではないか？
    * 長いと背の高い物体が取れない/奥に押し込んでしまう

**Comment by aginika** [comment]
@m1a1k0o この注文でできそうですか？もっと具体的がいいですか？

**Comment by m1a1k0o** [comment]
本日、具体的に聞けたらよいかと思っています．

**Comment by m1a1k0o** [comment]
グリッパーの長さ
　　15〜２０cm程度長くする．
カーブ後の長さ
　　１〜２ｃｍ程度短くする．
で作ってみます．

**Comment by m1a1k0o** [comment]
作ってみました
![long](https://cloud.githubusercontent.com/assets/11226577/7002225/542345d0-dc82-11e4-9636-c9b027a59328.png)
![jigulong](https://cloud.githubusercontent.com/assets/11226577/7002228/5b115aa8-dc82-11e4-9ce3-61932bdc7c62.png)
20㎝程度伸ばし、カーブ後を1.5cm程度短くしています．
筒の方を差し込むことで組み立てようと考えています．

**Comment by m1a1k0o** [comment]
完成したものを73B2の机に置いておきます
接続部分をテープ等で固定したら大丈夫ではないかと考えています

**Comment by iory** [comment]
グリッパー取り付けてみました
吸い込み確認してみましたが問題ないように思います。
また、前に使っていたグリッパーが掃除機のじゃばらとの接合部分が固くてはずすときに壊れてしまいました。
![2015-04-08 16 04 15](https://cloud.githubusercontent.com/assets/4690682/7040415/011e08dc-de0a-11e4-9454-640f47b2ebc4.jpg)
![2015-04-08 16 05 14](https://cloud.githubusercontent.com/assets/4690682/7040416/0120144c-de0a-11e4-8691-8026ba4eba1f.jpg)
![2015-04-08 16 05 44](https://cloud.githubusercontent.com/assets/4690682/7040417/01262b20-de0a-11e4-9a38-b9b910887d97.jpg)

**Comment by iory** [comment]
@m1a1k0oさん
やはり継ぎ接ぎのところが弱くてものを持つとしなるのと、空気が漏れるので、別のように設計する必要がありそうなのですが、お願いできますか？

**Comment by m1a1k0o** [comment]
わかりました．
検討してみます．

**Comment by iory** [comment]
baxterのグリッパーの吸盤ですが、固い方より、柔らかめのほうが良さそうです。

**Comment by aginika** [comment]
@m1a1k0o 吸引ゴムの部分が擦れるとポロッととれてしまうのですが、
いい方法はありますでしょうか？

**Comment by iory** [comment]
@m1a1k0o 掃除機とグリッパーの接合部がまた壊れてしまったのですが、接合部分を厚くすれば壊れにくくなるでしょうか？よろしくお願いします。

**Comment by aginika** [comment]
![image](https://cloud.githubusercontent.com/assets/3803922/7336344/5a5b9f8a-ec34-11e4-88f3-21add33ccca7.jpg)

**Comment by m1a1k0o** [comment]
吸引ゴムですが、テープや接着剤で固定するか結束帯やベルトのようなもので絞めつけて固定するのがいいのかなと思っています．
それでもダメな場合は考えます．

接合部分の方ですが厚くすることで強くはなると思います．
壊れてしまったのは普通に動かしていたときでしょうか？
掃除機から外そうとしたときでしょうか？

**Comment by aginika** [comment]
普通に動かしてた時のはずです。

**Comment by m1a1k0o** [comment]
わかりました．
厚くしたものを作ります．

**Comment by aginika** [comment]
吸引ゴムの方ですが、僕が間違って内側にゴムを入れてしまっていました。
外側につけて外れないか見てみます。

**Comment by iory** [comment]
あと左手のグリッパーを左右反転してもらえないでしょうか。

**Comment by aginika** [comment]
@m1a1k0o には伝えましたが、今日の故障は、ゴムがちぎれたことです。
![img_4399](https://cloud.githubusercontent.com/assets/3803922/7372419/914b4e68-ee01-11e4-8eb8-30fb155dd4df.JPG)

**Comment by aginika** [comment]
改良版をお願いしました。

**Comment by aginika** [comment]
じゃばらにかなり力がかかる角度があるので、これらの回避をするため、
すこし蛇腹接続部分が短くなるように頼んでいます。

![img_4397](https://cloud.githubusercontent.com/assets/3803922/7372435/a6bbf57c-ee01-11e4-8d77-745c1c735a8b.JPG)
![img_4398](https://cloud.githubusercontent.com/assets/3803922/7372436/a6bee084-ee01-11e4-8a51-38c4a4af1e73.JPG)

**Comment by aginika** [comment]
明日には、短いバージョンのハンドができるとのことを @m1a1k0o から聞きました。

**Comment by m1a1k0o** [comment]
短いバージョン完成しました
![dsc_0243](https://cloud.githubusercontent.com/assets/11226577/7405432/4d0d5dd6-ef2d-11e4-9d0d-04cbe28387da.JPG)

**Comment by m1a1k0o** [comment]
吸盤の改良をしました。
固定する部分を倍にして、破れてしまった部分を曲線にしました。
![kyuban_kai](https://cloud.githubusercontent.com/assets/11226577/7406503/b816bd00-ef3e-11e4-82ea-33d38ee81dcf.png)

**Comment by aginika** [comment]
いい感じです！
短めのがポロってすぐとれてしまうので、長い版も試します。

**Comment by wkentaro** [comment]
See https://github.com/start-jsk/2014-semi/issues/310
