### ISSUE TITLE
全部のbinの枠に手が届くようなプログラムを作る

### ISSUE THREAD

**Issue by k-okada** [start-jsk/2014-semi#92]
https://github.com/start-jsk/2014-semi/blob/master/jsk_2014_picking_challenge/scripts/main.l

**Comment by wkentaro** [comment]
stl file -> collada file
http://meshlab.sourceforge.net/

collada file -> eus model
https://github.com/jsk-ros-pkg/jsk_model_tools/blob/master/euscollada/pr2.sh#L15

**Comment by wkentaro** [comment]
MeshlabでSTLファイルをColladaファイルに変換して、ColladaファイルをLispファイルに変換しようとしたところ、エラーが出ました。
https://github.com/wkentaro/2014-semi/tree/euscollada/jsk_2014_picking_challenge/data

```bash
 $ rosrun euscollada collada2eus pod_lowres.dae pod_lowres.yml pod_lowres.l.$$.tmp
Error: Trying to load an invalid COLLADA version for this DOM build!
Error: Failed to load file:/home/wkentaro/catkin_ws/semi/src/2014-semi/jsk_2014_picking_challenge/data/kiva_pod/meshes/pod_lowres.dae
```


euscolladaはcolladaのver1.4.1に対応していないということでしょうか。
```bash
$  cat pod_lowres.dae | grep -i version
<?xml version="1.0" encoding="UTF-8"?>
<COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1">
```

**Comment by k-okada** [comment]
```
<COLLADA xmlns="http://www.collada.org/2008/03/COLLADASchema"
version="1.5.0">
```
と置き換えてみてください．多分ですが，書きだされたファイルのなかでnodeかobjectという名前に成る気がするので，kiva-podとかpod-lowersにして，あと，このオブジェクトを作ったらZ軸が鉛直上向きでZ=０が足の裏になるように調整してみてください．色もいい感じになるといいですね．

.yamlファイルはなくて euscollada pod_lowers.dat pod-loewers.l で動くと思います．

--
◉ Kei Okada

**Comment by wkentaro** [comment]
とりあえず、main.lの方は更新しました。
https://github.com/start-jsk/2014-semi/pull/97

メッセージで動くものはこのあと作ります。

**Comment by wkentaro** [comment]
トピックで動くようにしました。
https://github.com/start-jsk/2014-semi/pull/97

**Comment by wkentaro** [comment]
stlからlispモデルファイルの作り方。 @iory 

まず、meshlabを使って、stlファイルを読み込みdaeファイルとして書き出す。
meshlabは、ソフトウェアセンターなどからインストール可能。
(pod_lowres.stl -> pod_lowres.dae)

```bash
$ sed -i 's/<COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1">/<COLLADA xmlns="http://www.collada.org/2008/03/COLLADASchema"
version="1.5.0">/g' pod_lowres.dae
$ mv pod_lowres.dae pod_lowres.dat
$ rosrun euscollada pod_lowres.dat pod-lowres.l
```
