### ISSUE TITLE
作戦

### ISSUE THREAD

**Issue by wkentaro** [start-jsk/2014-semi#94]
- 各BINには物体がひとつだと仮定
- オーダの順番に手を伸ばす
- 掴んだものが正しいか確認（重さ、色、、、、）

**Comment by wkentaro** [comment]
![2015-02-18 19 06 10](https://cloud.githubusercontent.com/assets/4310419/6246517/45259dde-b7ad-11e4-82d4-30b2a5895c0d.jpg)

**Comment by 130s** [comment]
+1 良いメモ帳ですね．

あと Baxter が Ebola 対策に試用されるそうで，いつぞや @k-okada 先生が仰って (ましたよね？) いたのが実現されつつありあす．
https://twitter.com/Robohub/status/567734627801260034

おじゃましました．TORK @130s

**Comment by wkentaro** [comment]
いえ、 @k-okada 先生に書いていただいたものです;;

そうなんですか。私はその時聞いていなかったのか、知らなかったです。
最近Baxterに少し愛着がわいてきたので、こういうの見ると嬉しいですね。
ありがとうございます。

**Comment by wkentaro** [comment]
以前使っていたgoogle docsを更新しておきました。
https://docs.google.com/presentation/d/1GzXaNuXzJF_OUnuTSdu-CJ9CljfHD8_SApEdvVJtE2g/edit#slide=id.g7a3f94d6f_00
![screen shot 2015-02-20 at 3 50 22 pm](https://cloud.githubusercontent.com/assets/4310419/6282442/703d4a5a-b918-11e4-9a5f-cca8813132f2.png)

**Comment by wkentaro** [comment]
- [ ] 1. 掴めたかどうか判定
- [ ] 2. 認識精度と早さ改善
- [ ] 3. グリッパー改善と掴み方改善
- [ ] 4. arduinoの配線
- [ ] 5. 物体位置推定（つかむときの）

今のところ上のような優先度順でしょうか？

**Comment by aginika** [comment]
よく分かってないのですが、作戦としては
片手のみの吸い込み機構なのでしょうか？

**Comment by wkentaro** [comment]
両手にする案が抜けていますね。ありがとうございます。
最大で12個のターゲットがあり、片手だと時間内に全て取れないので両手にする必要性はあると思います。（実際他のチームがどれくらい取ろうとするかは予想できませんが）

---

ひとつのターゲット物体を取るのに、今の認識速度(2分)を上げて30秒ほどにしても片手だと

* bin with one object: 1min
* bin with two objects: 2~3min
* bin with three objects: 2~4.5min

ほどかかると思います。
制限時間の20分だととれて8ターゲットぐらいではないでしょうか。

**Comment by k-okada** [comment]
遅くなりました
- [ ] 最速の動作スピードでどれぐらい出来るか調べる #177　　認識なしでものを掴んでbinに置くのに何秒かかるか調べる．できるだけ早くする
- [ ] つかめたか動作判定
- [ ] 認識を色々試す．例えば色などで早いものから使っていく．重さも使えるはずだが．．．
- [ ] 認識精度を上げていく．SIFTは画像を間引く．モテそうな部分のオモテウラぐらいでいいはず
- [ ] 掴み方を改善（物体の位置推定も含めて）
かな．
配線を綺麗にするなどなどは当然のこととして．．．

**Comment by wkentaro** [comment]
TODO更新しました。
次は「認識精度を上げていく」段階だと思います。

**Comment by wkentaro** [comment]
モード切り替え条件ですが、以下で考えています。掴んでいるか否かの判別が100%にはならないと思うので、棚の中で一度スイッチを切るようにし、落としたり間違えたりするリスクの無いようにしたいです。

1. 掴んでいるか否かの判別を確実にする。
2. 掴んでいたら、single-item-bin以外は必ずverificationする。(最後の一個でも、同じものを掴むことがあるため)
3. 掴んでいなかったら、place_object, move_for_verificationはしないで、次の棚へ行く。

**Comment by wkentaro** [comment]
TODO更新しました。

* 掴み方を改善（物体の位置推定も含めて）
* 通しテスト

を繰り返す段階ですね。

**Comment by wkentaro** [comment]
今日のテストでは、全部をpickしようとすることに2１分ほどかかりました。
pickしたあとに落ちたものを拾う作戦のためにはpickを早くする必要がありそうです。
